const KEY='voltdrive_operator_v1';

function createParkingBays(siteId,prefix,total,counts,accessible=[],fleet=[]){
 const statuses=[];
 for(let i=0;i<(counts.available||0);i++)statuses.push('available');
 for(let i=0;i<(counts.reserved||0);i++)statuses.push('reserved');
 for(let i=0;i<(counts.blocked||0);i++)statuses.push('blocked');
 while(statuses.length<total)statuses.push('occupied');
 const vehicles=['Tesla Model 3 · 10AA900','Skoda Enyaq · 22BB411','Audi Q4 e-tron · 44CC712','Volvo EX30 · 15DD111','BMW iX1 · 33EE207','Kia EV6 · 48DD731','VW ID.4 · 88EE102'];
 return Array.from({length:total},(_,idx)=>{
  const n=idx+1,status=statuses[idx],type=accessible.includes(n)?'accessible':fleet.includes(n)?'fleet':'standard';
  return {id:`${siteId}-BAY-${String(n).padStart(2,'0')}`,site:siteId,label:`${prefix}-${String(n).padStart(2,'0')}`,status,type,charger:null,occupiedBy:status==='occupied'?vehicles[idx%vehicles.length]:null,reservationId:status==='reserved'?`RSV-${siteId.slice(-2)}${String(n).padStart(2,'0')}`:null,note:status==='blocked'?'Temporarily blocked by operator':null};
 });
}
const parkingSeed=[
 ...createParkingBays('SITE-01','C',16,{available:5,reserved:3,blocked:0},[1,2],[13,14,15,16]),
 ...createParkingBays('SITE-02','W',10,{available:2,reserved:2,blocked:2},[1],[8,9,10]),
 ...createParkingBays('SITE-03','A',12,{available:6,reserved:2,blocked:0},[1,2],[10,11,12]),
 ...createParkingBays('SITE-04','M',8,{available:1,reserved:1,blocked:1},[1],[7,8])
];
export const seed={
 network:{name:'VoltDrive Network Armenia',operator:'Arman Hakobyan',role:'Network Operator',currency:'AMD',timezone:'Asia/Yerevan'},
 sites:[
  {id:'SITE-01',name:'Yerevan Central Hub',address:'Arshakunyats Ave 34, Yerevan',status:'online',capacityKw:600,operatorLimitKw:560,buildingKw:118,evKw:342,solarKw:48,batteryKw:30,reliability:98.7,parking:{total:16,available:5,reserved:3},hours:'24/7',accessMode:'Public · Automatic gate',accessInstructions:'Enter from the south service lane. EV bays are on level P1.',contact:'Central Hub Security',phone:'+374 10 555 101',heightLimitM:2.4,gateStatus:'automatic',utilityFeed:'11 kV · T-01',transformerKva:800,networkConnection:'Fiber + LTE backup',lastInspection:'2026-08-08',nextInspection:'2026-09-08',facilities:['Restrooms','Coffee','Security','24/7 access']},
  {id:'SITE-02',name:'West Hub',address:'Sebastia St 12, Yerevan',status:'attention',capacityKw:420,operatorLimitKw:380,buildingKw:86,evKw:246,solarKw:24,batteryKw:0,reliability:92.4,parking:{total:10,available:2,reserved:2},hours:'24/7',accessMode:'Public · Barrier controlled',accessInstructions:'Use west entrance. Security can override the barrier during incidents.',contact:'West Hub Control Desk',phone:'+374 10 555 202',heightLimitM:2.6,gateStatus:'automatic',utilityFeed:'6 kV · T-02',transformerKva:630,networkConnection:'Fiber + LTE backup',lastInspection:'2026-08-04',nextInspection:'2026-08-25',facilities:['Security','Restrooms','Fleet parking']},
  {id:'SITE-03',name:'Airport Charge Center',address:'Zvartnots Airport, Yerevan',status:'online',capacityKw:480,operatorLimitKw:450,buildingKw:104,evKw:198,solarKw:0,batteryKw:40,reliability:97.1,parking:{total:12,available:6,reserved:2},hours:'24/7',accessMode:'Public · Airport perimeter',accessInstructions:'Follow EV Charging signage from Arrivals road. Security patrols the site continuously.',contact:'Airport Operations',phone:'+374 10 555 303',heightLimitM:3.2,gateStatus:'open',utilityFeed:'10 kV · Airport feeder',transformerKva:700,networkConnection:'Airport fiber + 5G backup',lastInspection:'2026-08-10',nextInspection:'2026-09-10',facilities:['Terminal','Restrooms','Cafe','Security']},
  {id:'SITE-04',name:'Yerevan Mall EV Station',address:'Arshakunyats Ave 34/3, Yerevan',status:'warning',capacityKw:300,operatorLimitKw:260,buildingKw:74,evKw:171,solarKw:18,batteryKw:0,reliability:94.2,parking:{total:8,available:1,reserved:1},hours:'08:00–23:00',accessMode:'Public · Mall parking',accessInstructions:'Enter via P2 ramp and follow EV signs. Access follows mall parking hours.',contact:'Mall Parking Office',phone:'+374 10 555 404',heightLimitM:2.2,gateStatus:'automatic',utilityFeed:'0.4 kV · Mall LV board',transformerKva:500,networkConnection:'Mall LAN + LTE backup',lastInspection:'2026-08-06',nextInspection:'2026-08-28',facilities:['Shopping','Food court','Restrooms','Security']}
 ],
 parkingBays:parkingSeed,
 chargers:[
  {id:'CH-101',site:'SITE-01',name:'DC-101',vendor:'ABB',model:'Terra 360',serial:'ABB-T360-101',maxKw:360,status:'busy',health:97,temp:42,firmware:'6.4.2',uptime:99.1,connectorIds:['CON-101-1','CON-101-2']},
  {id:'CH-102',site:'SITE-01',name:'DC-102',vendor:'Alpitronic',model:'HYC300',serial:'ALP-300-102',maxKw:300,status:'online',health:99,temp:37,firmware:'3.8.1',uptime:99.6,connectorIds:['CON-102-1','CON-102-2']},
  {id:'CH-103',site:'SITE-01',name:'AC-103',vendor:'Wallbox',model:'Commander 2',serial:'WB-C2-103',maxKw:22,status:'reserved',health:96,temp:31,firmware:'2.7.0',uptime:98.4,connectorIds:['CON-103-1']},
  {id:'CH-201',site:'SITE-02',name:'DC-201',vendor:'ABB',model:'Terra 184',serial:'ABB-T184-201',maxKw:180,status:'faulted',health:58,temp:71,firmware:'6.3.9',uptime:89.8,connectorIds:['CON-201-1','CON-201-2']},
  {id:'CH-202',site:'SITE-02',name:'DC-202',vendor:'Alpitronic',model:'HYC150',serial:'ALP-150-202',maxKw:150,status:'busy',health:91,temp:48,firmware:'3.8.1',uptime:95.5,connectorIds:['CON-202-1','CON-202-2']},
  {id:'CH-203',site:'SITE-02',name:'AC-203',vendor:'Wallbox',model:'Pulsar Pro',serial:'WB-PP-203',maxKw:22,status:'maintenance',health:74,temp:35,firmware:'2.6.5',uptime:91.2,connectorIds:['CON-203-1']},
  {id:'CH-301',site:'SITE-03',name:'DC-301',vendor:'Siemens',model:'Sicharge D',serial:'SIE-D-301',maxKw:300,status:'busy',health:98,temp:41,firmware:'5.2.0',uptime:99.0,connectorIds:['CON-301-1','CON-301-2']},
  {id:'CH-302',site:'SITE-03',name:'DC-302',vendor:'ABB',model:'Terra 124',serial:'ABB-T124-302',maxKw:120,status:'online',health:95,temp:39,firmware:'6.4.2',uptime:97.6,connectorIds:['CON-302-1','CON-302-2']},
  {id:'CH-303',site:'SITE-03',name:'AC-303',vendor:'Wallbox',model:'Commander 2',serial:'WB-C2-303',maxKw:22,status:'online',health:99,temp:29,firmware:'2.7.0',uptime:99.8,connectorIds:['CON-303-1']},
  {id:'CH-401',site:'SITE-04',name:'DC-401',vendor:'ABB',model:'Terra 124',serial:'ABB-T124-401',maxKw:120,status:'busy',health:94,temp:44,firmware:'6.4.2',uptime:96.1,connectorIds:['CON-401-1','CON-401-2']},
  {id:'CH-402',site:'SITE-04',name:'DC-402',vendor:'Siemens',model:'Sicharge UC',serial:'SIE-UC-402',maxKw:150,status:'warning',health:81,temp:56,firmware:'5.1.4',uptime:93.6,connectorIds:['CON-402-1','CON-402-2']},
  {id:'CH-403',site:'SITE-04',name:'AC-403',vendor:'Wallbox',model:'Pulsar Pro',serial:'WB-PP-403',maxKw:22,status:'online',health:97,temp:30,firmware:'2.7.0',uptime:98.9,connectorIds:['CON-403-1']}
 ],
 connectors:[
  {id:'CON-101-1',charger:'CH-101',number:1,type:'CCS2',maxKw:360,status:'busy',locked:true},{id:'CON-101-2',charger:'CH-101',number:2,type:'CCS2',maxKw:180,status:'available',locked:false},
  {id:'CON-102-1',charger:'CH-102',number:1,type:'CCS2',maxKw:300,status:'available',locked:false},{id:'CON-102-2',charger:'CH-102',number:2,type:'CCS2',maxKw:150,status:'available',locked:false},
  {id:'CON-103-1',charger:'CH-103',number:1,type:'Type 2',maxKw:22,status:'reserved',locked:false},
  {id:'CON-201-1',charger:'CH-201',number:1,type:'CCS2',maxKw:180,status:'faulted',locked:true,fault:'EVSE-CC-07'},{id:'CON-201-2',charger:'CH-201',number:2,type:'CCS2',maxKw:90,status:'disabled',locked:false,fault:'LOCK-22'},
  {id:'CON-202-1',charger:'CH-202',number:1,type:'CCS2',maxKw:150,status:'busy',locked:true},{id:'CON-202-2',charger:'CH-202',number:2,type:'CCS2',maxKw:75,status:'available',locked:false},
  {id:'CON-203-1',charger:'CH-203',number:1,type:'Type 2',maxKw:22,status:'maintenance',locked:false},
  {id:'CON-301-1',charger:'CH-301',number:1,type:'CCS2',maxKw:300,status:'busy',locked:true},{id:'CON-301-2',charger:'CH-301',number:2,type:'CCS2',maxKw:150,status:'available',locked:false},
  {id:'CON-302-1',charger:'CH-302',number:1,type:'CCS2',maxKw:120,status:'available',locked:false},{id:'CON-302-2',charger:'CH-302',number:2,type:'CCS2',maxKw:60,status:'available',locked:false},
  {id:'CON-303-1',charger:'CH-303',number:1,type:'Type 2',maxKw:22,status:'available',locked:false},
  {id:'CON-401-1',charger:'CH-401',number:1,type:'CCS2',maxKw:120,status:'busy',locked:true},{id:'CON-401-2',charger:'CH-401',number:2,type:'CCS2',maxKw:60,status:'available',locked:false},
  {id:'CON-402-1',charger:'CH-402',number:1,type:'CCS2',maxKw:150,status:'warning',locked:false,fault:'TEMP-14'},{id:'CON-402-2',charger:'CH-402',number:2,type:'CCS2',maxKw:75,status:'available',locked:false},
  {id:'CON-403-1',charger:'CH-403',number:1,type:'Type 2',maxKw:22,status:'available',locked:false}
 ],
 sessions:[
  {id:'CS-260814-091',driver:'Mariam A.',vehicle:'Tesla Model Y · 34AA456',site:'SITE-01',charger:'CH-101',connector:'CON-101-1',status:'active',started:'15:16',durationMin:41,socStart:24,soc:68,target:80,powerKw:112,energyKwh:51.6,cost:7380,payment:'preauthorized'},
  {id:'CS-260814-092',driver:'Arsen H.',vehicle:'Hyundai Ioniq 5 · 55BB808',site:'SITE-02',charger:'CH-202',connector:'CON-202-1',status:'active',started:'15:28',durationMin:29,socStart:18,soc:51,target:90,powerKw:91,energyKwh:37.8,cost:5580,payment:'preauthorized'},
  {id:'CS-260814-093',driver:'Lilit S.',vehicle:'BMW i4 · 12CC204',site:'SITE-03',charger:'CH-301',connector:'CON-301-1',status:'active',started:'15:34',durationMin:23,socStart:31,soc:57,target:85,powerKw:138,energyKwh:32.2,cost:4910,payment:'preauthorized'},
  {id:'CS-260814-094',driver:'Narek G.',vehicle:'Kia EV6 · 48DD731',site:'SITE-04',charger:'CH-401',connector:'CON-401-1',status:'active',started:'15:41',durationMin:16,socStart:42,soc:61,target:80,powerKw:84,energyKwh:20.6,cost:3180,payment:'preauthorized'},
  {id:'CS-260814-088',driver:'Sona P.',vehicle:'VW ID.4 · 88EE102',site:'SITE-01',charger:'CH-102',connector:'CON-102-1',status:'completed',started:'14:22',durationMin:49,socStart:21,soc:82,target:80,powerKw:0,energyKwh:58.4,cost:8120,payment:'paid'},
  {id:'CS-260814-087',driver:'Gor T.',vehicle:'Mercedes EQE · 77FF515',site:'SITE-02',charger:'CH-201',connector:'CON-201-1',status:'failed',started:'14:08',durationMin:12,socStart:35,soc:39,target:80,powerKw:0,energyKwh:4.2,cost:0,payment:'cancelled',stopReason:'Connector communication fault'},
  {id:'CS-260814-086',driver:'Tatev M.',vehicle:'Volvo EX40 · 19GG820',site:'SITE-04',charger:'CH-402',connector:'CON-402-1',status:'interrupted',started:'13:46',durationMin:21,socStart:28,soc:45,target:80,powerKw:0,energyKwh:15.7,cost:2480,payment:'pending',stopReason:'Thermal protection intervention'},
  {id:'CS-260814-085',driver:'Hayk R.',vehicle:'Audi Q8 e-tron · 71HH314',site:'SITE-03',charger:'CH-302',connector:'CON-302-1',status:'completed',started:'13:02',durationMin:54,socStart:17,soc:81,target:80,powerKw:0,energyKwh:63.1,cost:8760,payment:'paid'}
 ],
 reservations:[
  {id:'RSV-5401',driver:'Anna M.',vehicle:'Tesla Model 3 · 10AA900',site:'SITE-01',charger:'CH-103',bay:'B-07',arrival:'16:20',durationMin:60,status:'confirmed',fee:500},
  {id:'RSV-5402',driver:'David K.',vehicle:'Skoda Enyaq · 22BB411',site:'SITE-03',charger:null,bay:null,arrival:'16:35',durationMin:45,status:'confirmed',fee:500},
  {id:'RSV-5403',driver:'Suren A.',vehicle:'Audi Q4 e-tron · 44CC712',site:'SITE-02',charger:null,bay:'W-03',arrival:'16:40',durationMin:50,status:'waiting',fee:0},
  {id:'RSV-5404',driver:'Meri H.',vehicle:'Volvo EX30 · 15DD111',site:'SITE-04',charger:null,bay:null,arrival:'17:00',durationMin:40,status:'confirmed',fee:500}
 ],
 maintenanceAlerts:[
  {id:'AL-901',site:'SITE-02',charger:'CH-201',connector:'CON-201-1',severity:'critical',status:'open',code:'EVSE-CC-07',title:'Repeated connector communication fault',body:'3 failed sessions in 24 minutes. Remote reset failed.',created:'15:39',ticket:'MT-4407'},
  {id:'AL-902',site:'SITE-04',charger:'CH-402',connector:'CON-402-1',severity:'high',status:'open',code:'TEMP-14',title:'Connector temperature above threshold',body:'56 °C and rising during idle state.',created:'15:47',ticket:null},
  {id:'AL-903',site:'SITE-02',charger:'CH-203',connector:'CON-203-1',severity:'normal',status:'monitoring',code:'PM-DUE',title:'Preventive service overdue',body:'Quarterly inspection overdue by 4 days.',created:'13:10',ticket:'MT-4398'},
  {id:'AL-904',site:'SITE-01',charger:'CH-101',connector:null,severity:'normal',status:'monitoring',code:'GRID-PEAK',title:'Site approaching configured peak',body:'EV load is above 85% of current site allocation.',created:'15:52',ticket:null}
 ],
 maintenanceTickets:[
  {id:'MT-4407',alert:'AL-901',site:'SITE-02',charger:'CH-201',priority:'critical',status:'assigned',technician:'Gevor Martirosyan'},
  {id:'MT-4398',alert:'AL-903',site:'SITE-02',charger:'CH-203',priority:'normal',status:'in_progress',technician:'Ani Sargsyan'}
 ],
 supportCases:[
  {id:'SUP-7821',customer:'Mariam A.',subject:'Cable will not release after charge',site:'SITE-01',charger:'CH-101',priority:'high',status:'open',ageMin:6},
  {id:'SUP-7820',customer:'Arsen H.',subject:'Reservation bay occupied by ICE vehicle',site:'SITE-02',charger:null,priority:'normal',status:'open',ageMin:14},
  {id:'SUP-7818',customer:'Lilit S.',subject:'Invoice company details need correction',site:'SITE-03',charger:null,priority:'low',status:'pending',ageMin:31},
  {id:'SUP-7815',customer:'Suren A.',subject:'Waiting list assignment question',site:'SITE-02',charger:null,priority:'normal',status:'open',ageMin:42}
 ],
 revenue:{today:276420,energy:243180,reservations:14500,idle:9170,parking:6840,other:2730,transactions:68,failedPayments:2,refunds:1},
 emergencyEvents:[
  {id:'EM-120',site:'SITE-02',charger:'CH-201',type:'Safety isolation requested',status:'monitoring',created:'15:41',owner:'Arman Hakobyan'}
 ],
 commandHistory:[
  {id:'CMD-1001',time:'15:42',action:'Restart charger',target:'CH-201',result:'Failed',operator:'Arman Hakobyan'},
  {id:'CMD-1002',time:'15:18',action:'Release cable',target:'CON-101-1',result:'Success',operator:'Arman Hakobyan'}
 ]
};


const supportCaseTechnicalSeed={
 'SUP-7821':{channel:'phone',category:'charging',slaTargetMin:15,elapsedMin:6,owner:'Arman Hakobyan',team:'Network Operations',customerPhone:'+374 91 440 821',customerEmail:'mariam.a@example.com',vehicle:'Tesla Model Y · 34AA456',session:'CS-260814-091',reservation:null,transaction:null,connector:'CON-101-1',bay:null,customerPlan:'VoltDrive Plus',summary:'Customer reports charging is complete on the vehicle, but the backend session still appears active and the CCS cable remains locked.',desiredResolution:'Safely end the backend session and release the cable.',tags:['Cable lock','Live session','Customer waiting'],internalNotes:[{time:'15:48',author:'Call Center',text:'Customer is standing beside DC-101. Vehicle screen shows charging complete.'}],timeline:[{time:'15:45',type:'customer',title:'Phone case opened',detail:'Customer reported cable would not release after charging.'},{time:'15:47',type:'system',title:'Session context attached',detail:'Active session CS-260814-091 matched to charger CH-101 / connector 1.'},{time:'15:48',type:'note',title:'Call center note',detail:'Customer remains on site and can confirm connector state.'}]},
 'SUP-7820':{channel:'chat',category:'reservation',slaTargetMin:30,elapsedMin:14,owner:'Network Support',team:'Site Operations',customerPhone:'+374 93 201 775',customerEmail:'arsen.h@example.com',vehicle:'Hyundai Ioniq 5 · 55BB808',session:'CS-260814-092',reservation:null,transaction:null,connector:null,bay:'SITE-02-BAY-07',customerPlan:'Standard',summary:'Customer arrived at West Hub and found an ICE vehicle occupying an EV charging bay.',desiredResolution:'Contact site security and restore access to an EV bay.',tags:['Parking bay','ICE blocking','Site access'],internalNotes:[],timeline:[{time:'15:37',type:'customer',title:'Chat case opened',detail:'Customer sent a photo of a non-EV vehicle blocking the charging bay.'},{time:'15:39',type:'system',title:'Site context attached',detail:'West Hub parking and site operations context loaded.'}]},
 'SUP-7818':{channel:'email',category:'billing',slaTargetMin:120,elapsedMin:31,owner:'Billing Support',team:'Billing',customerPhone:'+374 95 411 620',customerEmail:'lilit.s@example.com',vehicle:'BMW i4 · 12CC204',session:'CS-260814-093',reservation:null,transaction:'TX-817-1044',connector:'CON-301-1',bay:null,customerPlan:'Roaming',summary:'Customer needs company details corrected before the final invoice is issued for a roaming charging session.',desiredResolution:'Confirm billing profile and route the correction to financial operations.',tags:['Invoice','Roaming','Company details'],internalNotes:[{time:'15:29',author:'Billing Support',text:'Awaiting company tax ID from customer.'}],timeline:[{time:'15:20',type:'customer',title:'Email received',detail:'Customer requested company invoice details be corrected.'},{time:'15:29',type:'note',title:'Billing requested tax ID',detail:'Reply sent asking for legal name and tax identifier.'}]},
 'SUP-7815':{channel:'chat',category:'reservation',slaTargetMin:45,elapsedMin:42,owner:'Network Support',team:'Reservations',customerPhone:'+374 99 720 118',customerEmail:'suren.a@example.com',vehicle:'Audi Q4 e-tron · 44CC712',session:null,reservation:'RSV-5403',transaction:null,connector:null,bay:'SITE-02-BAY-03',customerPlan:'Standard',summary:'Customer wants to know whether the waiting-list reservation at West Hub will be assigned before arrival.',desiredResolution:'Explain assignment logic and confirm waiting-list position or available alternative.',tags:['Waiting list','Reservation','Assignment'],internalNotes:[],timeline:[{time:'15:09',type:'customer',title:'Chat case opened',detail:'Customer asked for waiting-list assignment status.'},{time:'15:12',type:'system',title:'Reservation attached',detail:'Waiting reservation RSV-5403 matched to the case.'}]},
 'SUP-7812':{channel:'phone',category:'billing',slaTargetMin:20,elapsedMin:18,owner:'Arman Hakobyan',team:'Billing',customerPhone:'+374 77 334 112',customerEmail:'tatev.m@example.com',vehicle:'Volvo EX40 · 19GG820',session:'CS-260814-086',reservation:null,transaction:'TX-817-1046',connector:'CON-402-1',bay:null,customerPlan:'Standard',priority:'high',status:'pending',subject:'Partial refund after thermal interruption',site:'SITE-04',charger:'CH-402',summary:'Charging session was interrupted by thermal protection. Customer requests a partial adjustment while the payment remains pending settlement.',desiredResolution:'Review meter reconciliation and determine whether a partial refund is justified.',tags:['Refund review','Interrupted session','Payment pending'],internalNotes:[{time:'15:36',author:'Network Support',text:'Thermal event is already visible in session diagnostics.'}],timeline:[{time:'15:31',type:'customer',title:'Phone case opened',detail:'Customer requested charge adjustment after interrupted session.'},{time:'15:36',type:'note',title:'Technical context verified',detail:'TEMP-14 interruption confirmed on CH-402.'}]},
 'SUP-7809':{channel:'email',category:'billing',slaTargetMin:120,elapsedMin:76,owner:'Billing Support',team:'Billing',customerPhone:'+374 96 118 002',customerEmail:'sona.p@example.com',vehicle:'VW ID.4 · 88EE102',session:'CS-260814-088',reservation:null,transaction:'TX-817-1041',connector:'CON-102-1',bay:null,customerPlan:'VoltDrive Plus',priority:'normal',status:'resolved',subject:'Idle fee explanation request',site:'SITE-01',charger:'CH-102',summary:'Customer asked why a 350 AMD idle fee was charged after charging completed.',desiredResolution:'Explain idle fee policy and confirm billing accuracy.',resolution:'Explained 7-minute idle period and confirmed the charge matches tariff policy.',resolvedAt:'14:48',tags:['Idle fee','Billing'],internalNotes:[{time:'14:46',author:'Billing Support',text:'Transaction and session timestamps verified.'}],timeline:[{time:'13:32',type:'customer',title:'Email case opened',detail:'Customer disputed idle fee.'},{time:'14:46',type:'note',title:'Billing verified',detail:'7 billable idle minutes confirmed.'},{time:'14:48',type:'resolved',title:'Case resolved',detail:'Policy explanation sent to customer and fee confirmed.'}]}
};
seed.supportCases=seed.supportCases.map(c=>({...c,...(supportCaseTechnicalSeed[c.id]||{})}));
for(const [id,c] of Object.entries(supportCaseTechnicalSeed)){if(!seed.supportCases.some(x=>x.id===id)) seed.supportCases.push({id,...c})}

const emergencyEventTechnicalSeed={
 'EM-120':{severity:'critical',category:'electrical',title:'Safety isolation requested on DC-201',description:'Repeated EVSE control faults and elevated cabinet temperature require controlled isolation before field inspection.',status:'monitoring',connector:'CON-201-1',session:'CS-260814-087',elapsedMin:18,detectedBy:'Automatic safety rule',customerImpact:'High',responseTeam:'Network Operations',siteContact:'West Hub Control Desk',powerState:'energized',isolation:{site:false,charger:true,connector:true,powerConfirmed:false},impactedSessions:1,notifications:['Site Operations notified'],recoveryChecklist:[{id:'rc-1',label:'Affected charging session stopped',required:true,done:true},{id:'rc-2',label:'Connector disabled and cable released',required:true,done:true},{id:'rc-3',label:'Charger isolated from customer use',required:true,done:true},{id:'rc-4',label:'Field technician verifies safe condition',required:true,done:false},{id:'rc-5',label:'Power isolation / LOTO confirmed when required',required:true,done:false},{id:'rc-6',label:'Post-repair diagnostics passed',required:true,done:false}],timeline:[{time:'15:41',type:'detected',title:'Safety isolation requested',detail:'Automatic rule correlated EVSE-CC-07 with elevated cabinet temperature.'},{time:'15:43',type:'action',title:'Charger removed from service',detail:'CH-201 placed in protected state while incident is investigated.'},{time:'15:46',type:'notification',title:'Site operations notified',detail:'West Hub control desk asked to secure the charger area.'}]},
 'EM-121':{severity:'high',category:'thermal',title:'Connector thermal threshold exceeded',description:'Connector 1 temperature on DC-402 exceeded the configured safety threshold during a customer session.',status:'acknowledged',site:'SITE-04',charger:'CH-402',connector:'CON-402-1',session:'CS-260814-086',created:'15:31',elapsedMin:28,owner:'Arman Hakobyan',detectedBy:'Charger telemetry',customerImpact:'Medium',responseTeam:'Network Operations',siteContact:'Mall Parking Office',powerState:'energized',isolation:{site:false,charger:false,connector:true,powerConfirmed:false},impactedSessions:1,notifications:['Customer Support informed'],recoveryChecklist:[{id:'rc-1',label:'Affected charging session stopped',required:true,done:true},{id:'rc-2',label:'Connector disabled',required:true,done:true},{id:'rc-3',label:'Connector temperature below recovery threshold',required:true,done:false},{id:'rc-4',label:'Cable and contacts visually inspected',required:true,done:false},{id:'rc-5',label:'Insulation / contactor diagnostics passed',required:true,done:false}],timeline:[{time:'15:31',type:'detected',title:'Thermal protection triggered',detail:'TEMP-14 recorded on CON-402-1.'},{time:'15:33',type:'acknowledged',title:'Incident acknowledged',detail:'Network operator accepted incident ownership.'},{time:'15:35',type:'action',title:'Connector disabled',detail:'Connector removed from customer availability.'}]},
 'EM-122':{severity:'normal',category:'site',title:'Airport access lane temporarily restricted',description:'Security response briefly restricted access to charging bays during an airport perimeter incident.',status:'resolved',site:'SITE-03',charger:null,connector:null,session:null,created:'13:08',elapsedMin:52,owner:'Airport Operations',detectedBy:'Site security',customerImpact:'Low',responseTeam:'Site Operations',siteContact:'Airport Operations',powerState:'normal',isolation:{site:false,charger:false,connector:false,powerConfirmed:true},impactedSessions:0,notifications:['Airport security coordinated'],resolution:'Charging equipment remained safe. Access reopened after security clearance.',resolvedAt:'14:00',recoveryChecklist:[{id:'rc-1',label:'Site security clearance received',required:true,done:true},{id:'rc-2',label:'Charging bays inspected before reopening',required:true,done:true},{id:'rc-3',label:'Customer access restored',required:true,done:true}],timeline:[{time:'13:08',type:'detected',title:'Site access restriction reported',detail:'Airport security requested temporary control of the EV lane.'},{time:'13:11',type:'notification',title:'Customer access notice issued',detail:'Drivers were redirected to available airport parking.'},{time:'13:57',type:'recovery',title:'Security clearance received',detail:'Charging area cleared for reopening.'},{time:'14:00',type:'resolved',title:'Incident resolved',detail:'Normal access restored.'}]},
 'EM-123':{severity:'low',category:'vehicle',title:'Customer requested assisted cable release',description:'Session completed normally but the customer requested operator assistance to verify cable release.',status:'contained',site:'SITE-01',charger:'CH-102',connector:'CON-102-1',session:'CS-260814-088',created:'15:12',elapsedMin:11,owner:'Network Support',detectedBy:'Customer Support',customerImpact:'Low',responseTeam:'Network Support',siteContact:'Central Hub Security',powerState:'normal',isolation:{site:false,charger:false,connector:false,powerConfirmed:true},impactedSessions:0,notifications:[],recoveryChecklist:[{id:'rc-1',label:'Session confirmed completed',required:true,done:true},{id:'rc-2',label:'Connector de-energized',required:true,done:true},{id:'rc-3',label:'Cable lock released',required:true,done:true},{id:'rc-4',label:'Customer confirms safe departure',required:true,done:false}],timeline:[{time:'15:12',type:'detected',title:'Support escalation received',detail:'Customer requested confirmation that the connector was safe to remove.'},{time:'15:14',type:'action',title:'Connector state verified',detail:'Session was complete and connector was not energized.'},{time:'15:15',type:'action',title:'Cable release command successful',detail:'Lock state reported open.'}]}
};
seed.emergencyEvents=seed.emergencyEvents.map(e=>({...e,...(emergencyEventTechnicalSeed[e.id]||{})}));
for(const [id,e] of Object.entries(emergencyEventTechnicalSeed)){if(!seed.emergencyEvents.some(x=>x.id===id)) seed.emergencyEvents.push({id,...e})}


const maintenanceAlertTechnicalSeed={
 'AL-901':{source:'automatic',category:'connector',firstSeen:'15:18',lastSeen:'15:39',occurrences:4,affectedSessions:3,customerImpact:'High',slaTargetMin:30,elapsedMin:24,owner:'Network Operations',acknowledgedAt:'15:40',probableCauses:['Control pilot communication instability','Connector controller fault','Intermittent harness or terminal connection'],suggestedRecovery:['Verify heartbeat and OCPP connection','Reset affected connector','Restart charger if no active sessions remain'],diagnostics:{chargerHealth:58,chargerTempC:71,connectorTempC:47,networkLatencyMs:142,signal:'Fair',lastHeartbeat:'15:56:08',isolationMohm:4.8,inputVoltageV:405,errors24h:7},recoveryAttempts:[{time:'15:31',command:'Reset Connector',result:'Failed',detail:'Connector returned EVSE-CC-07 after reset.'},{time:'15:42',command:'Restart Charger',result:'Failed',detail:'Fault returned after charger boot.'}],timeline:[{time:'15:18',type:'critical',title:'Fault detected',detail:'EVSE-CC-07 reported on connector 1.'},{time:'15:26',type:'warning',title:'Repeated session failures',detail:'Second and third charging attempts failed.'},{time:'15:31',type:'failed',title:'Remote connector reset failed',detail:'Fault reappeared after reset.'},{time:'15:40',type:'recovery',title:'Alert acknowledged',detail:'Network operator started triage.'},{time:'15:43',type:'ticket',title:'Field ticket MT-4407 assigned',detail:'Gevor Martirosyan assigned for site visit.'}]},
 'AL-902':{source:'predictive',category:'thermal',firstSeen:'15:44',lastSeen:'15:47',occurrences:2,affectedSessions:0,customerImpact:'Medium',slaTargetMin:45,elapsedMin:12,owner:'Network Operations',probableCauses:['Connector temperature sensor drift','Cooling airflow restriction','Recent high-current thermal soak'],suggestedRecovery:['Verify live temperature trend','Temporary derate charger output','Dispatch technician if temperature continues rising'],diagnostics:{chargerHealth:81,chargerTempC:56,connectorTempC:58,networkLatencyMs:48,signal:'Good',lastHeartbeat:'15:58:22',isolationMohm:8.4,inputVoltageV:409,errors24h:2},recoveryAttempts:[],timeline:[{time:'15:44',type:'warning',title:'Thermal warning detected',detail:'Connector temperature crossed configured warning threshold.'},{time:'15:47',type:'warning',title:'Temperature still rising',detail:'Predictive rule escalated severity to high.'}]},
 'AL-903':{source:'preventive',category:'preventive',firstSeen:'13:10',lastSeen:'13:10',occurrences:1,affectedSessions:0,customerImpact:'Low',slaTargetMin:480,elapsedMin:170,owner:'Service Operations',acknowledgedAt:'13:18',probableCauses:['Quarterly preventive inspection overdue'],suggestedRecovery:['No remote recovery required','Complete inspection checklist and close field ticket'],diagnostics:{chargerHealth:74,chargerTempC:35,connectorTempC:31,networkLatencyMs:66,signal:'Good',lastHeartbeat:'15:57:51',isolationMohm:9.1,inputVoltageV:231,errors24h:0},recoveryAttempts:[],timeline:[{time:'13:10',type:'warning',title:'Preventive service alert',detail:'Quarterly maintenance exceeded due date by four days.'},{time:'13:18',type:'ticket',title:'Ticket MT-4398 in progress',detail:'Ani Sargsyan started preventive service.'}]},
 'AL-904':{source:'predictive',category:'energy',firstSeen:'15:52',lastSeen:'15:52',occurrences:1,affectedSessions:1,customerImpact:'Low',slaTargetMin:60,elapsedMin:7,owner:'Energy Operations',probableCauses:['EV demand approaching operator site limit','Concurrent high-power sessions'],suggestedRecovery:['Temporary derate selected charger','Monitor site EV load for 15 minutes'],diagnostics:{chargerHealth:97,chargerTempC:42,connectorTempC:39,networkLatencyMs:31,signal:'Excellent',lastHeartbeat:'15:58:42',siteEvKw:342,siteLimitKw:560,errors24h:0},recoveryAttempts:[],timeline:[{time:'15:52',type:'warning',title:'Peak load threshold crossed',detail:'Site EV load exceeded configured warning percentage.'}]}
};

const maintenanceTicketTechnicalSeed={
 'MT-4407':{connector:'CON-201-1',created:'15:43',eta:'16:20',description:'Investigate repeated EVSE-CC-07 communication failures. Remote reset and charger restart did not clear the fault.',parts:['Connector control board · inspect','CCS2 signal harness · inspect'],checklist:'DC Charger Fault Diagnosis v3',timeline:[{time:'15:43',title:'Ticket created',detail:'Created from critical alert AL-901.'},{time:'15:45',title:'Technician assigned',detail:'Gevor Martirosyan accepted the job.'}]},
 'MT-4398':{connector:'CON-203-1',created:'13:18',eta:'15:30',description:'Complete overdue quarterly preventive inspection and verify AC connector condition.',parts:[],checklist:'Quarterly Preventive Service v2',timeline:[{time:'13:18',title:'Ticket assigned',detail:'Ani Sargsyan assigned.'},{time:'14:52',title:'Work started',detail:'Technician marked job in progress.'}]}
};

seed.technicians=[
 {id:'TECH-01',name:'Gevor Martirosyan',status:'on_site',region:'Yerevan West',skills:['DC high power','ABB Terra','OCPP diagnostics'],onCall:true,activeJobs:1,etaMin:0},
 {id:'TECH-02',name:'Ani Sargsyan',status:'in_progress',region:'Yerevan Central',skills:['AC chargers','Preventive service','Safety inspection'],onCall:false,activeJobs:1,etaMin:0},
 {id:'TECH-03',name:'Aram Petrosyan',status:'available',region:'Yerevan / Airport',skills:['DC high power','Siemens Sicharge','Thermal systems'],onCall:true,activeJobs:0,etaMin:28},
 {id:'TECH-04',name:'Meline Grigoryan',status:'available',region:'Yerevan Central',skills:['Networking','OCPP','Payment terminals'],onCall:false,activeJobs:0,etaMin:34}
];
seed.maintenanceAlerts=seed.maintenanceAlerts.map(a=>({...a,...maintenanceAlertTechnicalSeed[a.id]}));
seed.maintenanceTickets=seed.maintenanceTickets.map(t=>({...t,...maintenanceTicketTechnicalSeed[t.id]}));

const chargerTechnicalSeed={
 'CH-101':{protocol:'OCPP 2.0.1',ip:'10.41.1.101',network:'Fiber · LTE backup',signal:'Excellent',lastHeartbeat:'15:58:42',installDate:'2025-11-14',lastService:'2026-07-22',nextService:'2026-10-22',meterKwh:184220,errors24h:0,reboots30d:1,cabinet:'closed',emergencyStop:false,firmwareLatest:'6.4.2',firmwareStatus:'current',inputVoltage:411,gridPhase:'3-phase'},
 'CH-102':{protocol:'OCPP 2.0.1',ip:'10.41.1.102',network:'Fiber · LTE backup',signal:'Excellent',lastHeartbeat:'15:58:39',installDate:'2026-01-18',lastService:'2026-08-02',nextService:'2026-11-02',meterKwh:99280,errors24h:0,reboots30d:0,cabinet:'closed',emergencyStop:false,firmwareLatest:'3.8.1',firmwareStatus:'current',inputVoltage:408,gridPhase:'3-phase'},
 'CH-103':{protocol:'OCPP 1.6J',ip:'10.41.1.103',network:'LAN',signal:'Good',lastHeartbeat:'15:58:31',installDate:'2025-09-03',lastService:'2026-06-28',nextService:'2026-09-28',meterKwh:28140,errors24h:0,reboots30d:0,cabinet:'closed',emergencyStop:false,firmwareLatest:'2.7.0',firmwareStatus:'current',inputVoltage:231,gridPhase:'3-phase'},
 'CH-201':{protocol:'OCPP 2.0.1',ip:'10.42.1.201',network:'Fiber · LTE backup',signal:'Fair',lastHeartbeat:'15:56:08',installDate:'2025-07-21',lastService:'2026-08-10',nextService:'2026-09-10',meterKwh:223870,errors24h:7,reboots30d:4,cabinet:'closed',emergencyStop:false,firmwareLatest:'6.4.2',firmwareStatus:'update_available',inputVoltage:405,gridPhase:'3-phase'},
 'CH-202':{protocol:'OCPP 2.0.1',ip:'10.42.1.202',network:'Fiber · LTE backup',signal:'Good',lastHeartbeat:'15:58:36',installDate:'2025-12-08',lastService:'2026-07-30',nextService:'2026-10-30',meterKwh:142610,errors24h:1,reboots30d:1,cabinet:'closed',emergencyStop:false,firmwareLatest:'3.8.1',firmwareStatus:'current',inputVoltage:409,gridPhase:'3-phase'},
 'CH-203':{protocol:'OCPP 1.6J',ip:'10.42.1.203',network:'LAN · LTE backup',signal:'Good',lastHeartbeat:'15:54:17',installDate:'2025-05-15',lastService:'2026-05-10',nextService:'2026-08-10',meterKwh:33740,errors24h:0,reboots30d:0,cabinet:'closed',emergencyStop:false,firmwareLatest:'2.7.0',firmwareStatus:'update_available',inputVoltage:230,gridPhase:'3-phase'},
 'CH-301':{protocol:'OCPP 2.0.1',ip:'10.43.1.301',network:'Airport fiber · 5G backup',signal:'Excellent',lastHeartbeat:'15:58:44',installDate:'2026-02-05',lastService:'2026-08-01',nextService:'2026-11-01',meterKwh:118930,errors24h:0,reboots30d:0,cabinet:'closed',emergencyStop:false,firmwareLatest:'5.2.0',firmwareStatus:'current',inputVoltage:412,gridPhase:'3-phase'},
 'CH-302':{protocol:'OCPP 2.0.1',ip:'10.43.1.302',network:'Airport fiber',signal:'Excellent',lastHeartbeat:'15:58:40',installDate:'2025-10-12',lastService:'2026-07-17',nextService:'2026-10-17',meterKwh:86220,errors24h:1,reboots30d:1,cabinet:'closed',emergencyStop:false,firmwareLatest:'6.4.2',firmwareStatus:'current',inputVoltage:407,gridPhase:'3-phase'},
 'CH-303':{protocol:'OCPP 1.6J',ip:'10.43.1.303',network:'Airport LAN',signal:'Excellent',lastHeartbeat:'15:58:41',installDate:'2025-10-12',lastService:'2026-07-17',nextService:'2026-10-17',meterKwh:19870,errors24h:0,reboots30d:0,cabinet:'closed',emergencyStop:false,firmwareLatest:'2.7.0',firmwareStatus:'current',inputVoltage:232,gridPhase:'3-phase'},
 'CH-401':{protocol:'OCPP 2.0.1',ip:'10.44.1.401',network:'Mall LAN · LTE backup',signal:'Good',lastHeartbeat:'15:58:29',installDate:'2025-08-28',lastService:'2026-07-25',nextService:'2026-10-25',meterKwh:77410,errors24h:1,reboots30d:1,cabinet:'closed',emergencyStop:false,firmwareLatest:'6.4.2',firmwareStatus:'current',inputVoltage:406,gridPhase:'3-phase'},
 'CH-402':{protocol:'OCPP 2.0.1',ip:'10.44.1.402',network:'Mall LAN · LTE backup',signal:'Fair',lastHeartbeat:'15:57:54',installDate:'2025-08-28',lastService:'2026-07-25',nextService:'2026-08-28',meterKwh:69640,errors24h:4,reboots30d:2,cabinet:'closed',emergencyStop:false,firmwareLatest:'5.2.0',firmwareStatus:'update_available',inputVoltage:403,gridPhase:'3-phase'},
 'CH-403':{protocol:'OCPP 1.6J',ip:'10.44.1.403',network:'Mall LAN',signal:'Good',lastHeartbeat:'15:58:19',installDate:'2025-08-28',lastService:'2026-07-25',nextService:'2026-10-25',meterKwh:17350,errors24h:0,reboots30d:0,cabinet:'closed',emergencyStop:false,firmwareLatest:'2.7.0',firmwareStatus:'current',inputVoltage:231,gridPhase:'3-phase'}
};
const connectorTechnicalSeed={
 'CON-101-1':{health:96,temp:43,sessionCycles:1284,lastSession:'CS-260814-091'},'CON-101-2':{health:98,temp:34,sessionCycles:941,lastSession:'CS-260814-083'},
 'CON-102-1':{health:99,temp:35,sessionCycles:814,lastSession:'CS-260814-088'},'CON-102-2':{health:99,temp:33,sessionCycles:702,lastSession:'CS-260814-079'},
 'CON-103-1':{health:96,temp:30,sessionCycles:1220,lastSession:'CS-260814-081'},
 'CON-201-1':{health:48,temp:68,sessionCycles:1660,lastSession:'CS-260814-087'},'CON-201-2':{health:61,temp:39,sessionCycles:1514,lastSession:'CS-260813-214'},
 'CON-202-1':{health:91,temp:49,sessionCycles:1022,lastSession:'CS-260814-092'},'CON-202-2':{health:93,temp:37,sessionCycles:864,lastSession:'CS-260814-077'},
 'CON-203-1':{health:74,temp:34,sessionCycles:1388,lastSession:'CS-260810-112'},
 'CON-301-1':{health:98,temp:42,sessionCycles:692,lastSession:'CS-260814-093'},'CON-301-2':{health:98,temp:36,sessionCycles:611,lastSession:'CS-260814-084'},
 'CON-302-1':{health:95,temp:38,sessionCycles:1102,lastSession:'CS-260814-076'},'CON-302-2':{health:96,temp:35,sessionCycles:894,lastSession:'CS-260814-071'},
 'CON-303-1':{health:99,temp:29,sessionCycles:728,lastSession:'CS-260814-069'},
 'CON-401-1':{health:94,temp:45,sessionCycles:1198,lastSession:'CS-260814-094'},'CON-401-2':{health:96,temp:36,sessionCycles:1003,lastSession:'CS-260814-073'},
 'CON-402-1':{health:73,temp:56,sessionCycles:978,lastSession:'CS-260814-066'},'CON-402-2':{health:86,temp:40,sessionCycles:835,lastSession:'CS-260814-061'},
 'CON-403-1':{health:97,temp:30,sessionCycles:911,lastSession:'CS-260814-059'}
};
seed.chargers=seed.chargers.map(c=>({...chargerTechnicalSeed[c.id],...c}));
seed.connectors=seed.connectors.map(c=>({...connectorTechnicalSeed[c.id],...c}));


const sessionTechnicalSeed={
 'CS-260814-091':{id:'REV-DAY-2026-08-14',date:'2026-08-14',ended:null,authMethod:'Plug & Charge',authorizationStatus:'accepted',authorizationRef:'AUTH-PNC-819104',accountType:'Personal',roaming:false,reservation:'RSV-5388',tariffName:'Central DC Flex',energyRate:138,minuteRate:0,connectionFee:250,idleRate:50,preauthAmount:12000,paymentProvider:'Visa • 4242 · Ameriabank',meterStartKwh:184168.4,meterLastKwh:184220.0,maxPowerKw:160,avgPowerKw:75.5,chargingLimitKw:160,errorCode:null,recoveryStatus:'none',chargingCurve:[{minute:0,power:0,soc:24},{minute:5,power:126,soc:30},{minute:10,power:160,soc:38},{minute:20,power:148,soc:50},{minute:30,power:126,soc:60},{minute:41,power:112,soc:68}],diagnostics:{voltageV:404,currentA:277,connectorTempC:43,cabinetTempC:42,networkLatencyMs:31,signal:'Excellent',isolationKOhm:690,cpState:'C'},events:[{time:'15:14',type:'authorization',title:'Vehicle certificate recognized',detail:'Plug & Charge contract certificate validated.'},{time:'15:15',type:'payment',title:'Preauthorization accepted',detail:'12,000 AMD authorized on Visa • 4242.'},{time:'15:16',type:'charging',title:'Energy delivery started',detail:'Connector locked · initial SOC 24%.'},{time:'15:36',type:'telemetry',title:'Peak charging power reached',detail:'160 kW at 46% SOC.'}]},
 'CS-260814-092':{id:'REV-DAY-2026-08-14',date:'2026-08-14',ended:null,authMethod:'Mobile app',authorizationStatus:'accepted',authorizationRef:'AUTH-APP-819122',accountType:'Corporate Fleet',roaming:false,reservation:null,tariffName:'West Hub DC',energyRate:145,minuteRate:0,connectionFee:100,idleRate:60,preauthAmount:10000,paymentProvider:'Corporate Wallet · Fleet 204',meterStartKwh:142572.2,meterLastKwh:142610.0,maxPowerKw:150,avgPowerKw:78.2,chargingLimitKw:150,errorCode:null,recoveryStatus:'none',chargingCurve:[{minute:0,power:0,soc:18},{minute:4,power:112,soc:23},{minute:10,power:148,soc:31},{minute:18,power:132,soc:41},{minute:24,power:106,soc:47},{minute:29,power:91,soc:51}],diagnostics:{voltageV:398,currentA:229,connectorTempC:49,cabinetTempC:48,networkLatencyMs:46,signal:'Good',isolationKOhm:640,cpState:'C'},events:[{time:'15:27',type:'authorization',title:'App authorization accepted',detail:'Fleet account permission validated.'},{time:'15:28',type:'charging',title:'Charging session started',detail:'Connector 1 locked and energy delivery enabled.'},{time:'15:49',type:'telemetry',title:'Power taper started',detail:'Battery requested reduced current above 45% SOC.'}]},
 'CS-260814-093':{id:'REV-DAY-2026-08-14',date:'2026-08-14',ended:null,authMethod:'RFID',authorizationStatus:'accepted',authorizationRef:'RFID-AM-33191',accountType:'Personal',roaming:true,roamingPartner:'ChargeWay AM',reservation:null,tariffName:'Airport Roaming DC',energyRate:152,minuteRate:0,connectionFee:300,idleRate:70,preauthAmount:15000,paymentProvider:'Roaming settlement · ChargeWay',meterStartKwh:118897.8,meterLastKwh:118930.0,maxPowerKw:200,avgPowerKw:84,chargingLimitKw:180,errorCode:null,recoveryStatus:'none',chargingCurve:[{minute:0,power:0,soc:31},{minute:3,power:132,soc:35},{minute:8,power:176,soc:42},{minute:14,power:165,soc:49},{minute:19,power:151,soc:54},{minute:23,power:138,soc:57}],diagnostics:{voltageV:412,currentA:335,connectorTempC:42,cabinetTempC:41,networkLatencyMs:18,signal:'Excellent',isolationKOhm:720,cpState:'C'},events:[{time:'15:33',type:'authorization',title:'Roaming RFID authorized',detail:'ChargeWay AM contract accepted.'},{time:'15:34',type:'charging',title:'Energy delivery started',detail:'Roaming session record opened.'},{time:'15:53',type:'telemetry',title:'Stable charging',detail:'No charger-side limitations detected.'}]},
 'CS-260814-094':{id:'REV-DAY-2026-08-14',date:'2026-08-14',ended:null,authMethod:'QR code',authorizationStatus:'accepted',authorizationRef:'QR-SESSION-094',accountType:'Personal',roaming:false,reservation:'RSV-5396',tariffName:'Mall DC Evening',energyRate:148,minuteRate:0,connectionFee:150,idleRate:65,preauthAmount:8000,paymentProvider:'Mastercard • 8810 · ACBA',meterStartKwh:77389.4,meterLastKwh:77410.0,maxPowerKw:120,avgPowerKw:77.3,chargingLimitKw:120,errorCode:null,recoveryStatus:'none',chargingCurve:[{minute:0,power:0,soc:42},{minute:3,power:96,soc:46},{minute:7,power:118,soc:51},{minute:11,power:104,soc:56},{minute:16,power:84,soc:61}],diagnostics:{voltageV:401,currentA:209,connectorTempC:45,cabinetTempC:44,networkLatencyMs:39,signal:'Good',isolationKOhm:610,cpState:'C'},events:[{time:'15:40',type:'authorization',title:'QR authorization accepted',detail:'Reservation RSV-5396 validated.'},{time:'15:41',type:'charging',title:'Charging session started',detail:'Connector locked successfully.'}]},
 'CS-260814-088':{id:'REV-DAY-2026-08-14',date:'2026-08-14',ended:'15:11',authMethod:'Mobile app',authorizationStatus:'accepted',authorizationRef:'AUTH-APP-818902',accountType:'Personal',roaming:false,reservation:null,tariffName:'Central DC Flex',energyRate:135,minuteRate:0,connectionFee:250,idleRate:50,preauthAmount:12000,paymentProvider:'Visa • 0921 · IDBank',meterStartKwh:99221.6,meterLastKwh:99280.0,maxPowerKw:185,avgPowerKw:71.5,chargingLimitKw:200,errorCode:null,recoveryStatus:'none',stopReason:'Target battery reached',chargingCurve:[{minute:0,power:0,soc:21},{minute:6,power:142,soc:29},{minute:15,power:185,soc:43},{minute:28,power:154,soc:60},{minute:40,power:96,soc:74},{minute:49,power:28,soc:82}],diagnostics:{voltageV:407,currentA:0,connectorTempC:35,cabinetTempC:35,networkLatencyMs:27,signal:'Excellent',isolationKOhm:705,cpState:'B'},events:[{time:'14:21',type:'authorization',title:'App authorization accepted',detail:'Payment method validated.'},{time:'14:22',type:'charging',title:'Charging started',detail:'Initial SOC 21%.'},{time:'15:10',type:'charging',title:'Target reached',detail:'Vehicle exceeded configured 80% target.'},{time:'15:11',type:'payment',title:'Payment captured',detail:'8,120 AMD captured successfully.'}]},
 'CS-260814-087':{id:'REV-DAY-2026-08-14',date:'2026-08-14',ended:'14:20',authMethod:'Bank card',authorizationStatus:'accepted',authorizationRef:'EMV-882901',accountType:'Guest',roaming:false,reservation:null,tariffName:'West Hub Guest DC',energyRate:150,minuteRate:0,connectionFee:300,idleRate:60,preauthAmount:10000,paymentProvider:'Visa • 7102 · terminal',meterStartKwh:223865.8,meterLastKwh:223870.0,maxPowerKw:118,avgPowerKw:21,chargingLimitKw:180,errorCode:'EVSE-CC-07',recoveryStatus:'required',chargingCurve:[{minute:0,power:0,soc:35},{minute:2,power:62,soc:36},{minute:5,power:91,soc:38},{minute:9,power:44,soc:39},{minute:12,power:0,soc:39}],diagnostics:{voltageV:405,currentA:0,connectorTempC:68,cabinetTempC:71,networkLatencyMs:184,signal:'Fair',isolationKOhm:580,cpState:'B'},events:[{time:'14:07',type:'authorization',title:'Card preauthorization accepted',detail:'10,000 AMD reserved.'},{time:'14:08',type:'charging',title:'Energy delivery started',detail:'Connector 1 locked.'},{time:'14:17',type:'fault',title:'Connector communication degraded',detail:'Repeated EVSE control-channel retries detected.'},{time:'14:20',type:'fault',title:'Session failed',detail:'EVSE-CC-07 · Connector communication fault.'},{time:'14:21',type:'payment',title:'Preauthorization cancelled',detail:'No final customer charge captured.'}]},
 'CS-260814-086':{id:'REV-DAY-2026-08-14',date:'2026-08-14',ended:'14:07',authMethod:'Mobile app',authorizationStatus:'accepted',authorizationRef:'AUTH-APP-818776',accountType:'Personal',roaming:false,reservation:null,tariffName:'Mall DC Day',energyRate:148,minuteRate:0,connectionFee:150,idleRate:65,preauthAmount:8000,paymentProvider:'Visa • 5520 · Ardshinbank',meterStartKwh:69624.3,meterLastKwh:69640.0,maxPowerKw:112,avgPowerKw:44.9,chargingLimitKw:150,errorCode:'TEMP-14',recoveryStatus:'monitoring',chargingCurve:[{minute:0,power:0,soc:28},{minute:4,power:94,soc:32},{minute:10,power:112,soc:38},{minute:16,power:76,soc:43},{minute:20,power:31,soc:45},{minute:21,power:0,soc:45}],diagnostics:{voltageV:403,currentA:0,connectorTempC:56,cabinetTempC:55,networkLatencyMs:63,signal:'Fair',isolationKOhm:625,cpState:'B'},events:[{time:'13:45',type:'authorization',title:'App authorization accepted',detail:'Payment preauthorization accepted.'},{time:'13:46',type:'charging',title:'Charging started',detail:'Connector 1 locked.'},{time:'14:02',type:'warning',title:'Connector thermal warning',detail:'Temperature reached 54 °C.'},{time:'14:07',type:'fault',title:'Thermal protection interrupted session',detail:'TEMP-14 protection threshold reached.'},{time:'14:08',type:'payment',title:'Payment pending capture',detail:'Final meter value requires operator reconciliation.'}]},
 'CS-260814-085':{id:'REV-DAY-2026-08-14',date:'2026-08-14',ended:'13:56',authMethod:'Plug & Charge',authorizationStatus:'accepted',authorizationRef:'AUTH-PNC-818601',accountType:'Corporate Fleet',roaming:false,reservation:null,tariffName:'Airport Fleet DC',energyRate:135,minuteRate:0,connectionFee:0,idleRate:50,preauthAmount:0,paymentProvider:'Corporate settlement · ACME Mobility',meterStartKwh:86156.9,meterLastKwh:86220.0,maxPowerKw:120,avgPowerKw:70.1,chargingLimitKw:120,errorCode:null,recoveryStatus:'none',stopReason:'Target battery reached',chargingCurve:[{minute:0,power:0,soc:17},{minute:8,power:118,soc:28},{minute:18,power:120,soc:43},{minute:30,power:111,soc:59},{minute:43,power:78,soc:72},{minute:54,power:26,soc:81}],diagnostics:{voltageV:407,currentA:0,connectorTempC:38,cabinetTempC:39,networkLatencyMs:24,signal:'Excellent',isolationKOhm:730,cpState:'B'},events:[{time:'13:01',type:'authorization',title:'Fleet Plug & Charge accepted',detail:'Corporate charging contract validated.'},{time:'13:02',type:'charging',title:'Charging started',detail:'Initial SOC 17%.'},{time:'13:55',type:'charging',title:'Target reached',detail:'Vehicle reached 80% target.'},{time:'13:56',type:'payment',title:'Corporate settlement queued',detail:'8,760 AMD posted to fleet account.'}]}
};
seed.sessions=seed.sessions.map(s=>({...sessionTechnicalSeed[s.id],...s}));



const reservationTechnicalSeed={
 'RSV-5401':{date:'2026-08-17',created:'08:42',arrival:'10:20',durationMin:60,status:'confirmed',assignmentMode:'specific',bay:'C-07',charger:'CH-103',connector:'CON-103-1',targetSoc:80,requestedKwh:34,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:5150,paymentStatus:'paid',arrivalState:'not_arrived',accessCode:'482913',source:'Mobile app',notes:'Customer requested accessible route from south entrance.',timeline:[{time:'08:42',type:'created',title:'Reservation created',detail:'Specific charger reservation confirmed.'},{time:'08:43',type:'payment',title:'Reservation fee paid',detail:'500 AMD captured.'}]},
 'RSV-5402':{id:'REV-DAY-2026-08-17',date:'2026-08-17',created:'09:05',arrival:'10:35',durationMin:45,status:'confirmed',assignmentMode:'auto',bay:null,charger:null,connector:null,targetSoc:85,requestedKwh:29,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:4620,paymentStatus:'paid',arrivalState:'not_arrived',accessCode:'731504',source:'Mobile app',notes:'Auto-assign best compatible DC charger on arrival.',timeline:[{time:'09:05',type:'created',title:'Location reservation created',detail:'Charger will be assigned automatically.'}]},
 'RSV-5403':{id:'REV-DAY-2026-08-17',date:'2026-08-17',created:'09:18',arrival:'10:40',durationMin:50,status:'waiting',assignmentMode:'waiting',bay:'W-03',charger:null,connector:null,targetSoc:80,requestedKwh:31,graceMin:8,cancellationCutoffMin:20,fee:0,estimatedCost:4890,paymentStatus:'not_required',arrivalState:'waiting',accessCode:null,source:'Mobile app',waitingPosition:1,notes:'Customer joined waiting list because all compatible DC chargers were allocated.',timeline:[{time:'09:18',type:'waiting',title:'Added to waiting list',detail:'Position 1 at West Hub.'}]},
 'RSV-5404':{id:'REV-DAY-2026-08-17',date:'2026-08-17',created:'09:26',arrival:'11:00',durationMin:40,status:'confirmed',assignmentMode:'auto',bay:null,charger:null,connector:null,targetSoc:80,requestedKwh:24,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:3780,paymentStatus:'paid',arrivalState:'not_arrived',accessCode:'905118',source:'Mobile app',notes:'Mall parking access required.',timeline:[{time:'09:26',type:'created',title:'Reservation confirmed',detail:'Location reservation accepted.'}]},
 'RSV-5405':{driver:'Artur B.',vehicle:'Mercedes EQB · 67JJ220',site:'SITE-01',date:'2026-08-17',created:'07:31',arrival:'09:45',durationMin:50,status:'active',assignmentMode:'specific',bay:'C-04',charger:'CH-102',connector:'CON-102-2',targetSoc:90,requestedKwh:42,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:6420,paymentStatus:'paid',arrivalState:'arrived',checkedIn:'09:41',accessCode:'615902',source:'Operator',notes:'Operator assigned secondary connector after primary became occupied.',timeline:[{time:'07:31',type:'created',title:'Reservation created',detail:'Reservation created by customer.'},{time:'09:41',type:'arrival',title:'Customer checked in',detail:'Arrival confirmed by geofence.'},{time:'09:43',type:'assignment',title:'Connector assigned',detail:'CH-102 · Connector 2.'}]},
 'RSV-5406':{driver:'Karine D.',vehicle:'Nissan Ariya · 91KK107',site:'SITE-02',date:'2026-08-17',created:'08:16',arrival:'10:30',durationMin:60,status:'confirmed',assignmentMode:'specific',bay:'W-04',charger:'CH-202',connector:'CON-202-2',targetSoc:80,requestedKwh:36,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:5480,paymentStatus:'paid',arrivalState:'not_arrived',accessCode:'247305',source:'Mobile app',notes:'Potential charger overlap with operator hold.',operatorOverride:false,timeline:[{time:'08:16',type:'created',title:'Reservation confirmed',detail:'Specific charger and bay reserved.'}]},
 'RSV-5407':{driver:'Vahan S.',vehicle:'Polestar 2 · 77LL506',site:'SITE-02',date:'2026-08-17',created:'08:22',arrival:'10:50',durationMin:50,status:'confirmed',assignmentMode:'specific',bay:'W-04',charger:'CH-202',connector:'CON-202-2',targetSoc:80,requestedKwh:30,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:4660,paymentStatus:'paid',arrivalState:'not_arrived',accessCode:'330149',source:'Partner roaming',notes:'Roaming reservation imported from partner network.',operatorOverride:false,timeline:[{time:'08:22',type:'created',title:'Roaming reservation imported',detail:'Partner reservation accepted.'}]},
 'RSV-5399':{driver:'Mane G.',vehicle:'Renault Megane E-Tech · 14MM620',site:'SITE-03',date:'2026-08-17',created:'06:54',arrival:'08:00',durationMin:45,status:'no_show',assignmentMode:'specific',bay:'A-05',charger:'CH-302',connector:'CON-302-2',targetSoc:80,requestedKwh:28,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:4210,paymentStatus:'paid',arrivalState:'no_show',accessCode:'118403',source:'Mobile app',notes:'Grace period expired without arrival.',timeline:[{time:'06:54',type:'created',title:'Reservation confirmed',detail:'Specific charger reserved.'},{time:'08:10',type:'no_show',title:'Marked no-show',detail:'10 minute grace period expired.'}]},
 'RSV-5398':{driver:'Ani P.',vehicle:'Cupra Born · 23NN814',site:'SITE-04',date:'2026-08-17',created:'06:20',arrival:'07:30',durationMin:40,status:'completed',assignmentMode:'specific',bay:'M-03',charger:'CH-403',connector:'CON-403-1',targetSoc:80,requestedKwh:21,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:3310,paymentStatus:'paid',arrivalState:'completed',checkedIn:'07:26',accessCode:'770612',source:'Mobile app',notes:'Reservation completed successfully.',timeline:[{time:'06:20',type:'created',title:'Reservation confirmed',detail:'AC charging bay reserved.'},{time:'07:26',type:'arrival',title:'Customer arrived',detail:'Access code validated.'},{time:'08:08',type:'completed',title:'Reservation completed',detail:'Charging session finished and bay released.'}]},
 'RSV-5397':{driver:'Levon T.',vehicle:'Ford Mustang Mach-E · 35PP519',site:'SITE-01',date:'2026-08-17',created:'06:12',arrival:'09:10',durationMin:60,status:'cancelled',assignmentMode:'auto',bay:null,charger:null,connector:null,targetSoc:90,requestedKwh:48,graceMin:10,cancellationCutoffMin:30,fee:500,estimatedCost:7160,paymentStatus:'refunded',arrivalState:'cancelled',accessCode:null,source:'Mobile app',notes:'Cancelled by customer before cutoff.',timeline:[{time:'06:12',type:'created',title:'Reservation confirmed',detail:'Location reservation accepted.'},{time:'08:02',type:'cancelled',title:'Reservation cancelled',detail:'Customer cancelled before cancellation cutoff.'},{time:'08:03',type:'payment',title:'Reservation fee refunded',detail:'500 AMD refund issued.'}]}
};
const extraReservations=Object.entries(reservationTechnicalSeed).filter(([id])=>!seed.reservations.some(r=>r.id===id)).map(([id,data])=>({id,...data}));
seed.reservations=seed.reservations.map(r=>({...r,...reservationTechnicalSeed[r.id]})).concat(extraReservations);

function normalizeReservation(reservation={}){
 const out={...reservation};
 out.durationMin=finiteNumber(reservation.durationMin,45);
 out.fee=finiteNumber(reservation.fee,0);
 out.estimatedCost=finiteNumber(reservation.estimatedCost,0);
 out.targetSoc=finiteNumber(reservation.targetSoc,80);
 out.requestedKwh=finiteNumber(reservation.requestedKwh,0);
 out.graceMin=finiteNumber(reservation.graceMin,10);
 out.cancellationCutoffMin=finiteNumber(reservation.cancellationCutoffMin,30);
 out.timeline=Array.isArray(reservation.timeline)?reservation.timeline:[];
 out.operatorOverride=Boolean(reservation.operatorOverride);
 return out;
}


const energyProfileSeed=[
 {id:'SITE-01',site:'SITE-01',mode:'balanced',defaultEvLimitKw:560,warningPercent:82,criticalPercent:94,contractedGridKw:520,transformerPf:.97,gridVoltageV:404,gridFrequencyHz:50.01,transformerTempC:51,solarInstalledKw:92,batteryCapacityKwh:180,batterySoc:64,batteryMode:'auto',batteryMaxKw:60,peakTodayKw:486,peakTime:'08:42',demandRate:780,forecastPeakKw:512,forecastTime:'18:20',reserveHeadroomKw:35,chargerLimits:{'CH-101':180,'CH-102':220,'CH-103':22},chargerPriorities:{'CH-101':'standard','CH-102':'standard','CH-103':'low'},history:[{time:'06:00',buildingKw:84,evKw:96,solarKw:5,batteryKw:0},{time:'08:00',buildingKw:132,evKw:318,solarKw:22,batteryKw:24},{time:'10:00',buildingKw:126,evKw:286,solarKw:54,batteryKw:0},{time:'12:00',buildingKw:121,evKw:304,solarKw:72,batteryKw:0},{time:'14:00',buildingKw:119,evKw:330,solarKw:63,batteryKw:18},{time:'16:00',buildingKw:118,evKw:342,solarKw:48,batteryKw:30}]},
 {id:'SITE-02',site:'SITE-02',mode:'peak_protection',defaultEvLimitKw:380,warningPercent:78,criticalPercent:90,contractedGridKw:300,transformerPf:.94,gridVoltageV:397,gridFrequencyHz:49.98,transformerTempC:67,solarInstalledKw:48,batteryCapacityKwh:0,batterySoc:0,batteryMode:'unavailable',batteryMaxKw:0,peakTodayKw:337,peakTime:'15:24',demandRate:860,forecastPeakKw:356,forecastTime:'17:45',reserveHeadroomKw:45,chargerLimits:{'CH-201':80,'CH-202':120,'CH-203':18},chargerPriorities:{'CH-201':'restricted','CH-202':'high','CH-203':'low'},history:[{time:'06:00',buildingKw:61,evKw:72,solarKw:2,batteryKw:0},{time:'08:00',buildingKw:79,evKw:146,solarKw:9,batteryKw:0},{time:'10:00',buildingKw:91,evKw:201,solarKw:24,batteryKw:0},{time:'12:00',buildingKw:88,evKw:220,solarKw:31,batteryKw:0},{time:'14:00',buildingKw:84,evKw:238,solarKw:27,batteryKw:0},{time:'16:00',buildingKw:86,evKw:246,solarKw:24,batteryKw:0}]},
 {id:'SITE-03',site:'SITE-03',mode:'balanced',defaultEvLimitKw:450,warningPercent:84,criticalPercent:95,contractedGridKw:430,transformerPf:.98,gridVoltageV:411,gridFrequencyHz:50.02,transformerTempC:48,solarInstalledKw:0,batteryCapacityKwh:220,batterySoc:38,batteryMode:'auto',batteryMaxKw:80,peakTodayKw:312,peakTime:'09:18',demandRate:810,forecastPeakKw:346,forecastTime:'19:10',reserveHeadroomKw:40,chargerLimits:{'CH-301':200,'CH-302':120,'CH-303':22},chargerPriorities:{'CH-301':'high','CH-302':'standard','CH-303':'low'},history:[{time:'06:00',buildingKw:76,evKw:54,solarKw:0,batteryKw:0},{time:'08:00',buildingKw:94,evKw:168,solarKw:0,batteryKw:0},{time:'10:00',buildingKw:111,evKw:201,solarKw:0,batteryKw:28},{time:'12:00',buildingKw:108,evKw:186,solarKw:0,batteryKw:0},{time:'14:00',buildingKw:106,evKw:215,solarKw:0,batteryKw:32},{time:'16:00',buildingKw:104,evKw:198,solarKw:0,batteryKw:40}]},
 {id:'SITE-04',site:'SITE-04',mode:'balanced',defaultEvLimitKw:260,warningPercent:80,criticalPercent:92,contractedGridKw:250,transformerPf:.95,gridVoltageV:399,gridFrequencyHz:49.99,transformerTempC:61,solarInstalledKw:36,batteryCapacityKwh:0,batterySoc:0,batteryMode:'unavailable',batteryMaxKw:0,peakTodayKw:261,peakTime:'15:36',demandRate:920,forecastPeakKw:278,forecastTime:'18:05',reserveHeadroomKw:25,chargerLimits:{'CH-401':100,'CH-402':90,'CH-403':18},chargerPriorities:{'CH-401':'high','CH-402':'restricted','CH-403':'low'},history:[{time:'06:00',buildingKw:28,evKw:18,solarKw:0,batteryKw:0},{time:'08:00',buildingKw:47,evKw:61,solarKw:3,batteryKw:0},{time:'10:00',buildingKw:69,evKw:118,solarKw:13,batteryKw:0},{time:'12:00',buildingKw:78,evKw:146,solarKw:24,batteryKw:0},{time:'14:00',buildingKw:76,evKw:158,solarKw:22,batteryKw:0},{time:'16:00',buildingKw:74,evKw:171,solarKw:18,batteryKw:0}]}
];
const energyAlertSeed=[
 {id:'EN-301',site:'SITE-01',severity:'normal',status:'monitoring',type:'peak',title:'Evening demand peak forecast',detail:'Forecast EV + building demand approaches the configured site warning threshold at 18:20.',created:'15:44',recommended:'Keep battery in Auto and maintain at least 35 kW operational headroom.',timeline:[{time:'15:44',type:'warning',title:'Forecast threshold detected',detail:'Predicted gross demand 512 kW.'}]},
 {id:'EN-302',site:'SITE-02',severity:'critical',status:'open',type:'grid',title:'Contracted grid demand exceeded',detail:'Estimated grid import is above the 300 kW contracted demand threshold while local battery support is unavailable.',created:'15:51',recommended:'Apply peak protection or temporarily derate non-priority chargers.',timeline:[{time:'15:51',type:'critical',title:'Contract demand threshold exceeded',detail:'Estimated grid import crossed the configured contract limit.'}]},
 {id:'EN-303',site:'SITE-04',severity:'high',status:'open',type:'capacity',title:'Low site headroom during mall peak',detail:'Physical load is above 80% and demand is forecast to increase before the evening peak.',created:'15:55',recommended:'Reduce EV site limit by 10–15% and prioritize active reservations.',timeline:[{time:'15:55',type:'warning',title:'Headroom warning',detail:'Site capacity reserve fell below preferred operating margin.'}]},
 {id:'EN-304',site:'SITE-03',severity:'normal',status:'monitoring',type:'battery',title:'Battery reserve below evening target',detail:'Battery state of charge is below the configured 45% pre-peak reserve target.',created:'15:20',recommended:'Charge battery during the next low-demand window or preserve discharge until evening peak.',timeline:[{time:'15:20',type:'warning',title:'Battery reserve warning',detail:'Battery SOC 38%.'}]}
];
seed.energyProfiles=energyProfileSeed;
seed.energyAlerts=energyAlertSeed;


const tariffSeed=[
 {id:'TAR-01',name:'Central DC Flex',site:'SITE-01',category:'DC',energyRate:138,connectionFee:250,idleRate:50,parkingRate:100,status:'active'},
 {id:'TAR-02',name:'West Hub DC',site:'SITE-02',category:'DC',energyRate:145,connectionFee:100,idleRate:60,parkingRate:80,status:'active'},
 {id:'TAR-03',name:'Airport Roaming DC',site:'SITE-03',category:'Roaming DC',energyRate:152,connectionFee:300,idleRate:70,parkingRate:120,status:'active'},
 {id:'TAR-04',name:'Mall DC Evening',site:'SITE-04',category:'DC',energyRate:148,connectionFee:150,idleRate:65,parkingRate:100,status:'active'},
 {id:'TAR-05',name:'AC Standard',site:null,category:'AC',energyRate:112,connectionFee:0,idleRate:35,parkingRate:80,status:'active'}
];
const revenueDailySeed=[
 {id:'REV-DAY-2026-08-11',date:'2026-08-11',energy:218600,reservations:11000,idle:6840,parking:5120,other:2100,total:243660},
 {id:'REV-DAY-2026-08-12',date:'2026-08-12',energy:229480,reservations:12500,idle:7520,parking:5480,other:2840,total:257820},
 {id:'REV-DAY-2026-08-13',date:'2026-08-13',energy:236120,reservations:13000,idle:8240,parking:6120,other:1980,total:265460},
 {id:'REV-DAY-2026-08-14',date:'2026-08-14',energy:251900,reservations:15000,idle:10140,parking:6980,other:3210,total:287230},
 {id:'REV-DAY-2026-08-15',date:'2026-08-15',energy:267420,reservations:16500,idle:11200,parking:7240,other:3960,total:306320},
 {id:'REV-DAY-2026-08-16',date:'2026-08-16',energy:258360,reservations:15500,idle:9880,parking:7160,other:3020,total:293920},
 {id:'REV-DAY-2026-08-17',date:'2026-08-17',energy:243180,reservations:14500,idle:9170,parking:6840,other:2730,total:276420}
];
const revenueBySiteSeed=[
 {id:'REV-SITE-01',site:'SITE-01',energy:89420,reservations:5000,idle:2880,parking:1640,other:820,transactions:22,failed:0},
 {id:'REV-SITE-02',site:'SITE-02',energy:48160,reservations:3000,idle:2690,parking:1480,other:520,transactions:15,failed:2},
 {id:'REV-SITE-03',site:'SITE-03',energy:67480,reservations:3500,idle:1640,parking:2020,other:960,transactions:17,failed:0},
 {id:'REV-SITE-04',site:'SITE-04',energy:38120,reservations:3000,idle:1960,parking:1700,other:430,transactions:14,failed:0}
];
const financialTransactionSeed=[
 {id:'TX-817-1048',date:'2026-08-17',time:'09:31',type:'charging',site:'SITE-01',charger:'CH-102',session:'CS-260814-088',reservation:null,customer:'Sona P.',accountType:'Personal',gross:8120,providerFee:162,tax:1353,net:6605,paymentMethod:'Visa • 0921',provider:'Ameriabank',status:'captured',roaming:false,reference:'PAY-AM-771204',timeline:[{time:'09:31',title:'Payment captured',detail:'Final charging amount captured successfully.'}]},
 {id:'TX-817-1047',date:'2026-08-17',time:'09:18',type:'charging',site:'SITE-03',charger:'CH-302',session:'CS-260814-085',reservation:null,customer:'ACME Mobility',accountType:'Corporate Fleet',gross:8760,providerFee:0,tax:1460,net:7300,paymentMethod:'Corporate settlement',provider:'Fleet Billing',status:'captured',roaming:false,reference:'FLT-ACME-88210',timeline:[{time:'09:18',title:'Fleet charge posted',detail:'Session posted to corporate fleet account.'}]},
 {id:'TX-817-1046',date:'2026-08-17',time:'09:03',type:'charging',site:'SITE-04',charger:'CH-402',session:'CS-260814-086',reservation:null,customer:'Tatev M.',accountType:'Personal',gross:2480,providerFee:50,tax:413,net:2017,paymentMethod:'Visa • 5520',provider:'Ardshinbank',status:'pending',roaming:false,reference:'PAY-AS-661901',failureReason:'Meter reconciliation required after thermal interruption.',timeline:[{time:'09:03',title:'Settlement pending',detail:'Final meter value requires reconciliation.'}]},
 {id:'TX-817-1045',date:'2026-08-17',time:'08:56',type:'charging',site:'SITE-02',charger:'CH-201',session:'CS-260814-087',reservation:null,customer:'Gor T.',accountType:'Guest',gross:0,providerFee:0,tax:0,net:0,paymentMethod:'Visa • 7102',provider:'Terminal acquiring',status:'failed',roaming:false,reference:'EMV-882901',failureReason:'Preauthorization reversed after EVSE fault. Retryable only if customer authorizes a new charge.',retryable:false,timeline:[{time:'08:56',title:'Payment cancelled',detail:'No customer charge captured after failed session.'}]},
 {id:'TX-817-1044',date:'2026-08-17',time:'08:42',type:'charging',site:'SITE-03',charger:'CH-301',session:'CS-260814-093',reservation:null,customer:'Lilit S.',accountType:'Personal',gross:4910,providerFee:98,tax:818,net:3994,paymentMethod:'Roaming RFID',provider:'ChargeWay AM',status:'pending',roaming:true,roamingPartner:'ChargeWay AM',reference:'CPO-CHW-99021',failureReason:'Partner CDR awaiting settlement batch.',timeline:[{time:'08:42',title:'Roaming CDR accepted',detail:'Partner settlement is pending.'}]},
 {id:'TX-817-1043',date:'2026-08-17',time:'08:28',type:'reservation',site:'SITE-01',charger:'CH-103',session:null,reservation:'RSV-5401',customer:'Anna M.',accountType:'Personal',gross:500,providerFee:10,tax:83,net:407,paymentMethod:'Wallet',provider:'VoltDrive Wallet',status:'captured',roaming:false,reference:'RSV-PAY-5401',timeline:[{time:'08:28',title:'Reservation fee captured',detail:'Reservation RSV-5401 confirmed.'}]},
 {id:'TX-817-1042',date:'2026-08-17',time:'08:11',type:'reservation',site:'SITE-03',charger:null,session:null,reservation:'RSV-5402',customer:'David K.',accountType:'Personal',gross:500,providerFee:10,tax:83,net:407,paymentMethod:'Mastercard • 1130',provider:'ACBA',status:'captured',roaming:false,reference:'RSV-PAY-5402',timeline:[{time:'08:11',title:'Reservation fee captured',detail:'Reservation RSV-5402 confirmed.'}]},
 {id:'TX-817-1041',date:'2026-08-17',time:'07:58',type:'idle',site:'SITE-01',charger:'CH-102',session:'CS-260814-088',reservation:null,customer:'Sona P.',accountType:'Personal',gross:350,providerFee:7,tax:58,net:285,paymentMethod:'Visa • 0921',provider:'Ameriabank',status:'captured',roaming:false,reference:'IDLE-771204',timeline:[{time:'07:58',title:'Idle fee captured',detail:'7 idle minutes billed after charging completion.'}]},
 {id:'TX-817-1040',date:'2026-08-17',time:'07:40',type:'parking',site:'SITE-04',charger:'CH-403',session:null,reservation:'RSV-5398',customer:'Ani P.',accountType:'Personal',gross:400,providerFee:8,tax:67,net:325,paymentMethod:'Wallet',provider:'VoltDrive Wallet',status:'captured',roaming:false,reference:'PARK-5398',timeline:[{time:'07:40',title:'Parking fee captured',detail:'Mall parking integration posted final parking charge.'}]},
 {id:'TX-817-1039',date:'2026-08-17',time:'07:22',type:'reservation',site:'SITE-01',charger:null,session:null,reservation:'RSV-5397',customer:'Levon T.',accountType:'Personal',gross:500,providerFee:10,tax:83,net:407,paymentMethod:'Visa • 7781',provider:'IDBank',status:'refunded',refundedAmount:500,roaming:false,reference:'RSV-PAY-5397',timeline:[{time:'07:22',title:'Reservation fee captured',detail:'Reservation accepted.'},{time:'08:03',title:'Refund completed',detail:'500 AMD refunded after cancellation before cutoff.'}]},
 {id:'TX-817-1038',date:'2026-08-17',time:'07:09',type:'adjustment',site:'SITE-02',charger:'CH-201',session:'CS-260814-087',reservation:null,customer:'Gor T.',accountType:'Guest',gross:1200,providerFee:24,tax:200,net:976,paymentMethod:'Visa • 7102',provider:'Terminal acquiring',status:'failed',roaming:false,reference:'ADJ-201-087',failureReason:'Issuer soft decline. Retry permitted.',retryable:true,timeline:[{time:'07:09',title:'Adjustment capture failed',detail:'Issuer returned soft decline.'}]},
 {id:'TX-817-1037',date:'2026-08-17',time:'06:48',type:'charging',site:'SITE-04',charger:'CH-401',session:'CS-260814-094',reservation:'RSV-5396',customer:'Narek G.',accountType:'Personal',gross:3180,providerFee:64,tax:530,net:2586,paymentMethod:'Mastercard • 8810',provider:'ACBA',status:'preauthorized',roaming:false,reference:'PAY-ACBA-44081',timeline:[{time:'06:48',title:'Preauthorization active',detail:'Session is still active; final capture not yet created.'}]}
];
const refundSeed=[
 {id:'RF-817-001',transaction:'TX-817-1039',date:'2026-08-17',time:'08:03',amount:500,reason:'Reservation cancellation',status:'completed',customer:'Levon T.',operator:'System',note:'Cancelled before cutoff.'},
 {id:'RF-817-002',transaction:'TX-817-1046',date:'2026-08-17',time:'09:12',amount:740,reason:'Charging interruption',status:'review',customer:'Tatev M.',operator:'Arman Hakobyan',note:'Customer requested partial adjustment after thermal interruption.'}
];
const roamingSettlementSeed=[
 {id:'SET-CHW-0817',partner:'ChargeWay AM',period:'2026-08-11 → 2026-08-17',sessions:18,gross:84620,operatorReceivable:70240,partnerFee:14380,status:'pending',due:'2026-08-20',lastSync:'09:20',variance:0},
 {id:'SET-EVR-0817',partner:'EV Roam Georgia',period:'2026-08-11 → 2026-08-17',sessions:7,gross:31280,operatorReceivable:25870,partnerFee:5410,status:'reconciled',due:'2026-08-21',lastSync:'08:54',variance:120},
 {id:'SET-GRN-0817',partner:'GreenCharge Caucasus',period:'2026-08-11 → 2026-08-17',sessions:5,gross:22840,operatorReceivable:19110,partnerFee:3730,status:'attention',due:'2026-08-19',lastSync:'08:31',variance:860}
];
seed.tariffs=tariffSeed;
seed.revenueDaily=revenueDailySeed;
seed.revenueBySite=revenueBySiteSeed;
seed.financialTransactions=financialTransactionSeed;
seed.refunds=refundSeed;
seed.roamingSettlements=roamingSettlementSeed;

function normalizeTransaction(tx={}){const out={...tx};out.gross=finiteNumber(tx.gross,0);out.providerFee=finiteNumber(tx.providerFee,0);out.tax=finiteNumber(tx.tax,0);out.net=finiteNumber(tx.net,out.gross-out.providerFee-out.tax);out.refundedAmount=finiteNumber(tx.refundedAmount,0);out.timeline=Array.isArray(tx.timeline)?tx.timeline:[];out.status=tx.status||'pending';out.type=tx.type||'charging';out.retryable=Boolean(tx.retryable);return out;}
function normalizeRefund(refund={}){const out={...refund};out.amount=finiteNumber(refund.amount,0);out.status=refund.status||'review';return out;}
function normalizeRoamingSettlement(item={}){const out={...item};out.sessions=finiteNumber(item.sessions,0);out.gross=finiteNumber(item.gross,0);out.operatorReceivable=finiteNumber(item.operatorReceivable,0);out.partnerFee=finiteNumber(item.partnerFee,0);out.variance=finiteNumber(item.variance,0);out.status=item.status||'pending';return out;}
function normalizeRevenueDay(item={}){const out={...item};['energy','reservations','idle','parking','other','total'].forEach(k=>out[k]=finiteNumber(item[k],0));return out;}
function normalizeRevenueSite(item={}){const out={...item};['energy','reservations','idle','parking','other','transactions','failed'].forEach(k=>out[k]=finiteNumber(item[k],0));return out;}

function normalizeEnergyProfile(profile={}){
 const out={...profile};
 out.defaultEvLimitKw=finiteNumber(profile.defaultEvLimitKw,0);out.warningPercent=finiteNumber(profile.warningPercent,82);out.criticalPercent=finiteNumber(profile.criticalPercent,94);out.contractedGridKw=finiteNumber(profile.contractedGridKw,0);out.transformerPf=finiteNumber(profile.transformerPf,.96);out.gridVoltageV=finiteNumber(profile.gridVoltageV,400);out.gridFrequencyHz=finiteNumber(profile.gridFrequencyHz,50);out.transformerTempC=finiteNumber(profile.transformerTempC,45);out.solarInstalledKw=finiteNumber(profile.solarInstalledKw,0);out.batteryCapacityKwh=finiteNumber(profile.batteryCapacityKwh,0);out.batterySoc=finiteNumber(profile.batterySoc,0);out.batteryMaxKw=finiteNumber(profile.batteryMaxKw,0);out.peakTodayKw=finiteNumber(profile.peakTodayKw,0);out.demandRate=finiteNumber(profile.demandRate,0);out.forecastPeakKw=finiteNumber(profile.forecastPeakKw,0);out.reserveHeadroomKw=finiteNumber(profile.reserveHeadroomKw,0);out.chargerLimits=profile.chargerLimits&&typeof profile.chargerLimits==='object'?profile.chargerLimits:{};out.chargerPriorities=profile.chargerPriorities&&typeof profile.chargerPriorities==='object'?profile.chargerPriorities:{};out.history=Array.isArray(profile.history)?profile.history:[];out.mode=profile.mode||'balanced';out.batteryMode=profile.batteryMode||'auto';return out;
}
function normalizeEnergyAlert(alert={}){const out={...alert};out.timeline=Array.isArray(alert.timeline)?alert.timeline:[];out.status=alert.status||'open';out.severity=alert.severity||'normal';out.type=alert.type||'capacity';return out;}


function finiteNumber(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function normalizeSession(session={}){
 const out={...session};
 out.durationMin=finiteNumber(session.durationMin,0);
 out.socStart=finiteNumber(session.socStart,0);
 out.soc=finiteNumber(session.soc,0);
 out.target=finiteNumber(session.target,80);
 out.powerKw=finiteNumber(session.powerKw,0);
 out.energyKwh=finiteNumber(session.energyKwh,0);
 out.cost=finiteNumber(session.cost,0);
 out.maxPowerKw=finiteNumber(session.maxPowerKw,0);
 out.avgPowerKw=finiteNumber(session.avgPowerKw,0);
 out.chargingLimitKw=finiteNumber(session.chargingLimitKw,0);
 out.meterStartKwh=finiteNumber(session.meterStartKwh,0);
 out.meterLastKwh=finiteNumber(session.meterLastKwh,0);
 out.chargingCurve=Array.isArray(session.chargingCurve)?session.chargingCurve:[];
 out.events=Array.isArray(session.events)?session.events:[];
 out.diagnostics=session.diagnostics&&typeof session.diagnostics==='object'?session.diagnostics:{};
 return out;
}


function normalizeSupportCase(item={}){
 const out={...item};
 out.ageMin=finiteNumber(item.ageMin,item.elapsedMin||0);
 out.elapsedMin=finiteNumber(item.elapsedMin,out.ageMin);
 out.slaTargetMin=finiteNumber(item.slaTargetMin,60);
 out.status=item.status||'open';
 out.priority=item.priority||'normal';
 out.channel=item.channel||'chat';
 out.category=item.category||'general';
 out.team=item.team||'Network Support';
 out.owner=item.owner||'Unassigned';
 out.tags=Array.isArray(item.tags)?item.tags:[];
 out.internalNotes=Array.isArray(item.internalNotes)?item.internalNotes:[];
 out.timeline=Array.isArray(item.timeline)?item.timeline:[];
 return out;
}


function normalizeEmergencyEvent(item={}){
 const out={...item};
 out.status=item.status||'open';out.severity=item.severity||'normal';out.category=item.category||'other';out.elapsedMin=finiteNumber(item.elapsedMin,0);out.impactedSessions=finiteNumber(item.impactedSessions,0);out.customerImpact=item.customerImpact||'Low';out.detectedBy=item.detectedBy||'Operator';out.responseTeam=item.responseTeam||'Network Operations';out.powerState=item.powerState||'normal';out.notifications=Array.isArray(item.notifications)?item.notifications:[];out.timeline=Array.isArray(item.timeline)?item.timeline:[];out.recoveryChecklist=Array.isArray(item.recoveryChecklist)?item.recoveryChecklist:[];out.isolation=item.isolation&&typeof item.isolation==='object'?{site:!!item.isolation.site,charger:!!item.isolation.charger,connector:!!item.isolation.connector,powerConfirmed:!!item.isolation.powerConfirmed}:{site:false,charger:false,connector:false,powerConfirmed:false};return out;
}

function normalizeMaintenanceAlert(alert={}){
 const out={...alert};
 out.occurrences=finiteNumber(alert.occurrences,1);
 out.affectedSessions=finiteNumber(alert.affectedSessions,0);
 out.slaTargetMin=finiteNumber(alert.slaTargetMin,60);
 out.elapsedMin=finiteNumber(alert.elapsedMin,0);
 out.probableCauses=Array.isArray(alert.probableCauses)?alert.probableCauses:[];
 out.suggestedRecovery=Array.isArray(alert.suggestedRecovery)?alert.suggestedRecovery:[];
 out.recoveryAttempts=Array.isArray(alert.recoveryAttempts)?alert.recoveryAttempts:[];
 out.timeline=Array.isArray(alert.timeline)?alert.timeline:[];
 out.diagnostics=alert.diagnostics&&typeof alert.diagnostics==='object'?alert.diagnostics:{};
 out.source=alert.source||'automatic';
 out.category=alert.category||'charger';
 out.customerImpact=alert.customerImpact||'Low';
 return out;
}
function normalizeMaintenanceTicket(ticket={}){
 const out={...ticket};
 out.parts=Array.isArray(ticket.parts)?ticket.parts:[];
 out.timeline=Array.isArray(ticket.timeline)?ticket.timeline:[];
 out.status=ticket.status||'unassigned';
 return out;
}


const defaultOperatorSettings={
 profile:{name:'Arman Hakobyan',role:'Network Operator',email:'arman.hakobyan@voltdrive.am',phone:'+374 10 555 010',employeeId:'OP-014',language:'English',timezone:'Asia/Yerevan'},
 shift:{region:'Armenia Network',shiftStart:'08:00',shiftEnd:'20:00',onCall:true,handoffRequired:true,escalationTeam:'Network Operations',handoffNote:'Review critical maintenance, payment attention and active safety incidents before shift handoff.'},
 notifications:{criticalIncidents:true,maintenanceAlerts:true,energyAlerts:true,supportSla:true,paymentFailures:true,roamingSettlements:true,desktopSound:true,emailDigest:false},
 reservations:{defaultGraceMin:10,extensionStepMin:5,cancellationCutoffMin:30,autoPromoteWaiting:true,allowOperatorOverride:true},
 maintenance:{slaCriticalMin:30,slaHighMin:60,slaNormalMin:180,slaLowMin:480,autoTicketCritical:true,recurrenceThreshold:3},
 energy:{peakReductionPct:15,reserveHeadroomKw:30,warningPercent:82,criticalPercent:94,batteryReserveSoc:25},
 safety:{requireOperatorReason:true,requireCriticalConfirmation:true,blockRestartWithActiveSession:true,requireSessionStopBeforeRelease:true,auditRetentionDays:365},
 interface:{density:'comfortable',defaultPage:'dashboard',defaultSite:'all',refreshSeconds:30,showLiveBadges:true,rememberFilters:true},
 device:{sessionTimeoutMin:30,desktopNotifications:true,soundAlerts:true,lockOnInactivity:true}
};
seed.operatorSettings=structuredClone(defaultOperatorSettings);

function normalizeOperatorSettings(settings={}){
 const src=settings&&typeof settings==='object'?settings:{};
 const merge=(key)=>({...defaultOperatorSettings[key],...(src[key]||{})});
 const out={profile:merge('profile'),shift:merge('shift'),notifications:merge('notifications'),reservations:merge('reservations'),maintenance:merge('maintenance'),energy:merge('energy'),safety:merge('safety'),interface:merge('interface'),device:merge('device')};
 out.profile.name=out.profile.name||'Arman Hakobyan';out.profile.role=out.profile.role||'Network Operator';out.profile.timezone=out.profile.timezone||'Asia/Yerevan';
 ['defaultGraceMin','extensionStepMin','cancellationCutoffMin'].forEach(k=>out.reservations[k]=finiteNumber(out.reservations[k],defaultOperatorSettings.reservations[k]));
 ['slaCriticalMin','slaHighMin','slaNormalMin','slaLowMin','recurrenceThreshold'].forEach(k=>out.maintenance[k]=finiteNumber(out.maintenance[k],defaultOperatorSettings.maintenance[k]));
 ['peakReductionPct','reserveHeadroomKw','warningPercent','criticalPercent','batteryReserveSoc'].forEach(k=>out.energy[k]=finiteNumber(out.energy[k],defaultOperatorSettings.energy[k]));
 out.safety.auditRetentionDays=finiteNumber(out.safety.auditRetentionDays,365);out.interface.refreshSeconds=finiteNumber(out.interface.refreshSeconds,30);out.device.sessionTimeoutMin=finiteNumber(out.device.sessionTimeoutMin,30);
 return out;
}
export function getDefaultOperatorSettings(){return structuredClone(defaultOperatorSettings);}

function mergeById(base=[],saved=[]){const map=new Map((saved||[]).map(i=>[i.id,i]));const ids=new Set((base||[]).map(i=>i.id));return (base||[]).map(i=>({...i,...(map.get(i.id)||{})})).concat((saved||[]).filter(i=>!ids.has(i.id)));}
export function loadState(){try{const raw=localStorage.getItem(KEY);if(!raw)return structuredClone(seed);const saved=JSON.parse(raw);const fresh=structuredClone(seed);return {...fresh,...saved,network:{...fresh.network,...(saved.network||{})},operatorSettings:normalizeOperatorSettings(saved.operatorSettings||fresh.operatorSettings),revenue:{...fresh.revenue,...(saved.revenue||{})},sites:mergeById(fresh.sites,saved.sites),parkingBays:mergeById(fresh.parkingBays,saved.parkingBays),chargers:mergeById(fresh.chargers,saved.chargers),connectors:mergeById(fresh.connectors,saved.connectors),sessions:mergeById(fresh.sessions,saved.sessions).map(normalizeSession),reservations:mergeById(fresh.reservations,saved.reservations).map(normalizeReservation),maintenanceAlerts:mergeById(fresh.maintenanceAlerts,saved.maintenanceAlerts).map(normalizeMaintenanceAlert),maintenanceTickets:mergeById(fresh.maintenanceTickets,saved.maintenanceTickets).map(normalizeMaintenanceTicket),technicians:mergeById(fresh.technicians,saved.technicians),supportCases:mergeById(fresh.supportCases,saved.supportCases).map(normalizeSupportCase),emergencyEvents:mergeById(fresh.emergencyEvents,saved.emergencyEvents).map(normalizeEmergencyEvent),energyProfiles:mergeById(fresh.energyProfiles,saved.energyProfiles).map(normalizeEnergyProfile),energyAlerts:mergeById(fresh.energyAlerts,saved.energyAlerts).map(normalizeEnergyAlert),tariffs:mergeById(fresh.tariffs,saved.tariffs),revenueDaily:mergeById(fresh.revenueDaily,saved.revenueDaily).map(normalizeRevenueDay),revenueBySite:mergeById(fresh.revenueBySite,saved.revenueBySite).map(normalizeRevenueSite),financialTransactions:mergeById(fresh.financialTransactions,saved.financialTransactions).map(normalizeTransaction),refunds:mergeById(fresh.refunds,saved.refunds).map(normalizeRefund),roamingSettlements:mergeById(fresh.roamingSettlements,saved.roamingSettlements).map(normalizeRoamingSettlement),commandHistory:mergeById(fresh.commandHistory,saved.commandHistory)};}catch(e){console.error('[VoltDrive Operator] state load failed',e);return structuredClone(seed);}}
export function saveState(state){localStorage.setItem(KEY,JSON.stringify(state));}
export function siteById(state,id){return state.sites.find(x=>x.id===id)}
export function chargerById(state,id){return state.chargers.find(x=>x.id===id)}
export function connectorById(state,id){return state.connectors.find(x=>x.id===id)}
export function sessionById(state,id){return state.sessions.find(x=>x.id===id)}
