import {initCommon,showToast} from '../layout/common.js';
import {saveState,siteById,chargerById,connectorById,sessionById} from '../core/operator-state.js';

let state=initCommon('chargers');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat('en-US').format(Math.round(Number(n)||0));
const statusClass=v=>`status-${String(v||'').toLowerCase().replace(/[_\s]+/g,'-')}`;
const nowTime=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
let currentChargerId=null,currentTab='overview';

function connectorsFor(id){return state.connectors.filter(c=>c.charger===id)}
function sessionsFor(id){return state.sessions.filter(s=>s.charger===id)}
function activeSessionFor(id){return state.sessions.find(s=>s.charger===id&&s.status==='active')}
function alertsFor(id){return state.maintenanceAlerts.filter(a=>a.charger===id&&a.status!=='resolved')}
function ticketsFor(id){return state.maintenanceTickets.filter(t=>t.charger===id&&!['resolved','closed'].includes(t.status))}
function commandsFor(id){const connectorIds=new Set(connectorsFor(id).map(c=>c.id)),sessionIds=new Set(sessionsFor(id).map(s=>s.id));return state.commandHistory.filter(c=>c.target===id||connectorIds.has(c.target)||sessionIds.has(c.target))}
function firmwareNeedsAttention(c){return c.firmwareStatus==='update_available'||(c.firmwareStatus!=='scheduled'&&c.firmwareLatest&&c.firmware!==c.firmwareLatest)}
function operational(c){return ['online','busy','reserved'].includes(c.status)}
function attentionScore(c){const order={faulted:0,warning:1,maintenance:2,offline:3,blocked:4,reserved:5,busy:6,online:7};let score=(order[c.status]??8)*100;score+=Math.max(0,Number(c.health)||0);if(firmwareNeedsAttention(c))score-=18;if(Number(c.temp)>=55)score-=25;if(alertsFor(c.id).some(a=>a.severity==='critical'))score-=35;return score}
function addCommand(action,target,result='Success',note=''){state.commandHistory.unshift({id:`CMD-${Date.now()}-${Math.floor(Math.random()*90+10)}`,time:nowTime(),action,target,result,operator:state.network.operator,note})}
function persist(message){saveState(state);render();if(currentChargerId)renderDrawer();if(message)showToast(message)}

function populateFilters(){
 $('#charger-site').insertAdjacentHTML('beforeend',state.sites.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join(''));
}
function renderKpis(){
 const op=state.chargers.filter(operational),attention=state.chargers.filter(c=>!operational(c)||Number(c.health)<85||Number(c.temp)>=55),activeCons=state.connectors.filter(c=>c.status==='busy'),firmware=state.chargers.filter(firmwareNeedsAttention),avgUptime=state.chargers.reduce((a,c)=>a+Number(c.uptime||0),0)/Math.max(1,state.chargers.length),avgHealth=state.chargers.reduce((a,c)=>a+Number(c.health||0),0)/Math.max(1,state.chargers.length);
 $('#kpi-operational').textContent=`${op.length}/${state.chargers.length}`;$('#kpi-operational-note').textContent=`${Math.round(op.length/state.chargers.length*100)}% customer available`;
 $('#kpi-attention').textContent=attention.length;$('#kpi-attention-note').textContent=`${state.chargers.filter(c=>['faulted','warning'].includes(c.status)).length} fault/warning assets`;
 $('#kpi-active-connectors').textContent=activeCons.length;$('#kpi-active-note').textContent=`${state.connectors.filter(c=>c.status==='available').length} connectors available`;
 $('#kpi-uptime').textContent=`${avgUptime.toFixed(1)}%`;$('#kpi-health-note').textContent=`${Math.round(avgHealth)}% average hardware health`;
 $('#kpi-firmware').textContent=firmware.length;$('#kpi-firmware-note').textContent=firmware.length?'Approved updates available':'Fleet current';
 $('#charger-network-chip').textContent=`${state.chargers.length} chargers`;$('#connector-network-chip').textContent=`${state.connectors.length} connectors`;
}
function filteredChargers(){
 const q=$('#charger-search').value.trim().toLowerCase(),site=$('#charger-site').value,status=$('#charger-status').value,firmware=$('#charger-firmware').value,sort=$('#charger-sort').value;
 let list=state.chargers.filter(c=>{const s=siteById(state,c.site);const hay=[c.id,c.name,c.serial,c.vendor,c.model,c.ip,s?.name].join(' ').toLowerCase();if(q&&!hay.includes(q))return false;if(site!=='all'&&c.site!==site)return false;if(status!=='all'&&c.status!==status)return false;if(firmware==='attention'&&!firmwareNeedsAttention(c))return false;if(firmware==='current'&&(firmwareNeedsAttention(c)||c.firmwareStatus==='scheduled'))return false;if(firmware==='scheduled'&&c.firmwareStatus!=='scheduled')return false;return true});
 const sorters={attention:(a,b)=>attentionScore(a)-attentionScore(b),site:(a,b)=>(siteById(state,a.site)?.name||'').localeCompare(siteById(state,b.site)?.name||''),health:(a,b)=>Number(a.health)-Number(b.health),temperature:(a,b)=>Number(b.temp)-Number(a.temp),uptime:(a,b)=>Number(a.uptime)-Number(b.uptime),name:(a,b)=>a.name.localeCompare(b.name)};return list.sort(sorters[sort]||sorters.attention);
}
function renderTable(){
 const list=filteredChargers();$('#charger-result-count').textContent=`${list.length} assets`;
 $('#charger-table-body').innerHTML=list.map(c=>{const site=siteById(state,c.site),cons=connectorsFor(c.id),available=cons.filter(x=>x.status==='available').length,session=activeSessionFor(c.id),fw=firmwareNeedsAttention(c)?`<span class="ui-pill status-warning">${esc(c.firmware)} → ${esc(c.firmwareLatest)}</span>`:c.firmwareStatus==='scheduled'?`<span class="ui-pill status-reserved">Scheduled</span>`:`<span class="ui-pill status-online">${esc(c.firmware)}</span>`;return `<tr data-charger-row="${c.id}"><td><div class="entity-main"><strong>${esc(c.name)} · ${c.maxKw} kW</strong><span>${esc(c.vendor)} ${esc(c.model)} · ${esc(c.serial)}</span></div></td><td><div class="entity-main"><strong>${esc(site?.name||c.site)}</strong><span>${esc(c.ip||'—')}</span></div></td><td><span class="ui-pill ${statusClass(c.status)}">${esc(c.status)}</span></td><td><div class="entity-main"><strong>${available}/${cons.length} available</strong><span>${cons.map(x=>`${x.type} ${x.maxKw}kW`).join(' · ')}</span></div></td><td>${session?`<div class="entity-main"><strong>${esc(session.id)}</strong><span>${esc(session.driver)} · ${session.powerKw} kW</span></div>`:'<span class="charger-muted">No live session</span>'}</td><td><div class="charger-health-cell"><strong>${c.health}%</strong><span class="charger-health-meter"><i style="width:${Math.max(0,Math.min(100,c.health))}%"></i></span></div></td><td><strong class="${Number(c.temp)>=55?'session-danger':''}">${c.temp} °C</strong></td><td>${Number(c.uptime||0).toFixed(1)}%</td><td>${fw}</td></tr>`}).join('')||`<tr><td colspan="9"><div class="site-empty">No chargers match the current filters.</div></td></tr>`;
 $$('[data-charger-row]').forEach(row=>row.addEventListener('click',()=>openCharger(row.dataset.chargerRow)));
}
function attentionReasons(c){const reasons=[];if(['faulted','warning','maintenance','offline','blocked'].includes(c.status))reasons.push(c.status);if(Number(c.health)<85)reasons.push(`health ${c.health}%`);if(Number(c.temp)>=55)reasons.push(`${c.temp} °C`);if(firmwareNeedsAttention(c))reasons.push('firmware');const alerts=alertsFor(c.id);if(alerts.length)reasons.push(`${alerts.length} alert${alerts.length===1?'':'s'}`);return reasons}
function renderAttention(){
 const list=state.chargers.map(c=>({c,reasons:attentionReasons(c)})).filter(x=>x.reasons.length).sort((a,b)=>attentionScore(a.c)-attentionScore(b.c));$('#attention-count').textContent=list.length;
 $('#charger-attention-list').innerHTML=list.slice(0,7).map(({c,reasons})=>`<button type="button" class="charger-attention-entry" data-attention-charger="${c.id}"><span class="charger-attention-entry__icon">!</span><div><strong>${esc(c.name)} · ${esc(siteById(state,c.site)?.name||c.site)}</strong><span>${esc(reasons.join(' · '))}</span></div><span class="ui-pill ${statusClass(c.status)}">${esc(c.status)}</span></button>`).join('')||`<div class="site-empty">No charger requires attention.</div>`;
 $$('[data-attention-charger]').forEach(el=>el.addEventListener('click',()=>openCharger(el.dataset.attentionCharger)));
}
function renderCommands(){
 const list=state.commandHistory.filter(c=>state.chargers.some(ch=>ch.id===c.target)||state.connectors.some(con=>con.id===c.target)||state.sessions.some(s=>s.id===c.target)).slice(0,7);
 $('#charger-command-list').innerHTML=list.map(c=>`<div class="command-mini-row"><span class="command-mini-icon">↯</span><div><strong>${esc(c.action)}</strong><span>${esc(c.target)} · ${esc(c.time)}${c.note?` · ${esc(c.note)}`:''}</span></div><span class="ui-pill ${String(c.result).toLowerCase()==='success'?'status-online':'status-faulted'}">${esc(c.result)}</span></div>`).join('')||`<div class="site-empty">No recent remote commands.</div>`;
}
function render(){renderKpis();renderTable();renderAttention();renderCommands()}

function openCharger(id){if(!chargerById(state,id))return;currentChargerId=id;currentTab='overview';$('#charger-drawer-backdrop').hidden=false;requestAnimationFrame(()=>$('#charger-drawer-backdrop').classList.add('is-visible'));$('#charger-drawer').classList.add('is-open');$('#charger-drawer').setAttribute('aria-hidden','false');$$('[data-charger-tab]').forEach(t=>t.classList.toggle('is-active',t.dataset.chargerTab==='overview'));renderDrawer()}
function closeCharger(){currentChargerId=null;$('#charger-drawer-backdrop').classList.remove('is-visible');$('#charger-drawer').classList.remove('is-open');$('#charger-drawer').setAttribute('aria-hidden','true');setTimeout(()=>{if(!$('#charger-drawer').classList.contains('is-open'))$('#charger-drawer-backdrop').hidden=true},190)}
$('#charger-drawer-close').addEventListener('click',closeCharger);$('#charger-drawer-backdrop').addEventListener('click',closeCharger);
$$('[data-charger-tab]').forEach(tab=>tab.addEventListener('click',()=>{currentTab=tab.dataset.chargerTab;$$('[data-charger-tab]').forEach(x=>x.classList.toggle('is-active',x===tab));renderDrawer()}));

function renderDrawer(){
 const c=chargerById(state,currentChargerId);if(!c)return closeCharger();const site=siteById(state,c.site);$('#charger-drawer-title').textContent=`${c.name} · ${c.maxKw} kW`;$('#charger-drawer-subtitle').textContent=`${site?.name||c.site} · ${c.vendor} ${c.model} · ${c.serial}`;
 const bodies={overview:renderOverview(c),connectors:renderConnectors(c),faults:renderFaults(c),firmware:renderFirmware(c),controls:renderControls(c)};$('#charger-drawer-body').innerHTML=bodies[currentTab]||bodies.overview;
 $('#charger-drawer-footer').innerHTML=`<button class="button button--secondary" id="charger-open-site">Open Site</button><button class="button button--secondary" id="charger-open-sessions">Sessions</button><button class="button button--primary" id="charger-open-maintenance">Maintenance</button>`;
 $('#charger-open-site').onclick=()=>location.href=`sites.html?site=${encodeURIComponent(c.site)}`;$('#charger-open-sessions').onclick=()=>location.href=`sessions.html?charger=${encodeURIComponent(c.id)}`;$('#charger-open-maintenance').onclick=()=>location.href=`maintenance.html?charger=${encodeURIComponent(c.id)}`;
 bindDrawerActions(c);
}
function renderOverview(c){const site=siteById(state,c.site),cons=connectorsFor(c.id),active=activeSessionFor(c.id),available=cons.filter(x=>x.status==='available').length,openAlerts=alertsFor(c.id);return `<section class="ui-detail-section"><div class="charger-overview-banner"><div><strong>${esc(c.name)} · ${esc(c.vendor)} ${esc(c.model)}</strong><span>${esc(site?.name||c.site)} · ${c.maxKw} kW · ${esc(c.protocol||'OCPP')}</span></div><span class="ui-pill ${statusClass(c.status)}">${esc(c.status)}</span></div></section>${openAlerts.length?`<section class="ui-detail-section"><div class="ui-callout ${openAlerts.some(a=>a.severity==='critical')?'ui-callout--danger':'ui-callout--warning'}"><strong>${openAlerts.length} open maintenance alert${openAlerts.length===1?'':'s'}</strong><span>${openAlerts.map(a=>`${a.code}: ${a.title}`).join(' · ')}</span></div></section>`:''}<section class="ui-detail-section"><h3>Hardware profile</h3><div class="ui-detail-grid"><div><span>Serial number</span><strong>${esc(c.serial)}</strong></div><div><span>Maximum power</span><strong>${c.maxKw} kW</strong></div><div><span>Protocol</span><strong>${esc(c.protocol||'—')}</strong></div><div><span>IP address</span><strong>${esc(c.ip||'—')}</strong></div><div><span>Network</span><strong>${esc(c.network||'—')}</strong></div><div><span>Signal</span><strong>${esc(c.signal||'—')}</strong></div><div><span>Input voltage</span><strong>${esc(c.inputVoltage||'—')} V</strong></div><div><span>Grid phase</span><strong>${esc(c.gridPhase||'—')}</strong></div></div></section><section class="ui-detail-section"><h3>Live operating state</h3><div class="ui-detail-grid"><div><span>Hardware health</span><strong>${c.health}%</strong></div><div><span>Temperature</span><strong class="${Number(c.temp)>=55?'session-danger':''}">${c.temp} °C</strong></div><div><span>30-day uptime</span><strong>${Number(c.uptime||0).toFixed(1)}%</strong></div><div><span>Last heartbeat</span><strong>${esc(c.lastHeartbeat||'—')}</strong></div><div><span>Connectors</span><strong>${available}/${cons.length} available</strong></div><div><span>Errors · 24h</span><strong>${c.errors24h??0}</strong></div><div><span>Cabinet</span><strong>${esc(c.cabinet||'—')}</strong></div><div><span>Emergency stop</span><strong>${c.emergencyStop?'Pressed':'Normal'}</strong></div></div></section><section class="ui-detail-section"><h3>Active session</h3>${active?`<button class="charger-session-card" type="button" data-open-session="${active.id}"><div><strong>${esc(active.id)} · ${esc(active.driver)}</strong><span>${esc(active.vehicle)} · SOC ${active.soc}% → ${active.target}%</span></div><div><strong>${active.powerKw} kW</strong><span>${Number(active.energyKwh||0).toFixed(1)} kWh · ${fmt(active.cost)} AMD</span></div></button>`:`<div class="site-empty">No active charging session on this charger.</div>`}</section>`}
function renderConnectors(c){const cons=connectorsFor(c.id);return `<section class="ui-detail-section"><h3>Connector inventory</h3><div class="connector-ops-list">${cons.map(con=>{const session=state.sessions.find(s=>s.connector===con.id&&s.status==='active');return `<article class="connector-ops-card"><div class="connector-ops-card__head"><div><strong>Connector ${con.number} · ${esc(con.type)}</strong><span>${con.maxKw} kW · ${esc(con.id)}</span></div><span class="ui-pill ${statusClass(con.status)}">${esc(con.status)}</span></div><div class="ui-detail-grid"><div><span>Health</span><strong>${con.health??'—'}%</strong></div><div><span>Temperature</span><strong>${con.temp??'—'} °C</strong></div><div><span>Cable lock</span><strong>${con.locked?'Locked':'Released'}</strong></div><div><span>Session cycles</span><strong>${fmt(con.sessionCycles||0)}</strong></div><div><span>Fault code</span><strong>${esc(con.fault||'None')}</strong></div><div><span>Live session</span><strong>${esc(session?.id||'None')}</strong></div></div><div class="connector-ops-card__actions"><button class="action-button" data-connector-command="release-cable" data-target="${con.id}" ${session?'disabled':''}>Release Cable</button><button class="action-button" data-connector-command="${con.status==='disabled'?'enable-connector':'disable-connector'}" data-target="${con.id}" ${session?'disabled':''}>${con.status==='disabled'?'Enable':'Disable'}</button><button class="action-button" data-create-ticket-connector="${con.id}">Create Ticket</button></div></article>`}).join('')}</div></section>`}
function renderFaults(c){const alerts=state.maintenanceAlerts.filter(a=>a.charger===c.id),sessions=sessionsFor(c.id).filter(s=>['active','failed'].includes(s.status)),commands=commandsFor(c.id).slice(0,8);return `<section class="ui-detail-section"><h3>Charging sessions</h3>${sessions.length?`<div class="charger-activity-stack">${sessions.map(s=>`<button class="charger-activity-row" type="button" data-open-session="${s.id}"><div><strong>${esc(s.id)} · ${esc(s.driver)}</strong><span>${esc(s.vehicle)} · ${Number(s.energyKwh||0).toFixed(1)} kWh · ${fmt(s.cost)} AMD</span></div><span class="ui-pill ${statusClass(s.status)}">${esc(s.status)}</span></button>`).join('')}</div>`:`<div class="site-empty">No active or failed sessions.</div>`}</section><section class="ui-detail-section"><h3>Fault / alert history</h3>${alerts.length?`<div class="charger-activity-stack">${alerts.map(a=>`<button class="charger-activity-row" type="button" data-open-alert="${a.id}"><div><strong>${esc(a.code)} · ${esc(a.title)}</strong><span>${esc(a.created)} · ${esc(a.body)}</span></div><span class="ui-pill priority-${a.severity}">${esc(a.severity)}</span></button>`).join('')}</div>`:`<div class="site-empty">No maintenance alerts recorded.</div>`}</section><section class="ui-detail-section"><h3>Remote command history</h3>${commands.length?`<div class="charger-activity-stack">${commands.map(cmd=>`<div class="charger-activity-row"><div><strong>${esc(cmd.action)}</strong><span>${esc(cmd.time)} · ${esc(cmd.target)}${cmd.note?` · ${esc(cmd.note)}`:''}</span></div><span class="ui-pill ${String(cmd.result).toLowerCase()==='success'?'status-online':'status-faulted'}">${esc(cmd.result)}</span></div>`).join('')}</div>`:`<div class="site-empty">No remote commands for this charger.</div>`}</section>`}
function renderFirmware(c){const attention=firmwareNeedsAttention(c),scheduled=c.firmwareStatus==='scheduled';return `<section class="ui-detail-section"><div class="ui-callout ${attention?'ui-callout--warning':''}"><strong>${attention?'Firmware update available':scheduled?'Firmware update scheduled':'Firmware current'}</strong><span>Installed ${esc(c.firmware)} · latest approved ${esc(c.firmwareLatest||c.firmware)}${c.firmwareScheduled?` · ${esc(c.firmwareScheduled)}`:''}</span></div></section><section class="ui-detail-section"><h3>Firmware & service</h3><div class="ui-detail-grid"><div><span>Installed firmware</span><strong>${esc(c.firmware)}</strong></div><div><span>Latest approved</span><strong>${esc(c.firmwareLatest||c.firmware)}</strong></div><div><span>Firmware state</span><strong>${esc(c.firmwareStatus||'current')}</strong></div><div><span>Reboots · 30d</span><strong>${c.reboots30d??0}</strong></div><div><span>Installed</span><strong>${esc(c.installDate||'—')}</strong></div><div><span>Last service</span><strong>${esc(c.lastService||'—')}</strong></div><div><span>Next service</span><strong>${esc(c.nextService||'—')}</strong></div><div><span>Lifetime meter</span><strong>${fmt(c.meterKwh||0)} kWh</strong></div></div></section><section class="ui-detail-section"><div class="dashboard-actions"><button class="button button--secondary" id="schedule-firmware" ${attention||scheduled?'':'disabled'}>${scheduled?'Reschedule Update':'Schedule Firmware Update'}</button><button class="button button--secondary" id="create-maintenance-ticket">Create Maintenance Ticket</button></div></section>`}
function renderControls(c){const active=activeSessionFor(c.id),critical=alertsFor(c.id).some(a=>['critical','high'].includes(a.severity))||ticketsFor(c.id).some(t=>['critical','high'].includes(t.priority));return `<section class="ui-detail-section"><div class="ui-callout ui-callout--warning"><strong>Permission-sensitive remote controls</strong><span>Commands affect live charging hardware. Active sessions and unresolved critical faults may block unsafe actions.</span></div></section><section class="ui-detail-section"><div class="charger-control-grid"><div class="site-control-card"><strong>Controlled restart</strong><span>${active?'Blocked while a charging session is active.':'Restart EVSE software and communications stack.'}</span><button class="button button--secondary" data-charger-command="restart-charger" data-target="${c.id}" ${active?'disabled':''}>Restart Charger</button></div><div class="site-control-card"><strong>Customer availability</strong><span>${c.status==='blocked'?'Charger is blocked from customer use.':'Block this charger from new customer sessions.'}</span><button class="button ${c.status==='blocked'?'button--secondary':'button--danger'}" data-charger-command="${c.status==='blocked'?'unblock-charger':'block-charger'}" data-target="${c.id}" ${active?'disabled':''}>${c.status==='blocked'?'Unblock Charger':'Block Charger'}</button></div><div class="site-control-card"><strong>Maintenance state</strong><span>${c.status==='maintenance'?'Return after technical clearance.':'Place the EVSE into service maintenance mode.'}</span><button class="button button--secondary" data-charger-command="${c.status==='maintenance'?'return-online':'set-maintenance'}" data-target="${c.id}" ${(active||(c.status==='maintenance'&&critical))?'disabled':''}>${c.status==='maintenance'?'Return Online':'Set Maintenance'}</button></div><div class="site-control-card"><strong>Maintenance workflow</strong><span>Create a ticket with charger/connector context for the technical team.</span><button class="button button--secondary" id="control-create-ticket">Create Ticket</button></div></div></section>${active?`<section class="ui-detail-section"><div class="ui-callout ui-callout--danger"><strong>Active session ${esc(active.id)}</strong><span>${esc(active.driver)} · ${active.powerKw} kW. Stop the session only for safety, fault recovery or a customer request.</span></div><button class="button button--danger charger-stop-button" data-charger-command="stop-session" data-target="${active.id}">Stop Active Session</button></section>`:''}`}

function bindDrawerActions(c){
 $$('[data-open-session]').forEach(el=>el.addEventListener('click',()=>location.href=`sessions.html?session=${encodeURIComponent(el.dataset.openSession)}`));
 $$('[data-open-alert]').forEach(el=>el.addEventListener('click',()=>location.href=`maintenance.html?alert=${encodeURIComponent(el.dataset.openAlert)}`));
 $$('[data-charger-command]').forEach(el=>el.addEventListener('click',()=>openCommand(el.dataset.chargerCommand,el.dataset.target)));
 $$('[data-connector-command]').forEach(el=>el.addEventListener('click',()=>openCommand(el.dataset.connectorCommand,el.dataset.target)));
 $$('[data-create-ticket-connector]').forEach(el=>el.addEventListener('click',()=>openTicketDialog(c.id,el.dataset.createTicketConnector)));
 $('#schedule-firmware')?.addEventListener('click',()=>openFirmwareDialog(c.id));$('#create-maintenance-ticket')?.addEventListener('click',()=>openTicketDialog(c.id,''));$('#control-create-ticket')?.addEventListener('click',()=>openTicketDialog(c.id,''));
}

const commandConfig={
 'restart-charger':{title:'Restart Charger',description:'Send a controlled remote restart command.',target:'charger',action:'Restart charger'},
 'release-cable':{title:'Release Cable',description:'Attempt safe cable release on the selected connector.',target:'connector',action:'Release cable'},
 'disable-connector':{title:'Disable Connector',description:'Block the connector from accepting new charging sessions.',target:'connector',action:'Disable connector'},
 'enable-connector':{title:'Enable Connector',description:'Return a healthy disabled connector to service.',target:'connector',action:'Enable connector'},
 'block-charger':{title:'Block Charger',description:'Block the EVSE from new customer charging sessions.',target:'charger',action:'Block charger'},
 'unblock-charger':{title:'Unblock Charger',description:'Return a cleared blocked charger to customer availability.',target:'charger',action:'Unblock charger'},
 'set-maintenance':{title:'Set Maintenance',description:'Place the EVSE and healthy connectors into maintenance state.',target:'charger',action:'Set charger maintenance'},
 'return-online':{title:'Return Charger Online',description:'Return the charger after technical clearance.',target:'charger',action:'Return charger online'},
 'stop-session':{title:'Stop Charging Session',description:'Operator safety/customer-request stop. Delivered energy is preserved.',target:'session',action:'Stop session'}
};
function targetList(kind){if(kind==='charger')return state.chargers.map(c=>({id:c.id,label:`${c.name} · ${siteById(state,c.site)?.name} · ${c.status}`}));if(kind==='connector')return state.connectors.map(con=>({id:con.id,label:`${chargerById(state,con.charger)?.name} / ${con.type} · ${con.status}`}));if(kind==='session')return state.sessions.filter(s=>s.status==='active').map(s=>({id:s.id,label:`${s.id} · ${s.driver} · ${chargerById(state,s.charger)?.name}`}));return[]}
function openCommand(type,preset){const cfg=commandConfig[type];if(!cfg)return;$('#charger-command-title').textContent=cfg.title;$('#charger-command-subtitle').textContent=cfg.description;$('#charger-command-warning').textContent=cfg.action;$('#charger-command-type').value=type;const list=targetList(cfg.target);$('#charger-command-target').innerHTML=list.map(x=>`<option value="${x.id}">${esc(x.label)}</option>`).join('');if(preset&&list.some(x=>x.id===preset))$('#charger-command-target').value=preset;$('#charger-command-note').value='';$('#charger-command-dialog').showModal()}
function closeCommand(){$('#charger-command-dialog').close()}
$('#charger-command-close').addEventListener('click',closeCommand);$('#charger-command-cancel').addEventListener('click',closeCommand);
$('#charger-command-confirm').addEventListener('click',()=>{const type=$('#charger-command-type').value,target=$('#charger-command-target').value,note=$('#charger-command-note').value.trim(),cfg=commandConfig[type];if(!cfg||!target)return;let result='Success',message='';
 if(type==='restart-charger'){const c=chargerById(state,target);if(activeSessionFor(target)){result='Blocked';message='Active session must be stopped first.'}else if(c?.status==='faulted'&&alertsFor(target).some(a=>a.severity==='critical')){result='Failed';c.reboots30d=(c.reboots30d||0)+1;message='Restart failed; critical hardware fault remains.'}else if(c){c.status='online';c.lastHeartbeat=nowTime()+':00';c.reboots30d=(c.reboots30d||0)+1;c.temp=Math.max(30,Number(c.temp)-3);message='Charger restarted successfully.'}}
 if(type==='release-cable'){const con=connectorById(state,target),active=state.sessions.find(s=>s.connector===target&&s.status==='active');if(active){result='Blocked';message='Cable cannot be released during an active session.'}else if(con){con.locked=false;if(con.status==='busy')con.status='available';message='Cable lock released.'}}
 if(type==='disable-connector'){const con=connectorById(state,target),active=state.sessions.find(s=>s.connector===target&&s.status==='active');if(active){result='Blocked';message='Connector has an active session.'}else if(con){con.status='disabled';message='Connector disabled.'}}
 if(type==='enable-connector'){const con=connectorById(state,target);if(con?.fault){result='Blocked';message=`Connector fault ${con.fault} must be cleared first.`}else if(con){con.status='available';message='Connector enabled.'}}
 if(type==='block-charger'){const c=chargerById(state,target);if(activeSessionFor(target)){result='Blocked';message='Active session must be stopped first.'}else if(c){c.status='blocked';connectorsFor(target).forEach(con=>{if(!['faulted','maintenance'].includes(con.status))con.status='disabled'});message='Charger blocked from customer use.'}}
 if(type==='unblock-charger'){const c=chargerById(state,target);if(alertsFor(target).some(a=>['critical','high'].includes(a.severity))){result='Blocked';message='High/critical maintenance alert must be cleared first.'}else if(c){c.status='online';connectorsFor(target).forEach(con=>{if(con.status==='disabled'&&!con.fault)con.status='available'});message='Charger returned to customer availability.'}}
 if(type==='set-maintenance'){const c=chargerById(state,target);if(activeSessionFor(target)){result='Blocked';message='Active session must be stopped first.'}else if(c){c.status='maintenance';connectorsFor(target).forEach(con=>{if(!['faulted','disabled'].includes(con.status))con.status='maintenance'});message='Charger placed in maintenance.'}}
 if(type==='return-online'){const c=chargerById(state,target);if(alertsFor(target).some(a=>['critical','high'].includes(a.severity))||ticketsFor(target).some(t=>['critical','high'].includes(t.priority))){result='Blocked';message='Critical maintenance work remains open.'}else if(c){c.status='online';connectorsFor(target).forEach(con=>{if(con.status==='maintenance'&&!con.fault)con.status='available'});message='Charger returned online.'}}
 if(type==='stop-session'){const s=sessionById(state,target);if(s){const ended=nowTime();s.status='completed';s.ended=ended;s.stopReason=note||'Stopped by network operator';s.powerKw=0;if(s.payment==='preauthorized')s.payment='pending';if(!Array.isArray(s.events))s.events=[];s.events.push({time:ended,type:'operator',title:'Session stopped by operator',detail:s.stopReason},{time:ended,type:'payment',title:'Settlement queued',detail:'Final delivered energy submitted for payment settlement.'});const con=connectorById(state,s.connector);if(con){con.status='available';con.locked=false}const c=chargerById(state,s.charger);if(c&&!['faulted','maintenance','blocked','warning'].includes(c.status))c.status='online';message='Charging session stopped and settlement queued.'}}
 addCommand(cfg.action,target,result,note||message);saveState(state);closeCommand();render();if(currentChargerId)renderDrawer();showToast(`${cfg.action}: ${result}${message?` · ${message}`:''}`)});

function openFirmwareDialog(id){const c=chargerById(state,id);if(!c)return;currentChargerId=id;$('#firmware-dialog-subtitle').textContent=`${c.name} · ${siteById(state,c.site)?.name}`;$('#firmware-current').textContent=c.firmware;$('#firmware-latest').textContent=c.firmwareLatest||c.firmware;$('#firmware-note').value='';$('#firmware-dialog').showModal()}
function closeFirmware(){$('#firmware-dialog').close()}
$('#firmware-dialog-close').addEventListener('click',closeFirmware);$('#firmware-cancel').addEventListener('click',closeFirmware);
$('#firmware-confirm').addEventListener('click',()=>{const c=chargerById(state,currentChargerId);if(!c)return;const window=$('#firmware-window').value,note=$('#firmware-note').value.trim();c.firmwareStatus='scheduled';c.firmwareScheduled=window;addCommand('Schedule firmware update',c.id,'Success',`${c.firmware} → ${c.firmwareLatest} · ${window}${note?` · ${note}`:''}`);saveState(state);closeFirmware();render();renderDrawer();showToast(`Firmware update scheduled for ${c.name}`)});

function openTicketDialog(chargerId,connectorId=''){const c=chargerById(state,chargerId);if(!c)return;currentChargerId=chargerId;$('#ticket-dialog-subtitle').textContent=`${c.name} · ${siteById(state,c.site)?.name}`;const cons=connectorsFor(chargerId);$('#ticket-connector').innerHTML=`<option value="">Whole charger</option>${cons.map(con=>`<option value="${con.id}">${con.type} · Connector ${con.number} · ${con.status}</option>`).join('')}`;$('#ticket-connector').value=connectorId||'';const con=connectorId?connectorById(state,connectorId):null;$('#ticket-priority').value=(c.status==='faulted'||con?.status==='faulted')?'critical':(c.status==='warning'||Number(c.temp)>=55)?'high':'normal';$('#ticket-note').value=con?.fault?`Connector fault ${con.fault}`:alertsFor(chargerId)[0]?.title||'';$('#ticket-dialog').showModal()}
function closeTicket(){$('#ticket-dialog').close()}
$('#ticket-dialog-close').addEventListener('click',closeTicket);$('#ticket-cancel').addEventListener('click',closeTicket);
$('#ticket-confirm').addEventListener('click',()=>{const c=chargerById(state,currentChargerId);if(!c)return;const connector=$('#ticket-connector').value||null,priority=$('#ticket-priority').value,note=$('#ticket-note').value.trim()||'Operator technical review requested';const existing=ticketsFor(c.id).find(t=>(t.connector||null)===connector);if(existing){showToast(`Open ticket ${existing.id} already exists`);return}const id=`MT-${String(Date.now()).slice(-5)}`;state.maintenanceTickets.unshift({id,alert:null,site:c.site,charger:c.id,connector,priority,status:'unassigned',technician:null,created:nowTime(),note});const alertId=`AL-${String(Date.now()).slice(-5)}`;state.maintenanceAlerts.unshift({id:alertId,site:c.site,charger:c.id,connector,severity:priority==='critical'?'critical':priority==='high'?'high':'normal',status:'open',code:connectorById(state,connector)?.fault||'OP-REPORT',title:note,body:`Operator-created maintenance request for ${c.name}.`,created:nowTime(),ticket:id});state.maintenanceTickets[0].alert=alertId;addCommand('Create maintenance ticket',c.id,'Success',`${id} · ${priority}`);saveState(state);closeTicket();render();renderDrawer();showToast(`Maintenance ticket ${id} created`)});

['charger-search','charger-site','charger-status','charger-firmware','charger-sort'].forEach(id=>$('#'+id).addEventListener(id==='charger-search'?'input':'change',renderTable));
populateFilters();render();
const params=new URLSearchParams(location.search),requested=params.get('charger');if(requested&&chargerById(state,requested))requestAnimationFrame(()=>openCharger(requested));
