import {initCommon,showToast} from '../layout/common.js';
import {saveState,siteById,chargerById,connectorById,sessionById} from '../core/operator-state.js';
let state=initCommon('dashboard');
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(n){return new Intl.NumberFormat('en-US').format(Math.round(Number(n)||0))}
function num(v,fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback}
function statusClass(v){return `status-${String(v||'').toLowerCase().replace(/\s+/g,'-')}`}
function activeSessions(){return state.sessions.filter(s=>s.status==='active')}
function openAlerts(){return state.maintenanceAlerts.filter(a=>a.status!=='resolved')}
function renderKpis(){
 const online=state.chargers.filter(c=>['online','busy','reserved'].includes(c.status)).length;
 const availability=Math.round(online/state.chargers.length*100);
 $('#kpi-availability').textContent=`${availability}%`;$('#kpi-chargers').textContent=`${online}/${state.chargers.length} operational`;
 $('#kpi-sessions').textContent=activeSessions().length;$('#kpi-session-energy').textContent=`${activeSessions().reduce((a,s)=>a+num(s.energyKwh),0).toFixed(1)} kWh live`;
 const critical=openAlerts().filter(a=>['critical','high'].includes(a.severity)).length;$('#kpi-alerts').textContent=critical;$('#kpi-alerts-note').textContent=`${openAlerts().length} open network alerts`;
 $('#kpi-reservations').textContent=state.reservations.filter(r=>['confirmed','waiting'].includes(r.status)).length;
 $('#kpi-revenue').textContent=`${fmt(state.revenue.today)} AMD`;$('#kpi-transactions').textContent=`${state.revenue.transactions} transactions today`;
 const siteLoad=state.sites.reduce((a,s)=>a+s.evKw+s.buildingKw,0),cap=state.sites.reduce((a,s)=>a+s.capacityKw,0);$('#kpi-load').textContent=`${Math.round(siteLoad/cap*100)}%`;$('#kpi-load-note').textContent=`${fmt(siteLoad)} / ${fmt(cap)} kW network load`;
}
function renderSites(){
 $('#site-grid').innerHTML=state.sites.map(site=>{const chargers=state.chargers.filter(c=>c.site===site.id);const healthy=chargers.filter(c=>!['faulted','maintenance'].includes(c.status)).length;const load=site.buildingKw+site.evKw;return `<article class="site-card" data-site="${site.id}"><div class="site-card__head"><div><strong>${esc(site.name)}</strong><span>${esc(site.address)}</span></div><span class="ui-pill ${statusClass(site.status)}">${site.status}</span></div><div class="site-card__stats"><div><span>Chargers</span><b>${healthy}/${chargers.length}</b></div><div><span>Load</span><b>${load} kW</b></div><div><span>Reliability</span><b>${site.reliability}%</b></div></div><div class="health-track"><span style="width:${Math.min(100,site.reliability)}%"></span></div></article>`}).join('');
 document.querySelectorAll('[data-site]').forEach(el=>el.addEventListener('click',()=>openSite(el.dataset.site)));
}
function renderSessions(){
 $('#sessions-body').innerHTML=activeSessions().map(s=>{const site=siteById(state,s.site),charger=chargerById(state,s.charger);return `<tr data-session="${s.id}"><td><div class="entity-main"><strong>${esc(s.id)}</strong><span>${esc(s.driver)} · ${esc(s.vehicle)}</span></div></td><td>${esc(site?.name)}</td><td><div class="entity-main"><strong>${esc(charger?.name)}</strong><span>${esc(connectorById(state,s.connector)?.type)}</span></div></td><td><strong>${s.soc}% → ${s.target}%</strong></td><td>${s.powerKw} kW</td><td>${num(s.energyKwh).toFixed(1)} kWh</td><td>${fmt(s.cost)} AMD</td><td><span class="ui-pill status-active">Active</span></td></tr>`}).join('');
 document.querySelectorAll('[data-session]').forEach(row=>row.addEventListener('click',()=>openSession(row.dataset.session)));
}
function renderAttention(){
 const items=[...openAlerts()].sort((a,b)=>({critical:0,high:1,normal:2,low:3}[a.severity]-({critical:0,high:1,normal:2,low:3}[b.severity]))).slice(0,5);
 $('#attention-list').innerHTML=items.map(a=>{const site=siteById(state,a.site),ch=chargerById(state,a.charger);return `<div class="attention-item" data-alert="${a.id}"><span class="attention-icon">!</span><div><strong>${esc(a.title)}</strong><span>${esc(site?.name)} · ${esc(ch?.name||'Site')} · ${esc(a.code)}</span></div><span class="ui-pill priority-${a.severity}">${a.severity}</span></div>`}).join('');
 document.querySelectorAll('[data-alert]').forEach(el=>el.addEventListener('click',()=>openAlert(el.dataset.alert)));
}
function renderEnergy(){
 $('#energy-list').innerHTML=state.sites.map(site=>{const total=site.evKw+site.buildingKw,percent=Math.round(total/site.capacityKw*100);return `<div class="energy-row"><div><strong>${esc(site.name)}</strong><span>EV ${site.evKw} kW · Building ${site.buildingKw} kW · Solar ${site.solarKw} kW</span></div><div class="value-right"><b>${percent}%</b><span>${total}/${site.capacityKw} kW</span></div></div>`}).join('');
}
function renderRevenue(){
 $('#revenue-total').textContent=`${fmt(state.revenue.today)} AMD`;
 $('#revenue-breakdown').innerHTML=`<div><span>Energy</span><strong>${fmt(state.revenue.energy)} AMD</strong></div><div><span>Reservations</span><strong>${fmt(state.revenue.reservations)} AMD</strong></div><div><span>Idle</span><strong>${fmt(state.revenue.idle)} AMD</strong></div><div><span>Parking</span><strong>${fmt(state.revenue.parking)} AMD</strong></div>`;
}
function renderSupport(){
 $('#support-list').innerHTML=state.supportCases.filter(c=>c.status!=='resolved').sort((a,b)=>num(b.elapsedMin,b.ageMin)-num(a.elapsedMin,a.ageMin)).slice(0,4).map(c=>`<div class="support-case" data-support-case="${esc(c.id)}"><div class="support-case__head"><strong>${esc(c.id)} · ${esc(c.customer)}</strong><span class="ui-pill priority-${c.priority}">${c.priority}</span></div><span>${esc(c.subject)}</span><span>${num(c.elapsedMin,c.ageMin)} min · ${esc(siteById(state,c.site)?.name||'Network')}</span></div>`).join('');
 document.querySelectorAll('[data-support-case]').forEach(el=>el.addEventListener('click',()=>location.href=`support.html?case=${encodeURIComponent(el.dataset.supportCase)}`));
}
function renderNetworkSummary(){const failed=state.sessions.filter(s=>s.status==='failed').length;$('#network-summary').innerHTML=`<div><span>Sites</span><strong>${state.sites.length}</strong></div><div><span>Connectors</span><strong>${state.connectors.length}</strong></div><div><span>Failed sessions</span><strong>${failed}</strong></div><div><span>Emergency events</span><strong>${state.emergencyEvents.filter(e=>e.status!=='resolved').length}</strong></div>`;}
function openDrawer(title,subtitle,body,footer=''){ $('#drawer-title').textContent=title;$('#drawer-subtitle').textContent=subtitle;$('#drawer-body').innerHTML=body;$('#drawer-footer').innerHTML=footer;$('#drawer-backdrop').classList.add('is-visible');$('#operator-drawer').classList.add('is-open');}
function closeDrawer(){ $('#drawer-backdrop').classList.remove('is-visible');$('#operator-drawer').classList.remove('is-open');}
$('#drawer-close').addEventListener('click',closeDrawer);$('#drawer-backdrop').addEventListener('click',closeDrawer);
function openSession(id){const s=sessionById(state,id),site=siteById(state,s.site),ch=chargerById(state,s.charger),con=connectorById(state,s.connector);openDrawer(s.id,`${s.driver} · ${s.vehicle}`,`<section class="ui-detail-section"><h3>Active charging session</h3><div class="ui-detail-grid"><div><span>Site</span><strong>${esc(site?.name)}</strong></div><div><span>Charger</span><strong>${esc(ch?.name)} · ${esc(con?.type)}</strong></div><div><span>SOC</span><strong>${s.soc}% / ${s.target}%</strong></div><div><span>Power</span><strong>${s.powerKw} kW</strong></div><div><span>Energy</span><strong>${num(s.energyKwh).toFixed(1)} kWh</strong></div><div><span>Cost</span><strong>${fmt(s.cost)} AMD</strong></div></div></section><section class="ui-detail-section"><div class="ui-callout ui-callout--warning"><strong>Operator safety control</strong><span>Stopping a session is reserved for customer request, fault recovery or safety intervention.</span></div></section>`,`<button class="button button--secondary" id="drawer-view-session">View Sessions</button><button class="button button--danger" id="drawer-stop-session">Stop Session</button>`);$('#drawer-view-session').onclick=()=>location.href=`sessions.html?session=${encodeURIComponent(id)}`;$('#drawer-stop-session').onclick=()=>openCommand('stop-session',id);}
function openAlert(id){const a=state.maintenanceAlerts.find(x=>x.id===id),site=siteById(state,a.site),ch=chargerById(state,a.charger);openDrawer(a.title,`${a.id} · ${a.code}`,`<section class="ui-detail-section"><div class="ui-callout ui-callout--danger"><strong>${esc(a.body)}</strong><span>${esc(site?.name)} · ${esc(ch?.name||'Site')} · created ${esc(a.created)}</span></div></section><section class="ui-detail-section"><h3>Operational context</h3><div class="ui-detail-grid"><div><span>Severity</span><strong>${esc(a.severity)}</strong></div><div><span>Status</span><strong>${esc(a.status)}</strong></div><div><span>Ticket</span><strong>${esc(a.ticket||'Not created')}</strong></div><div><span>Connector</span><strong>${esc(a.connector||'Site/charger')}</strong></div></div></section>`,`<button class="button button--secondary" id="drawer-maintenance">Maintenance Alerts</button><button class="button button--primary" id="drawer-restart">Restart Charger</button>`);$('#drawer-maintenance').onclick=()=>location.href=`maintenance.html?alert=${encodeURIComponent(id)}`;$('#drawer-restart').onclick=()=>openCommand('restart-charger',a.charger);}
function openSite(id){const site=siteById(state,id),chargers=state.chargers.filter(c=>c.site===id);openDrawer(site.name,site.address,`<section class="ui-detail-section"><div class="ui-detail-grid"><div><span>Capacity</span><strong>${site.capacityKw} kW</strong></div><div><span>EV load</span><strong>${site.evKw} kW</strong></div><div><span>Parking</span><strong>${site.parking.available}/${site.parking.total} available</strong></div><div><span>Reliability</span><strong>${site.reliability}%</strong></div></div></section><section class="ui-detail-section"><h3>Chargers</h3>${chargers.map(c=>`<div class="energy-row"><div><strong>${esc(c.name)}</strong><span>${esc(c.vendor)} ${esc(c.model)} · ${c.maxKw} kW</span></div><div class="value-right"><span class="ui-pill ${statusClass(c.status)}">${esc(c.status)}</span></div></div>`).join('')}</section>`,`<button class="button button--primary" id="drawer-site-link">Open Sites</button>`);$('#drawer-site-link').onclick=()=>location.href=`sites.html?site=${encodeURIComponent(id)}`;}
const commandConfig={
 'restart-charger':{title:'Restart charger',description:'Send a controlled remote restart command.',target:'charger',action:'Restart charger'},
 'release-cable':{title:'Release cable',description:'Attempt safe connector cable release.',target:'connector',action:'Release cable'},
 'disable-connector':{title:'Disable connector',description:'Block a connector from new sessions.',target:'connector',action:'Disable connector'},
 'block-charger':{title:'Block charger',description:'Disable the charger from customer use.',target:'charger',action:'Block charger'},
 'stop-session':{title:'Stop charging session',description:'Emergency/operator stop. Current delivered energy will be finalized.',target:'session',action:'Stop session'}
};
function openCommand(type,preset=''){const cfg=commandConfig[type];$('#command-title').textContent=cfg.title;$('#command-description').textContent=cfg.description;$('#command-type').value=type;const select=$('#command-target');let list=[];if(cfg.target==='charger')list=state.chargers.map(c=>({id:c.id,label:`${c.name} · ${siteById(state,c.site)?.name} · ${c.status}`}));if(cfg.target==='connector')list=state.connectors.map(c=>{const ch=chargerById(state,c.charger);return{id:c.id,label:`${ch?.name} / ${c.type} · ${c.status}`}});if(cfg.target==='session')list=activeSessions().map(s=>({id:s.id,label:`${s.id} · ${s.driver} · ${chargerById(state,s.charger)?.name}`}));select.innerHTML=list.map(x=>`<option value="${x.id}">${esc(x.label)}</option>`).join('');if(preset&&list.some(x=>x.id===preset))select.value=preset;$('#command-note').value='';$('#command-dialog').showModal();}
document.querySelectorAll('[data-command]').forEach(btn=>btn.addEventListener('click',()=>openCommand(btn.dataset.command)));
$('#command-cancel').addEventListener('click',()=>$('#command-dialog').close());$('#command-close').addEventListener('click',()=>$('#command-dialog').close());
$('#command-confirm').addEventListener('click',()=>{const type=$('#command-type').value,target=$('#command-target').value,note=$('#command-note').value.trim(),cfg=commandConfig[type];if(!target)return;let result='Success';if(type==='restart-charger'){const ch=chargerById(state,target);if(ch?.status==='faulted'){result='Failed';}else if(ch){ch.status='online';}}if(type==='release-cable'){const con=connectorById(state,target);if(con){con.locked=false;if(con.status==='busy')con.status='available';}}if(type==='disable-connector'){const con=connectorById(state,target);if(con)con.status='disabled';}if(type==='block-charger'){const ch=chargerById(state,target);if(ch)ch.status='blocked';}if(type==='stop-session'){const s=sessionById(state,target);if(s){const ended=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});s.status='completed';s.ended=ended;s.stopReason=note||'Stopped by network operator';s.powerKw=0;if(s.payment==='preauthorized')s.payment='pending';if(!Array.isArray(s.events))s.events=[];s.events.push({time:ended,type:'operator',title:'Session stopped by operator',detail:s.stopReason},{time:ended,type:'payment',title:'Settlement queued',detail:'Final delivered energy submitted for payment settlement.'});const con=connectorById(state,s.connector);if(con){con.status='available';con.locked=false;}const ch=chargerById(state,s.charger);if(ch&&!['faulted','maintenance','blocked','warning'].includes(ch.status))ch.status='online';}}
 state.commandHistory.unshift({id:`CMD-${Date.now()}`,time:new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),action:cfg.action,target,result,operator:state.network.operator,note});saveState(state);$('#command-dialog').close();closeDrawer();render();showToast(`${cfg.action}: ${result}`);});
function render(){renderKpis();renderSites();renderSessions();renderAttention();renderEnergy();renderRevenue();renderSupport();renderNetworkSummary();}
render();
