import {initCommon,showToast} from '../layout/common.js';
import {saveState,siteById,chargerById,connectorById,sessionById} from '../core/operator-state.js';

let state=initCommon('maintenance');
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=v=>String(v??'').replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const statusClass=v=>`status-${String(v||'').toLowerCase().replace(/[_\s]+/g,'-')}`;
const priorityClass=v=>`priority-${String(v||'normal').toLowerCase()}`;
const nowTime=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
let listFilter='all',selectedId=null,drawerTab='overview',pendingStatusAction=null;

const openStatuses=new Set(['open','acknowledged','triaged','recovery','ticketed','monitoring']);
const fieldStatuses=new Set(['assigned','en_route','on_site','in_progress','waiting_parts','qa']);
function alertById(id){return state.maintenanceAlerts.find(a=>a.id===id)}
function ticketFor(a){return a?.ticket?state.maintenanceTickets.find(t=>t.id===a.ticket):state.maintenanceTickets.find(t=>t.alert===a?.id)}
function technicianByName(name){return state.technicians?.find(t=>t.name===name)}
function sessionsForAlert(a){return state.sessions.filter(s=>s.charger===a.charger&&(a.connector? s.connector===a.connector:true))}
function activeSessionOnCharger(charger){return state.sessions.find(s=>s.charger===charger&&s.status==='active')}
function activeSessionOnConnector(connector){return state.sessions.find(s=>s.connector===connector&&s.status==='active')}
function unresolved(a){return a.status!=='resolved'}
function slaRatio(a){return num(a.elapsedMin)/Math.max(1,num(a.slaTargetMin,60))}
function slaLabel(a){if(a.status==='resolved')return 'Closed';const left=Math.max(0,num(a.slaTargetMin)-num(a.elapsedMin));return slaRatio(a)>=1?'Breached':`${left} min left`}
function isSlaRisk(a){return unresolved(a)&&slaRatio(a)>=.75}
function recoveryEligible(a){return unresolved(a)&&a.category!=='preventive'}
function addCommand(action,target,result='Success',note=''){state.commandHistory.unshift({id:`CMD-${Date.now()}-${Math.floor(Math.random()*90+10)}`,time:nowTime(),action,target,result,operator:state.network.operator,note})}
function addTimeline(a,type,eventTitle,detail){a.timeline=Array.isArray(a.timeline)?a.timeline:[];a.timeline.push({time:nowTime(),type,title:eventTitle,detail})}
function persist(message){saveState(state);render();if(selectedId)renderDrawer();if(message)showToast(message)}
function empty(text){return `<div class="reservation-empty">${esc(text)}</div>`}

function populateFilters(){
 $('#maintenance-site').insertAdjacentHTML('beforeend',state.sites.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join(''));
 $('#maintenance-create-site').innerHTML=state.sites.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
 updateCreateChargers();
}

function renderKpis(){
 const open=state.maintenanceAlerts.filter(a=>unresolved(a));
 const severe=open.filter(a=>['critical','high'].includes(a.severity));
 const recovery=open.filter(recoveryEligible);
 const sla=open.filter(isSlaRisk);
 const tickets=state.maintenanceTickets.filter(t=>fieldStatuses.has(t.status));
 const monitoring=open.filter(a=>a.status==='monitoring');
 $('#kpi-maint-open').textContent=open.length;$('#kpi-maint-open-note').textContent=`${open.filter(a=>a.status==='open').length} awaiting triage`;
 $('#kpi-maint-critical').textContent=severe.length;$('#kpi-maint-critical-note').textContent=`${severe.filter(a=>a.severity==='critical').length} critical`;
 $('#kpi-maint-recovery').textContent=recovery.length;$('#kpi-maint-recovery-note').textContent=`${recovery.filter(a=>(a.recoveryAttempts||[]).length===0).length} not attempted`;
 $('#kpi-maint-sla').textContent=sla.length;$('#kpi-maint-sla-note').textContent=`${open.filter(a=>slaRatio(a)>=1).length} breached`;
 $('#kpi-maint-tickets').textContent=tickets.length;$('#kpi-maint-tickets-note').textContent=`${tickets.filter(t=>['on_site','in_progress'].includes(t.status)).length} on site / working`;
 $('#kpi-maint-monitoring').textContent=monitoring.length;$('#kpi-maint-monitoring-note').textContent=`${state.maintenanceAlerts.filter(a=>a.status==='resolved').length} resolved`;
 const badge=$('#maintenance-nav-badge');if(badge)badge.textContent=open.length;
}

function matchesTab(a){
 if(listFilter==='all')return true;
 if(listFilter==='open')return ['open','acknowledged','triaged','recovery'].includes(a.status);
 if(listFilter==='critical')return unresolved(a)&&['critical','high'].includes(a.severity);
 if(listFilter==='ticketed')return Boolean(ticketFor(a))&&unresolved(a);
 if(listFilter==='monitoring')return a.status==='monitoring';
 if(listFilter==='resolved')return a.status==='resolved';
 return true;
}
function filteredAlerts(){
 const q=$('#maintenance-search').value.trim().toLowerCase(),site=$('#maintenance-site').value,severity=$('#maintenance-severity').value,source=$('#maintenance-source').value,sort=$('#maintenance-sort').value;
 let items=state.maintenanceAlerts.filter(a=>matchesTab(a)&&(!q||[a.id,a.code,a.title,a.body,a.charger,a.connector,siteById(state,a.site)?.name].some(v=>String(v||'').toLowerCase().includes(q)))&&(site==='all'||a.site===site)&&(severity==='all'||a.severity===severity)&&(source==='all'||a.source===source));
 items=[...items].sort((a,b)=>{
  if(sort==='recent')return String(b.lastSeen||b.created).localeCompare(String(a.lastSeen||a.created));
  if(sort==='sla')return slaRatio(b)-slaRatio(a);
  if(sort==='occurrences')return num(b.occurrences)-num(a.occurrences);
  if(sort==='site')return String(siteById(state,a.site)?.name||'').localeCompare(String(siteById(state,b.site)?.name||''));
  const sev={critical:0,high:1,normal:2,low:3},status={open:0,recovery:1,acknowledged:2,triaged:3,ticketed:4,monitoring:5,resolved:6};
  return (sev[a.severity]??4)*100+(status[a.status]??7)*10-slaRatio(a)-( (sev[b.severity]??4)*100+(status[b.status]??7)*10-slaRatio(b));
 });
 return items;
}
function renderTable(){
 const items=filteredAlerts();$('#maintenance-result-count').textContent=`${items.length} alert${items.length===1?'':'s'}`;
 $('#maintenance-table-body').innerHTML=items.map(a=>{const site=siteById(state,a.site),ch=chargerById(state,a.charger),ticket=ticketFor(a),tech=ticket?.technician||'Unassigned';return `<tr data-alert-id="${a.id}"><td><div class="maintenance-alert-title"><strong>${esc(a.id)} · ${esc(a.title)}</strong><span>${esc(a.code)} · ${esc(title(a.source))} · ${esc(a.lastSeen||a.created)}</span></div></td><td><div class="entity-main"><strong>${esc(site?.name||a.site)}</strong><span>${esc(ch?.name||a.charger)}${a.connector?` · ${esc(a.connector)}`:''}</span></div></td><td><div class="entity-main"><strong>${esc(a.customerImpact||'Low')}</strong><span>${num(a.affectedSessions)} affected sessions</span></div></td><td>${num(a.occurrences,1)}</td><td><div class="entity-main"><strong>${esc(slaLabel(a))}</strong><span>${num(a.elapsedMin)} / ${num(a.slaTargetMin)} min</span></div></td><td><div class="entity-main"><strong>${esc(ticket?.id||'No ticket')}</strong><span>${esc(tech)}</span></div></td><td><span class="ui-pill ${priorityClass(a.severity)}">${esc(title(a.severity))}</span></td><td><span class="ui-pill ${statusClass(a.status)}">${esc(title(a.status))}</span></td></tr>`}).join('')||`<tr><td colspan="8">${empty('No maintenance alerts match these filters.')}</td></tr>`;
 $('#maintenance-table-body').querySelectorAll('tr[data-alert-id]').forEach(r=>r.addEventListener('click',()=>openDrawer(r.dataset.alertId)));
}

function sideRow(a,kind='critical'){const site=siteById(state,a.site),ch=chargerById(state,a.charger);return `<button class="maintenance-side-row" type="button" data-alert-open="${a.id}"><span class="maintenance-side-icon maintenance-side-icon--${kind}">${kind==='recovery'?'↻':'!'}</span><div><strong>${esc(a.title)}</strong><span>${esc(site?.name)} · ${esc(ch?.name||a.charger)} · ${esc(a.code)}</span></div><span class="ui-pill ${priorityClass(a.severity)}">${esc(title(a.severity))}</span></button>`}
function renderSides(){
 const critical=state.maintenanceAlerts.filter(a=>unresolved(a)&&['critical','high'].includes(a.severity)).sort((a,b)=>slaRatio(b)-slaRatio(a));
 $('#maintenance-critical-count').textContent=critical.length;$('#maintenance-critical-list').innerHTML=critical.slice(0,5).map(a=>sideRow(a,a.severity)).join('')||empty('No critical maintenance alerts.');
 const recovery=state.maintenanceAlerts.filter(recoveryEligible).sort((a,b)=>(a.recoveryAttempts||[]).length-(b.recoveryAttempts||[]).length).slice(0,5);
 $('#maintenance-recovery-count').textContent=recovery.length;$('#maintenance-recovery-list').innerHTML=recovery.map(a=>sideRow(a,'recovery')).join('')||empty('No alerts require remote recovery.');
 const techs=(state.technicians||[]).map(t=>{const jobs=state.maintenanceTickets.filter(x=>x.technician===t.name&&fieldStatuses.has(x.status));return {...t,jobs:jobs.length};});
 $('#maintenance-technician-count').textContent=techs.length;$('#maintenance-technician-list').innerHTML=techs.map(t=>`<div class="maintenance-technician-row"><span class="maintenance-tech-avatar">${esc(t.name.split(' ').map(x=>x[0]).join('').slice(0,2))}</span><div><strong>${esc(t.name)}</strong><span>${esc(t.region)} · ${(t.skills||[]).slice(0,2).map(esc).join(' / ')}</span></div><span class="ui-pill ${statusClass(t.jobs?'assigned':t.status)}">${t.jobs?`${t.jobs} job${t.jobs===1?'':'s'}`:esc(title(t.status))}</span></div>`).join('')||empty('No technician roster configured.');
 document.querySelectorAll('[data-alert-open]').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.alertOpen)));
}
function render(){renderKpis();renderTable();renderSides();}

function openDrawer(id){if(!alertById(id))return;selectedId=id;drawerTab='overview';renderDrawer();$('#maintenance-drawer-backdrop').hidden=false;requestAnimationFrame(()=>{$('#maintenance-drawer-backdrop').classList.add('is-visible');$('#maintenance-drawer').classList.add('is-open');$('#maintenance-drawer').setAttribute('aria-hidden','false')});}
function closeDrawer(){$('#maintenance-drawer-backdrop').classList.remove('is-visible');$('#maintenance-drawer').classList.remove('is-open');$('#maintenance-drawer').setAttribute('aria-hidden','true');setTimeout(()=>{$('#maintenance-drawer-backdrop').hidden=true},190);selectedId=null;}
function metric(label,value,note=''){return `<div class="maintenance-impact-card"><span>${esc(label)}</span><strong>${esc(value)}</strong>${note?`<small>${esc(note)}</small>`:''}</div>`}
function detail(label,value){return `<div><span>${esc(label)}</span><strong>${esc(value??'—')}</strong></div>`}
function renderOverview(a){const site=siteById(state,a.site),ch=chargerById(state,a.charger),con=connectorById(state,a.connector);return `<div class="maintenance-summary-banner"><div><span class="ui-pill ${priorityClass(a.severity)}">${esc(title(a.severity))}</span><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p></div><div class="maintenance-summary-value"><strong>${esc(a.code)}</strong><span>${num(a.occurrences,1)} occurrence${num(a.occurrences,1)===1?'':'s'}</span></div></div><div class="maintenance-impact-grid">${metric('Customer impact',a.customerImpact||'Low',`${num(a.affectedSessions)} sessions affected`)}${metric('SLA',slaLabel(a),`${num(a.elapsedMin)} / ${num(a.slaTargetMin)} min`)}${metric('Current state',title(a.status),a.owner||'Network Operations')}</div><section class="ui-detail-section"><h3>Affected Infrastructure</h3><div class="ui-detail-grid">${detail('Site',site?.name||a.site)}${detail('Charger',`${ch?.name||a.charger} · ${ch?.model||'—'}`)}${detail('Connector',con?`#${con.number} · ${con.type}`:'Whole charger')}${detail('Source',title(a.source))}</div></section><section class="ui-detail-section"><h3>Probable Causes</h3><div class="maintenance-cause-list">${(a.probableCauses||[]).map((c,i)=>`<div class="maintenance-cause"><strong>${i+1}. ${esc(c)}</strong><span>${i===0?'Highest-probability hypothesis based on current diagnostics.':'Validate during recovery or field service.'}</span></div>`).join('')||empty('No probable causes recorded.')}</div></section><section class="ui-detail-section"><h3>Related Sessions</h3>${sessionsForAlert(a).slice(0,4).map(s=>`<a class="ui-action-card" href="sessions.html?session=${encodeURIComponent(s.id)}"><strong>${esc(s.id)} · ${esc(s.driver)}</strong><span>${esc(title(s.status))} · ${num(s.energyKwh).toFixed(1)} kWh · ${esc(s.connector)}</span></a>`).join('')||empty('No charging sessions linked to this charger/connector.')}</section>`}
function renderDiagnostics(a){const d=a.diagnostics||{},ch=chargerById(state,a.charger),con=connectorById(state,a.connector);return `<section class="ui-detail-section"><h3>Live Diagnostic Snapshot</h3><div class="ui-detail-grid">${detail('Charger health',`${num(d.chargerHealth,ch?.health)}%`)}${detail('Charger temperature',`${num(d.chargerTempC,ch?.temp)} °C`)}${detail('Connector temperature',d.connectorTempC!=null?`${num(d.connectorTempC)} °C`:'—')}${detail('Network latency',d.networkLatencyMs!=null?`${num(d.networkLatencyMs)} ms`:'—')}${detail('Signal',d.signal||ch?.signal||'—')}${detail('Last heartbeat',d.lastHeartbeat||ch?.lastHeartbeat||'—')}${detail('Isolation resistance',d.isolationMohm!=null?`${num(d.isolationMohm)} MΩ`:'—')}${detail('Input voltage',d.inputVoltageV!=null?`${num(d.inputVoltageV)} V`:'—')}${detail('Errors 24h',num(d.errors24h,ch?.errors24h))}${detail('Connector state',con?title(con.status):'Whole charger')}</div></section><section class="ui-detail-section"><h3>Fault Context</h3><div class="ui-callout ${a.severity==='critical'?'ui-callout--danger':'ui-callout--warning'}"><strong>${esc(a.code)} · ${esc(a.title)}</strong><span>${esc(a.body)} First seen ${esc(a.firstSeen||a.created)} · Last seen ${esc(a.lastSeen||a.created)}.</span></div></section><section class="ui-detail-section"><h3>Suggested Diagnostic Path</h3><div class="maintenance-cause-list">${(a.suggestedRecovery||[]).map((x,i)=>`<div class="maintenance-cause"><strong>Step ${i+1}</strong><span>${esc(x)}</span></div>`).join('')||empty('No diagnostic path configured.')}</div></section>`}
function renderRecovery(a){return `<section class="ui-detail-section"><h3>Recommended Remote Actions</h3><div class="maintenance-recovery-action-grid">${(a.suggestedRecovery||[]).map(x=>`<div class="maintenance-recovery-action"><strong>${esc(x)}</strong><span>${a.category==='preventive'?'Field procedure required.':'Operator safety guards apply before execution.'}</span></div>`).join('')||empty('No remote action recommended.')}</div></section><section class="ui-detail-section"><h3>Recovery History</h3><div class="maintenance-recovery-history">${[...(a.recoveryAttempts||[])].reverse().map(r=>`<div class="maintenance-recovery-record"><strong>${esc(r.time)} · ${esc(r.command)} · <span class="ui-pill ${r.result==='Success'?'status-resolved':'status-failed'}">${esc(r.result)}</span></strong><span>${esc(r.detail||'No detail recorded.')}</span></div>`).join('')||empty('No remote recovery attempts yet.')}</div></section>`}
function renderTicket(a){const ticket=ticketFor(a);if(!ticket)return `<section class="ui-detail-section"><h3>Field Service</h3><div class="ui-callout ui-callout--warning"><strong>No maintenance ticket</strong><span>This alert has not yet been handed off to a field technician.</span></div></section>`;const tech=technicianByName(ticket.technician);return `<section class="ui-detail-section"><h3>Maintenance Ticket</h3><div class="maintenance-ticket-card-list"><div class="maintenance-ticket-card"><strong>${esc(ticket.id)} · ${esc(title(ticket.status))}</strong><span>${esc(ticket.description||a.body)}</span></div></div><div class="ui-detail-grid" style="margin-top:10px">${detail('Priority',title(ticket.priority))}${detail('Technician',ticket.technician||'Unassigned')}${detail('ETA',ticket.eta||'Not set')}${detail('Checklist',ticket.checklist||'Not assigned')}</div></section><section class="ui-detail-section"><h3>Technician Context</h3>${tech?`<div class="ui-detail-grid">${detail('Region',tech.region)}${detail('Current status',title(tech.status))}${detail('On call',tech.onCall?'Yes':'No')}${detail('Skills',(tech.skills||[]).join(', '))}</div>`:empty('No technician assigned.')}</section><section class="ui-detail-section"><h3>Parts / Service Preparation</h3><div class="maintenance-cause-list">${(ticket.parts||[]).map(p=>`<div class="maintenance-cause"><strong>${esc(p)}</strong><span>Inspect availability before field replacement.</span></div>`).join('')||empty('No parts currently identified.')}</div></section>`}
function renderTimeline(a){return `<div class="maintenance-timeline">${[...(a.timeline||[])].reverse().map(e=>`<div class="maintenance-timeline-row"><span class="maintenance-timeline-dot maintenance-timeline-dot--${esc(e.type||'info')}"></span><div><div class="maintenance-timeline-head"><strong>${esc(e.title)}</strong><span>${esc(e.time)}</span></div><p>${esc(e.detail||'')}</p></div></div>`).join('')||empty('No alert timeline events.')}</div>`}
function renderDrawer(){const a=alertById(selectedId);if(!a)return;const site=siteById(state,a.site),ch=chargerById(state,a.charger);$('#maintenance-drawer-title').textContent=`${a.id} · ${a.code}`;$('#maintenance-drawer-subtitle').textContent=`${site?.name||a.site} · ${ch?.name||a.charger}`;document.querySelectorAll('[data-maint-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.maintTab===drawerTab));$('#maintenance-drawer-body').innerHTML=drawerTab==='overview'?renderOverview(a):drawerTab==='diagnostics'?renderDiagnostics(a):drawerTab==='recovery'?renderRecovery(a):drawerTab==='ticket'?renderTicket(a):renderTimeline(a);
 const footer=[];if(a.status==='open')footer.push(`<button class="button button--secondary" type="button" data-maint-action="acknowledge">Acknowledge</button>`);if(recoveryEligible(a))footer.push(`<button class="button button--secondary" type="button" data-maint-action="recovery">Remote Recovery</button>`);if(unresolved(a))footer.push(`<button class="button button--secondary" type="button" data-maint-action="ticket">${ticketFor(a)?'Update Ticket':'Create Ticket'}</button>`);if(unresolved(a))footer.push(`<button class="button button--primary" type="button" data-maint-action="resolve">Resolve Alert</button>`);else footer.push(`<button class="button button--primary" type="button" data-maint-action="reopen">Reopen Alert</button>`);$('#maintenance-drawer-footer').innerHTML=footer.join('');$('#maintenance-drawer-footer').querySelectorAll('[data-maint-action]').forEach(b=>b.addEventListener('click',()=>handleAction(b.dataset.maintAction)));}

function commandEligibility(a,cmd){const activeCh=activeSessionOnCharger(a.charger),activeCon=a.connector?activeSessionOnConnector(a.connector):null,ch=chargerById(state,a.charger),con=connectorById(state,a.connector);if(cmd==='reset_connector'&&!con)return [false,'This alert does not target a specific connector.'];if(cmd==='release_cable'&&!con)return [false,'This alert does not target a specific connector.'];if(['reset_connector','release_cable'].includes(cmd)&&activeCon)return [false,`Connector is in active session ${activeCon.id}.`];if(cmd==='restart_charger'&&activeCh)return [false,`Charger is serving active session ${activeCh.id}. Stop the session first.`];if(cmd==='reset_connector'&&a.code==='TEMP-14'&&num(a.diagnostics?.connectorTempC,ch?.temp)>=55)return [false,'Thermal condition is still above the safe reset threshold.'];return [true,cmd==='derate'?`Output will be limited to ${Math.round(num(ch?.maxKw)*.5)} kW until manually restored.`:'Safety checks passed.'];}
function updateRecoveryWarning(){const a=alertById(selectedId);if(!a)return;const [ok,text]=commandEligibility(a,$('#maintenance-recovery-command').value);$('#maintenance-recovery-warning-text').textContent=text;$('#maintenance-recovery-warning').className=`ui-callout ${ok?'ui-callout--warning':'ui-callout--danger'}`;$('#maintenance-recovery-confirm').disabled=!ok;}
function openRecovery(){const a=alertById(selectedId);if(!a)return;$('#maintenance-recovery-subtitle').textContent=`${a.id} · ${a.code} · ${chargerById(state,a.charger)?.name||a.charger}`;$('#maintenance-recovery-note').value='';$('#maintenance-recovery-command').value=a.category==='energy'?'derate':a.connector?'reset_connector':'heartbeat';updateRecoveryWarning();$('#maintenance-recovery-dialog').showModal();}
function executeRecovery(){const a=alertById(selectedId),cmd=$('#maintenance-recovery-command').value;if(!a)return;const [ok,reason]=commandEligibility(a,cmd);if(!ok){showToast(reason);return;}const ch=chargerById(state,a.charger),con=connectorById(state,a.connector),note=$('#maintenance-recovery-note').value.trim();let result='Success',detail='Command completed successfully.';
 if(cmd==='heartbeat'){a.diagnostics={...(a.diagnostics||{}),lastHeartbeat:nowTime()};detail='Heartbeat received and OCPP connection verified.';}
 if(cmd==='reset_connector'){if(a.code==='EVSE-CC-07'&&num(a.occurrences)>=3){result='Failed';detail='Connector reset completed, but EVSE-CC-07 returned.';}else{if(con){con.fault=null;if(!activeSessionOnConnector(con.id))con.status='available';}detail='Connector controller reset and fault state cleared.';}}
 if(cmd==='restart_charger'){if(a.code==='EVSE-CC-07'&&num(a.occurrences)>=3){result='Failed';detail='Charger rebooted, but repeated communication fault returned.';}else{if(ch&&!['blocked','maintenance'].includes(ch.status))ch.status='online';detail='Charger restarted and heartbeat restored.';}}
 if(cmd==='release_cable'){if(con){con.locked=false;if(con.status==='disabled')con.status='available';}detail='Cable lock released successfully.';}
 if(cmd==='derate'){if(ch){ch.operatorDerateKw=Math.round(num(ch.maxKw)*.5);ch.status=ch.status==='faulted'?'warning':ch.status;}detail=`Temporary output limit set to ${ch?.operatorDerateKw||0} kW.`;}
 a.recoveryAttempts=Array.isArray(a.recoveryAttempts)?a.recoveryAttempts:[];a.recoveryAttempts.push({time:nowTime(),command:title(cmd),result,detail:note?`${detail} ${note}`:detail});a.status=result==='Success'?'monitoring':'recovery';a.lastSeen=nowTime();addTimeline(a,result==='Success'?'success':'failed',`${title(cmd)} · ${result}`,note?`${detail} ${note}`:detail);addCommand(title(cmd),a.connector||a.charger,result,`${a.id} · ${detail}`);saveState(state);$('#maintenance-recovery-dialog').close();render();renderDrawer();showToast(`${title(cmd)}: ${result}.`);}

function populateTicketTechnicians(selected=''){const options=[`<option value="">Unassigned</option>`].concat((state.technicians||[]).map(t=>`<option value="${esc(t.name)}" ${t.name===selected?'selected':''}>${esc(t.name)} · ${esc(title(t.status))} · ${esc(t.region)}</option>`));$('#maintenance-ticket-technician').innerHTML=options.join('');}
function openTicketDialog(){const a=alertById(selectedId);if(!a)return;const t=ticketFor(a);$('#maintenance-ticket-subtitle').textContent=`${a.id} · ${chargerById(state,a.charger)?.name||a.charger}`;$('#maintenance-ticket-priority').value=t?.priority||a.severity||'normal';populateTicketTechnicians(t?.technician||'');$('#maintenance-ticket-status').value=t?.status&&fieldStatuses.has(t.status)?t.status:'assigned';$('#maintenance-ticket-eta').value=t?.eta||'';$('#maintenance-ticket-note').value=t?.description||a.body||'';$('#maintenance-ticket-dialog').showModal();}
function saveTicket(){const a=alertById(selectedId);if(!a)return;let t=ticketFor(a),created=false;if(!t){created=true;const id=`MT-${String(Date.now()).slice(-5)}`;t={id,alert:a.id,site:a.site,charger:a.charger,connector:a.connector||null,created:nowTime(),parts:[],timeline:[]};state.maintenanceTickets.unshift(t);a.ticket=id;}const previousTech=t.technician||null;t.priority=$('#maintenance-ticket-priority').value;t.technician=$('#maintenance-ticket-technician').value||null;t.status=t.technician?$('#maintenance-ticket-status').value:'unassigned';t.eta=$('#maintenance-ticket-eta').value||null;t.description=$('#maintenance-ticket-note').value.trim()||a.body;t.checklist=t.checklist||'Charger Fault Diagnosis v1';t.timeline=Array.isArray(t.timeline)?t.timeline:[];t.timeline.push({time:nowTime(),title:created?'Ticket created':'Ticket updated',detail:`${t.technician||'Unassigned'} · ${title(t.status)}${t.eta?` · ETA ${t.eta}`:''}`});a.status='ticketed';addTimeline(a,'ticket',created?`Maintenance ticket ${t.id} created`:`Maintenance ticket ${t.id} updated`,`${t.technician||'Unassigned'} · ${title(t.status)}${previousTech&&previousTech!==t.technician?` · reassigned from ${previousTech}`:''}`);addCommand(created?'Create maintenance ticket':'Update maintenance ticket',t.id,'Success',`${a.id} · ${t.technician||'Unassigned'}`);saveState(state);$('#maintenance-ticket-dialog').close();render();renderDrawer();showToast(`${t.id} ${created?'created':'updated'}.`);}

const statusConfig={acknowledge:{title:'Acknowledge Alert',button:'Acknowledge',text:'Marks the alert as triaged by Network Operations.'},resolve:{title:'Resolve Alert',button:'Resolve Alert',text:'Closes the operational alert. Linked field ticket is not automatically deleted.'},reopen:{title:'Reopen Alert',button:'Reopen Alert',text:'Returns the alert to the open triage queue.'}};
function openStatusAction(action){const a=alertById(selectedId),cfg=statusConfig[action];if(!a||!cfg)return;pendingStatusAction=action;$('#maintenance-status-title').textContent=cfg.title;$('#maintenance-status-subtitle').textContent=`${a.id} · ${a.code}`;$('#maintenance-status-note').value='';$('#maintenance-status-callout-text').textContent=cfg.text;$('#maintenance-status-confirm').textContent=cfg.button;$('#maintenance-status-confirm').className=`button ${action==='resolve'?'button--primary':'button--secondary'}`;$('#maintenance-status-dialog').showModal();}
function confirmStatus(){const a=alertById(selectedId),action=pendingStatusAction,note=$('#maintenance-status-note').value.trim();if(!a||!action)return;if(action==='acknowledge'){a.status='triaged';a.acknowledgedAt=nowTime();a.owner=state.network.operator;addTimeline(a,'recovery','Alert acknowledged',note||`Triaged by ${state.network.operator}.`);addCommand('Acknowledge maintenance alert',a.id,'Success',note);}
 if(action==='resolve'){a.status='resolved';a.resolution=note||'Resolved by Network Operations.';addTimeline(a,'resolved','Alert resolved',a.resolution);const con=connectorById(state,a.connector);if(con&&con.fault===a.code&&!activeSessionOnConnector(con.id)){con.fault=null;if(con.status==='faulted'||con.status==='warning')con.status='available';}const ch=chargerById(state,a.charger);const otherSevere=state.maintenanceAlerts.some(x=>x.id!==a.id&&x.charger===a.charger&&unresolved(x)&&['critical','high'].includes(x.severity));if(ch&&!otherSevere&&!activeSessionOnCharger(ch.id)&&['faulted','warning'].includes(ch.status))ch.status='online';addCommand('Resolve maintenance alert',a.id,'Success',note);}
 if(action==='reopen'){a.status='open';a.resolution=null;a.elapsedMin=0;addTimeline(a,'warning','Alert reopened',note||`Reopened by ${state.network.operator}.`);addCommand('Reopen maintenance alert',a.id,'Success',note);}
 saveState(state);$('#maintenance-status-dialog').close();pendingStatusAction=null;render();renderDrawer();showToast(`${a.id} updated.`);}
function handleAction(action){if(action==='recovery')openRecovery();else if(action==='ticket')openTicketDialog();else openStatusAction(action);}

function updateCreateChargers(){const site=$('#maintenance-create-site').value;const chargers=state.chargers.filter(c=>c.site===site);$('#maintenance-create-charger').innerHTML=chargers.map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.model)}</option>`).join('');updateCreateConnectors();}
function updateCreateConnectors(){const charger=$('#maintenance-create-charger').value;const connectors=state.connectors.filter(c=>c.charger===charger);$('#maintenance-create-connector').innerHTML=`<option value="">Whole charger</option>`+connectors.map(c=>`<option value="${c.id}">Connector ${c.number} · ${esc(c.type)} · ${esc(title(c.status))}</option>`).join('');}
function createManualAlert(){const site=$('#maintenance-create-site').value,charger=$('#maintenance-create-charger').value,connector=$('#maintenance-create-connector').value||null,titleText=$('#maintenance-create-title').value.trim(),body=$('#maintenance-create-body').value.trim();if(!site||!charger||!titleText){showToast('Site, charger and alert title are required.');return;}const id=`AL-${String(Date.now()).slice(-5)}`,severity=$('#maintenance-create-severity').value,code=$('#maintenance-create-code').value.trim()||'OP-REPORT',ch=chargerById(state,charger),con=connectorById(state,connector);const a={id,site,charger,connector,severity,status:'open',code,title:titleText,body:body||'Operator-observed maintenance exception.',created:nowTime(),firstSeen:nowTime(),lastSeen:nowTime(),ticket:null,source:'operator',category:connector?'connector':'charger',occurrences:1,affectedSessions:0,customerImpact:severity==='critical'?'High':severity==='high'?'Medium':'Low',slaTargetMin:slaForSeverity(severity),elapsedMin:0,owner:'Network Operations',probableCauses:['Manual diagnosis required'],suggestedRecovery:['Verify heartbeat and charger communication',connector?'Inspect or reset affected connector':'Restart charger if no active sessions are present'],diagnostics:{chargerHealth:num(ch?.health),chargerTempC:num(ch?.temp),connectorTempC:con?num(con.temp,ch?.temp):null,networkLatencyMs:null,signal:ch?.signal||'Unknown',lastHeartbeat:ch?.lastHeartbeat||nowTime(),errors24h:num(ch?.errors24h)},recoveryAttempts:[],timeline:[{time:nowTime(),type:'warning',title:'Manual alert created',detail:`Created by ${state.network.operator}.`} ]};state.maintenanceAlerts.unshift(a);addCommand('Create manual maintenance alert',id,'Success',`${charger}${connector?` · ${connector}`:''}`);saveState(state);$('#maintenance-create-dialog').close();render();openDrawer(id);showToast(`${id} created.`);}

$('#maintenance-filter-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-maint-filter]');if(!b)return;listFilter=b.dataset.maintFilter;document.querySelectorAll('[data-maint-filter]').forEach(x=>x.classList.toggle('is-active',x===b));renderTable();});
['maintenance-search','maintenance-site','maintenance-severity','maintenance-source','maintenance-sort'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(id==='maintenance-search'?'input':'change',renderTable);});
$('#maintenance-drawer-close').addEventListener('click',closeDrawer);$('#maintenance-drawer-backdrop').addEventListener('click',closeDrawer);$('#maintenance-drawer-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-maint-tab]');if(!b)return;drawerTab=b.dataset.maintTab;renderDrawer();});
$('#maintenance-recovery-command').addEventListener('change',updateRecoveryWarning);$('#maintenance-recovery-close').addEventListener('click',()=>$('#maintenance-recovery-dialog').close());$('#maintenance-recovery-cancel').addEventListener('click',()=>$('#maintenance-recovery-dialog').close());$('#maintenance-recovery-confirm').addEventListener('click',executeRecovery);
$('#maintenance-ticket-close').addEventListener('click',()=>$('#maintenance-ticket-dialog').close());$('#maintenance-ticket-cancel').addEventListener('click',()=>$('#maintenance-ticket-dialog').close());$('#maintenance-ticket-confirm').addEventListener('click',saveTicket);
$('#maintenance-status-close').addEventListener('click',()=>$('#maintenance-status-dialog').close());$('#maintenance-status-cancel').addEventListener('click',()=>$('#maintenance-status-dialog').close());$('#maintenance-status-confirm').addEventListener('click',confirmStatus);
$('#new-maintenance-alert').addEventListener('click',()=>{$('#maintenance-create-title').value='';$('#maintenance-create-body').value='';$('#maintenance-create-code').value='OP-REPORT';updateCreateChargers();$('#maintenance-create-dialog').showModal();});$('#maintenance-create-site').addEventListener('change',updateCreateChargers);$('#maintenance-create-charger').addEventListener('change',updateCreateConnectors);$('#maintenance-create-close').addEventListener('click',()=>$('#maintenance-create-dialog').close());$('#maintenance-create-cancel').addEventListener('click',()=>$('#maintenance-create-dialog').close());$('#maintenance-create-confirm').addEventListener('click',createManualAlert);

populateFilters();render();
const params=new URLSearchParams(location.search);if(params.get('site')){$('#maintenance-site').value=params.get('site');renderTable();}if(params.get('alert'))openDrawer(params.get('alert'));else if(params.get('charger')){const a=state.maintenanceAlerts.find(x=>x.charger===params.get('charger'));if(a)openDrawer(a.id);}
