import {saveState,siteById,chargerById,connectorById} from '../core/operator-state.js';
import {initCommon,showToast} from '../layout/common.js';

let state=initCommon('reservations');
let selectedId=null;
let drawerTab='overview';
let listFilter='all';
let pendingStatusAction=null;

const $=id=>document.getElementById(id);
const money=n=>`${Math.round(Number(n)||0).toLocaleString('en-US')} AMD`;
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const title=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const nowTime=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
const toMinutes=t=>{const [h,m]=String(t||'00:00').split(':').map(Number);return (h||0)*60+(m||0)};
const overlaps=(a,b)=>a.date===b.date&&toMinutes(a.arrival)<toMinutes(b.arrival)+num(b.durationMin)&&toMinutes(b.arrival)<toMinutes(a.arrival)+num(a.durationMin);
const openStatuses=new Set(['confirmed','active']);
const getReservation=id=>state.reservations.find(r=>r.id===id);
const getBay=(site,label)=>state.parkingBays.find(b=>b.site===site&&(b.label===label||b.id===label));
const statusClass=s=>({confirmed:'status-reserved',active:'status-active',waiting:'status-pending',completed:'status-completed',cancelled:'status-cancelled',no_show:'status-failed',online:'status-online',available:'status-available',busy:'status-busy',reserved:'status-reserved',warning:'status-warning',faulted:'status-faulted',offline:'status-offline',maintenance:'status-maintenance',blocked:'status-blocked',disabled:'status-disabled',occupied:'status-occupied'}[s]||'status-maintenance');
const arrivalClass=s=>({arrived:'status-active',waiting:'status-pending',not_arrived:'status-maintenance',no_show:'status-failed',cancelled:'status-cancelled',completed:'status-completed'}[s]||'status-maintenance');
const assignmentLabel=r=>r.assignmentMode==='waiting'?'Waiting list':r.charger?`${chargerById(state,r.charger)?.name||r.charger}${r.bay?` · ${r.bay}`:''}`:r.assignmentMode==='auto'?'Auto assign':'Unassigned';
const reservationSettings=()=>state.operatorSettings?.reservations||{};
const graceStep=()=>Math.max(1,num(reservationSettings().extensionStepMin,5));

function persist(){saveState(state)}
function appendTimeline(r,type,titleText,detail){r.timeline=Array.isArray(r.timeline)?r.timeline:[];r.timeline.push({time:nowTime(),type,title:titleText,detail});}
function logCommand(action,target,result='Success'){state.commandHistory.unshift({id:`CMD-${Date.now()}`,time:nowTime(),action,target,result,operator:state.network.operator});}

function conflictsFor(r,includeOverrides=true){
 if(!openStatuses.has(r.status))return [];
 return state.reservations.filter(o=>o.id!==r.id&&openStatuses.has(o.status)&&o.site===r.site&&overlaps(r,o)&&(
  (r.charger&&o.charger&&r.charger===o.charger)||(r.connector&&o.connector&&r.connector===o.connector)||(r.bay&&o.bay&&r.bay===o.bay)
 )).filter(o=>includeOverrides||(!r.operatorOverride&&!o.operatorOverride));
}
function unresolvedConflicts(){
 const seen=new Set(),rows=[];
 state.reservations.forEach(r=>conflictsFor(r,false).forEach(o=>{const key=[r.id,o.id].sort().join('|');if(!seen.has(key)){seen.add(key);rows.push({a:r,b:o})}}));
 return rows;
}
function releaseAssignment(r){
 const others=state.reservations.filter(o=>o.id!==r.id&&openStatuses.has(o.status));
 if(r.bay){const bay=getBay(r.site,r.bay);if(bay&&bay.reservationId===r.id){bay.status='available';bay.reservationId=null;bay.occupiedBy=null;}}
 if(r.connector&&!others.some(o=>o.connector===r.connector)){const c=connectorById(state,r.connector);if(c&&c.status==='reserved'){c.status='available';c.locked=false;}}
 if(r.charger&&!others.some(o=>o.charger===r.charger)&&!state.sessions.some(s=>s.charger===r.charger&&s.status==='active')){const ch=chargerById(state,r.charger);if(ch&&ch.status==='reserved')ch.status='online';}
}
function applyAssignmentState(r){
 if(!openStatuses.has(r.status))return;
 if(r.bay){const bay=getBay(r.site,r.bay);if(bay&&['available','reserved'].includes(bay.status)){bay.status=r.status==='active'?'occupied':'reserved';bay.reservationId=r.id;bay.occupiedBy=r.status==='active'?r.vehicle:null;}}
 if(r.connector){const c=connectorById(state,r.connector);if(c&&c.status==='available')c.status='reserved';}
 if(r.charger){const ch=chargerById(state,r.charger);if(ch&&ch.status==='online')ch.status='reserved';}
}
function syncAllAssignments(){state.reservations.forEach(applyAssignmentState)}

function populateFilters(){
 $('reservation-site').innerHTML='<option value="all">All sites</option>'+state.sites.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
 $('reservation-create-site').innerHTML=state.sites.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
}
function filteredReservations(){
 const q=$('reservation-search').value.trim().toLowerCase(),site=$('reservation-site').value,mode=$('reservation-assignment').value,sort=$('reservation-sort').value;
 let rows=state.reservations.filter(r=>{
  const hay=[r.id,r.driver,r.vehicle,siteById(state,r.site)?.name,r.charger&&chargerById(state,r.charger)?.name,r.bay].join(' ').toLowerCase();
  const tab=listFilter==='all'||r.status===listFilter||(listFilter==='exception'&&['cancelled','no_show'].includes(r.status));
  return tab&&(site==='all'||r.site===site)&&(mode==='all'||r.assignmentMode===mode)&&(!q||hay.includes(q));
 });
 const attention=r=>conflictsFor(r,false).length*100+(['waiting','no_show'].includes(r.status)?30:0)+(r.status==='active'?10:0);
 rows.sort((a,b)=>sort==='arrival'?toMinutes(a.arrival)-toMinutes(b.arrival):sort==='recent'?String(b.created||'').localeCompare(String(a.created||'')):sort==='site'?(siteById(state,a.site)?.name||'').localeCompare(siteById(state,b.site)?.name||''):attention(b)-attention(a)||toMinutes(a.arrival)-toMinutes(b.arrival));
 return rows;
}

function renderKpis(){
 const upcoming=state.reservations.filter(r=>r.status==='confirmed'),active=state.reservations.filter(r=>r.status==='active'),waiting=state.reservations.filter(r=>r.status==='waiting'),noshow=state.reservations.filter(r=>r.status==='no_show'),conflicts=unresolvedConflicts(),assigned=state.reservations.filter(r=>openStatuses.has(r.status)&&(r.charger||r.bay));
 $('kpi-res-upcoming').textContent=upcoming.length;$('kpi-res-upcoming-note').textContent=`${upcoming.filter(r=>r.charger).length} charger assigned`;
 $('kpi-res-active').textContent=active.length;$('kpi-res-active-note').textContent=`${active.filter(r=>r.arrivalState==='arrived').length} checked in`;
 $('kpi-res-waiting').textContent=waiting.length;$('kpi-res-waiting-note').textContent=waiting.length?'Promotion required':'No queue pressure';
 $('kpi-res-conflicts').textContent=conflicts.length;$('kpi-res-conflicts-note').textContent=conflicts.length?'Operator review required':'No unresolved overlaps';
 $('kpi-res-noshow').textContent=noshow.length;$('kpi-res-noshow-note').textContent='Current reservation set';
 $('kpi-res-assigned').textContent=assigned.length;$('kpi-res-assigned-note').textContent=`${assigned.filter(r=>r.bay).length} parking bays reserved`;
}
function renderTable(){
 const rows=filteredReservations();$('reservation-result-count').textContent=`${rows.length} reservations`;
 $('reservation-table-body').innerHTML=rows.map(r=>{const site=siteById(state,r.site),conflict=conflictsFor(r,false).length>0;return `<tr data-reservation-id="${r.id}" class="${conflict?'reservation-row--conflict':''}"><td><div class="entity-main"><strong>${esc(r.id)} · ${esc(r.driver)}</strong><span>${esc(r.vehicle)}${conflict?' · Conflict':''}</span></div></td><td><div class="entity-main"><strong>${esc(site?.name||r.site)}</strong><span>${esc(r.source||'Mobile app')}</span></div></td><td><div class="entity-main"><strong>${esc(r.arrival||'—')}</strong><span>${num(r.durationMin)} min · +${num(r.graceMin)} min grace</span></div></td><td><div class="entity-main"><strong>${esc(assignmentLabel(r))}</strong><span>${r.connector?esc(r.connector):title(r.assignmentMode)}</span></div></td><td><div class="entity-main"><strong>${num(r.targetSoc)}%</strong><span>${num(r.requestedKwh)} kWh requested</span></div></td><td><div class="entity-main"><strong>${money(r.fee)}</strong><span>${money(r.estimatedCost)} est.</span></div></td><td><span class="ui-pill ${arrivalClass(r.arrivalState)}">${esc(title(r.arrivalState||'not_arrived'))}</span></td><td><span class="ui-pill ${statusClass(r.status)}">${esc(title(r.status))}</span></td></tr>`}).join('')||`<tr><td colspan="8"><div class="reservation-empty">No reservations match the current filters.</div></td></tr>`;
 document.querySelectorAll('[data-reservation-id]').forEach(row=>row.addEventListener('click',()=>openDrawer(row.dataset.reservationId)));
}
function renderSidebars(){
 const waiting=state.reservations.filter(r=>r.status==='waiting').sort((a,b)=>num(a.waitingPosition,99)-num(b.waitingPosition,99));$('waiting-count').textContent=waiting.length;
 $('waiting-list').innerHTML=waiting.map((r,i)=>`<button class="reservation-side-row" type="button" data-open-res="${r.id}"><span class="reservation-side-icon reservation-side-icon--waiting">${i+1}</span><div><strong>${esc(r.driver)}</strong><span>${esc(siteById(state,r.site)?.name)} · ${esc(r.arrival)} · ${num(r.requestedKwh)} kWh</span></div><span class="ui-pill status-pending">Waiting</span></button>`).join('')||'<div class="reservation-empty">Waiting list is clear.</div>';
 const conflicts=unresolvedConflicts();$('conflict-count').textContent=conflicts.length;$('conflict-list').innerHTML=conflicts.map(({a,b})=>`<button class="reservation-side-row" type="button" data-open-res="${a.id}"><span class="reservation-side-icon reservation-side-icon--danger">!</span><div><strong>${esc(a.charger?chargerById(state,a.charger)?.name:a.bay||'Asset conflict')}</strong><span>${esc(a.id)} overlaps ${esc(b.id)} · ${esc(a.arrival)} / ${esc(b.arrival)}</span></div><span class="ui-pill status-critical">Conflict</span></button>`).join('')||'<div class="reservation-empty">No unresolved assignment conflicts.</div>';
 const attention=state.reservations.filter(r=>['confirmed','active','no_show'].includes(r.status)&&(['no_show'].includes(r.arrivalState)||r.operatorOverride||conflictsFor(r,false).length));$('arrival-attention-count').textContent=attention.length;$('arrival-attention-list').innerHTML=attention.map(r=>`<button class="reservation-side-row" type="button" data-open-res="${r.id}"><span class="reservation-side-icon ${r.status==='no_show'?'reservation-side-icon--danger':'reservation-side-icon--warning'}">${r.status==='no_show'?'!':'◷'}</span><div><strong>${esc(r.id)} · ${esc(r.driver)}</strong><span>${r.status==='no_show'?'Grace period expired':r.operatorOverride?'Operator override active':'Assignment conflict'}</span></div><span class="ui-pill ${statusClass(r.status)}">${esc(title(r.status))}</span></button>`).join('')||'<div class="reservation-empty">No arrival exceptions.</div>';
 document.querySelectorAll('[data-open-res]').forEach(el=>el.addEventListener('click',()=>openDrawer(el.dataset.openRes)));
}
function render(){syncAllAssignments();renderKpis();renderTable();renderSidebars();if(selectedId&&$('reservation-drawer').classList.contains('is-open'))renderDrawer();}

function overviewHtml(r){const site=siteById(state,r.site);const conflicts=conflictsFor(r,false);return `<div class="reservation-summary-banner"><div><span class="ui-pill ${statusClass(r.status)}">${esc(title(r.status))}</span><h3>${esc(r.driver)} · ${esc(r.vehicle)}</h3><p>${esc(site?.name||r.site)} · ${esc(r.arrival)} · ${num(r.durationMin)} minutes</p></div><div class="reservation-summary-value"><strong>${num(r.targetSoc)}%</strong><span>Target SOC</span></div></div>${conflicts.length?`<div class="ui-callout ui-callout--danger"><strong>Assignment conflict</strong><span>Overlaps ${conflicts.map(x=>esc(x.id)).join(', ')}. Review assignment before arrival.</span></div>`:''}${r.operatorOverride?`<div class="ui-callout ui-callout--warning"><strong>Operator override active</strong><span>This reservation is allowed to overlap another assignment. Verify operational capacity manually.</span></div>`:''}<section class="ui-detail-section"><h3>Reservation</h3><div class="ui-detail-grid"><div><span>Reservation ID</span><strong>${esc(r.id)}</strong></div><div><span>Source</span><strong>${esc(r.source||'Mobile app')}</strong></div><div><span>Arrival</span><strong>${esc(r.arrival)}</strong></div><div><span>Duration</span><strong>${num(r.durationMin)} min</strong></div><div><span>Arrival State</span><strong><span class="ui-pill ${arrivalClass(r.arrivalState)}">${esc(title(r.arrivalState))}</span></strong></div><div><span>Checked in</span><strong>${esc(r.checkedIn||'—')}</strong></div></div></section><section class="ui-detail-section"><h3>Customer request</h3><div class="ui-detail-grid"><div><span>Target SOC</span><strong>${num(r.targetSoc)}%</strong></div><div><span>Requested Energy</span><strong>${num(r.requestedKwh)} kWh</strong></div><div><span>Access Code</span><strong>${esc(r.accessCode||'—')}</strong></div><div><span>Payment</span><strong>${esc(title(r.paymentStatus||'pending'))}</strong></div></div></section>${r.notes?`<section class="ui-detail-section"><h3>Notes</h3><div class="ui-callout"><strong>Operational context</strong><span>${esc(r.notes)}</span></div></section>`:''}`}
function assignmentHtml(r){const ch=r.charger&&chargerById(state,r.charger),con=r.connector&&connectorById(state,r.connector),bay=r.bay&&getBay(r.site,r.bay);return `<div class="reservation-assignment-grid"><article class="reservation-assignment-card"><span class="reservation-assignment__icon">ϟ</span><div><strong>Charger</strong><span>${esc(ch?`${ch.name} · ${ch.maxKw} kW`:'Not assigned')}</span></div><span class="ui-pill ${ch?statusClass(ch.status):'status-maintenance'}">${esc(ch?title(ch.status):'Pending')}</span></article><article class="reservation-assignment-card"><span class="reservation-assignment__icon">◉</span><div><strong>Connector</strong><span>${esc(con?`${con.type} · ${con.maxKw} kW`:'Not assigned')}</span></div><span class="ui-pill ${con?statusClass(con.status):'status-maintenance'}">${esc(con?title(con.status):'Pending')}</span></article><article class="reservation-assignment-card"><span class="reservation-assignment__icon">▣</span><div><strong>Parking Bay</strong><span>${esc(bay?`${bay.label} · ${title(bay.type)}`:'Not assigned')}</span></div><span class="ui-pill ${bay?statusClass(bay.status):'status-maintenance'}">${esc(bay?title(bay.status):'Pending')}</span></article></div><section class="ui-detail-section"><h3>Assignment policy</h3><div class="ui-detail-grid"><div><span>Mode</span><strong>${esc(title(r.assignmentMode))}</strong></div><div><span>Override</span><strong>${r.operatorOverride?'Enabled':'No'}</strong></div><div><span>Conflicts</span><strong>${conflictsFor(r,false).length}</strong></div><div><span>Site</span><strong>${esc(siteById(state,r.site)?.name||r.site)}</strong></div></div></section>`}
function rulesHtml(r){return `<section class="ui-detail-section"><h3>Grace & cancellation</h3><div class="ui-detail-grid"><div><span>Grace Period</span><strong>${num(r.graceMin)} min</strong></div><div><span>Cancellation Cutoff</span><strong>${num(r.cancellationCutoffMin)} min</strong></div><div><span>Reservation Fee</span><strong>${money(r.fee)}</strong></div><div><span>Estimated Charge</span><strong>${money(r.estimatedCost)}</strong></div></div></section><section class="ui-detail-section"><h3>Payment context</h3><div class="ui-detail-grid"><div><span>Status</span><strong>${esc(title(r.paymentStatus||'pending'))}</strong></div><div><span>Source</span><strong>${esc(r.source||'Mobile app')}</strong></div></div></section><div class="ui-callout ui-callout--warning"><strong>Operator override responsibility</strong><span>Conflicting assignments should only be overridden when physical bay and charger availability has been verified.</span></div>`}
function timelineHtml(r){const rows=[...(r.timeline||[])].reverse();return `<div class="reservation-timeline">${rows.map(e=>`<div class="reservation-timeline-row"><span class="reservation-timeline-dot reservation-timeline-dot--${esc(e.type)}"></span><div><div class="reservation-timeline-head"><strong>${esc(e.title)}</strong><span>${esc(e.time)}</span></div><p>${esc(e.detail)}</p></div></div>`).join('')||'<div class="reservation-empty">No reservation events recorded.</div>'}</div>`}
function renderDrawer(){const r=getReservation(selectedId);if(!r)return closeDrawer();$('reservation-drawer-title').textContent=r.id;$('reservation-drawer-subtitle').textContent=`${r.driver} · ${siteById(state,r.site)?.name||r.site}`;$('reservation-drawer-body').innerHTML=drawerTab==='overview'?overviewHtml(r):drawerTab==='assignment'?assignmentHtml(r):drawerTab==='rules'?rulesHtml(r):timelineHtml(r);document.querySelectorAll('[data-res-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.resTab===drawerTab));
 const actions=[];if(['confirmed','active','waiting'].includes(r.status))actions.push(`<button class="button button--secondary" type="button" data-res-action="assignment">Manage Assignment</button>`);if(r.status==='waiting')actions.push(`<button class="button button--primary" type="button" data-res-action="promote">Promote from Waiting</button>`);if(r.status==='confirmed')actions.push(`<button class="button button--primary" type="button" data-res-action="arrived">Mark Arrived</button><button class="button button--secondary" type="button" data-res-action="grace">+${graceStep()} min Grace</button><button class="button button--danger" type="button" data-res-action="no_show">No-show</button>`);if(r.status==='active')actions.push(`<button class="button button--primary" type="button" data-res-action="complete">Complete Reservation</button>`);if(['confirmed','waiting','active'].includes(r.status))actions.push(`<button class="button button--danger" type="button" data-res-action="cancel">Cancel</button>`);$('reservation-drawer-footer').innerHTML=actions.join('');document.querySelectorAll('[data-res-action]').forEach(b=>b.addEventListener('click',()=>handleAction(b.dataset.resAction)));
}
function openDrawer(id){selectedId=id;drawerTab='overview';$('reservation-drawer').classList.add('is-open');$('reservation-drawer').setAttribute('aria-hidden','false');$('reservation-drawer-backdrop').hidden=false;requestAnimationFrame(()=>$('reservation-drawer-backdrop').classList.add('is-visible'));renderDrawer();}
function closeDrawer(){$('reservation-drawer').classList.remove('is-open');$('reservation-drawer').setAttribute('aria-hidden','true');$('reservation-drawer-backdrop').classList.remove('is-visible');setTimeout(()=>$('reservation-drawer-backdrop').hidden=true,190);selectedId=null;}

function assignmentCandidates(r){
 const chargers=state.chargers.filter(ch=>ch.site===r.site&&!['faulted','maintenance','blocked','offline','disabled'].includes(ch.status));
 return chargers;
}
function fillAssignmentDialog(r){
 const chargers=assignmentCandidates(r);$('reservation-charger').innerHTML='<option value="">Auto / none</option>'+chargers.map(ch=>`<option value="${ch.id}" ${ch.id===r.charger?'selected':''}>${esc(ch.name)} · ${ch.maxKw} kW · ${title(ch.status)}</option>`).join('');
 updateConnectorOptions(r.connector);
 const bays=state.parkingBays.filter(b=>b.site===r.site);$('reservation-bay').innerHTML='<option value="">No specific bay</option>'+bays.map(b=>`<option value="${b.label}" ${b.label===r.bay?'selected':''}>${esc(b.label)} · ${title(b.type)} · ${title(b.status)}</option>`).join('');
 $('reservation-override').value=r.operatorOverride?'yes':'no';$('reservation-assignment-note').value='';updateConflictWarning();
}
function updateConnectorOptions(preselect=''){const charger=$('reservation-charger').value;const cons=state.connectors.filter(c=>c.charger===charger&&!['faulted','maintenance','disabled'].includes(c.status));$('reservation-connector').innerHTML='<option value="">Auto / none</option>'+cons.map(c=>`<option value="${c.id}" ${c.id===preselect?'selected':''}>Connector ${c.number} · ${c.type} · ${c.maxKw} kW · ${title(c.status)}</option>`).join('');updateConflictWarning();}
function prospectiveConflict(r){const tmp={...r,charger:$('reservation-charger').value||null,connector:$('reservation-connector').value||null,bay:$('reservation-bay').value||null};return conflictsFor(tmp,true).length>0;}
function updateConflictWarning(){const r=getReservation(selectedId);if(!r)return;$('reservation-conflict-warning').hidden=!prospectiveConflict(r);}
function openAssignment(){const r=getReservation(selectedId);if(!r)return;fillAssignmentDialog(r);$('reservation-assignment-subtitle').textContent=`${r.id} · ${siteById(state,r.site)?.name}`;$('reservation-assignment-dialog').showModal();}
function saveAssignment(){const r=getReservation(selectedId);if(!r)return;const override=$('reservation-override').value==='yes';if(override&&reservationSettings().allowOperatorOverride===false){showToast('Operator assignment override is disabled in Settings.');return;}if(prospectiveConflict(r)&&!override){showToast('Assignment conflict: enable operator override or select another asset.');return;}releaseAssignment(r);r.charger=$('reservation-charger').value||null;r.connector=$('reservation-connector').value||null;r.bay=$('reservation-bay').value||null;r.operatorOverride=override;r.assignmentMode=r.charger||r.bay?'specific':'auto';const note=$('reservation-assignment-note').value.trim();appendTimeline(r,'assignment','Operator assignment updated',`${assignmentLabel(r)}${override?' · Conflict override enabled':''}${note?` · ${note}`:''}`);applyAssignmentState(r);logCommand('Reservation assignment override',r.id);persist();$('reservation-assignment-dialog').close();render();renderDrawer();showToast('Reservation assignment updated.');}

function findBestAssignment(r){
 const active=state.reservations.filter(o=>o.id!==r.id&&openStatuses.has(o.status));
 const chargers=assignmentCandidates(r);
 for(const ch of chargers){const cons=state.connectors.filter(c=>c.charger===ch.id&&['available','reserved'].includes(c.status));for(const con of cons){const tmp={...r,charger:ch.id,connector:con.id,bay:null,status:'confirmed'};if(!active.some(o=>o.connector===con.id&&overlaps(tmp,o))){const bay=state.parkingBays.find(b=>b.site===r.site&&b.status==='available'&&!active.some(o=>o.bay===b.label&&overlaps({...tmp,bay:b.label},o)));return {charger:ch.id,connector:con.id,bay:bay?.label||null};}}}
 return null;
}
function promoteWaiting(){const r=getReservation(selectedId);if(!r)return;const best=findBestAssignment(r);if(!best){showToast('No conflict-free compatible assignment is available.');return;}r.status='confirmed';r.assignmentMode='specific';r.charger=best.charger;r.connector=best.connector;r.bay=best.bay;r.waitingPosition=null;r.fee=500;r.paymentStatus=r.paymentStatus==='not_required'?'pending':r.paymentStatus;r.accessCode=String(Math.floor(100000+Math.random()*900000));appendTimeline(r,'assignment','Waiting customer promoted',`${chargerById(state,r.charger)?.name} · ${r.bay||'No fixed bay'} assigned by operator.`);applyAssignmentState(r);logCommand('Promote waiting reservation',r.id);persist();render();renderDrawer();showToast('Waiting reservation promoted and assigned.');}

const actionConfig={arrived:{title:'Mark Customer Arrived',button:'Mark Arrived',danger:false,text:'The reservation becomes active and assigned parking is marked occupied.'},no_show:{title:'Mark No-show',button:'Mark No-show',danger:true,text:'The reservation will close and assigned charger/bay capacity will be released.'},cancel:{title:'Cancel Reservation',button:'Cancel Reservation',danger:true,text:'The reservation will be cancelled and assigned assets released.'},complete:{title:'Complete Reservation',button:'Complete',danger:false,text:'The reservation is completed and its allocation is released.'},grace:{title:'Extend Grace Period',button:`Add ${graceStep()} Minutes`,danger:false,text:`Adds ${graceStep()} minutes to the customer arrival grace period.`}};
function openStatusAction(action){const r=getReservation(selectedId),cfg=actionConfig[action];if(!r||!cfg)return;pendingStatusAction=action;$('reservation-status-title').textContent=cfg.title;$('reservation-status-subtitle').textContent=`${r.id} · ${r.driver}`;$('reservation-status-note').value='';$('reservation-status-callout-text').textContent=cfg.text;$('reservation-status-confirm').textContent=cfg.button;$('reservation-status-confirm').className=`button ${cfg.danger?'button--danger':'button--primary'}`;$('reservation-status-dialog').showModal();}
function confirmStatusAction(){const r=getReservation(selectedId),action=pendingStatusAction,note=$('reservation-status-note').value.trim();if(!r||!action)return;
 if(action==='arrived'){r.status='active';r.arrivalState='arrived';r.checkedIn=nowTime();appendTimeline(r,'arrival','Customer checked in',note||'Arrival confirmed by operator.');applyAssignmentState(r);}
 if(action==='no_show'){releaseAssignment(r);r.status='no_show';r.arrivalState='no_show';appendTimeline(r,'no_show','Marked no-show',note||`Grace period of ${r.graceMin} minutes expired.`);}
 if(action==='cancel'){releaseAssignment(r);r.status='cancelled';r.arrivalState='cancelled';if(r.paymentStatus==='paid'&&r.fee>0)r.paymentStatus='refunded';appendTimeline(r,'cancelled','Reservation cancelled',note||'Cancelled by network operator.');}
 if(action==='complete'){releaseAssignment(r);r.status='completed';r.arrivalState='completed';appendTimeline(r,'completed','Reservation completed',note||'Reservation allocation released.');}
 if(action==='grace'){r.graceMin=num(r.graceMin,num(reservationSettings().defaultGraceMin,10))+graceStep();appendTimeline(r,'grace','Grace period extended',`${r.graceMin} minutes total${note?` · ${note}`:''}`);}
 logCommand(`Reservation ${action.replace('_',' ')}`,r.id);persist();$('reservation-status-dialog').close();pendingStatusAction=null;render();renderDrawer();showToast(`${r.id} updated.`);
}
function handleAction(action){if(action==='assignment')openAssignment();else if(action==='promote')promoteWaiting();else openStatusAction(action);}

function createReservation(){const driver=$('reservation-create-driver').value.trim(),vehicle=$('reservation-create-vehicle').value.trim(),site=$('reservation-create-site').value,arrival=$('reservation-create-arrival').value,mode=$('reservation-create-mode').value;if(!driver||!vehicle||!site||!arrival){showToast('Customer, vehicle, site and arrival are required.');return;}const id=`RSV-${String(Date.now()).slice(-5)}`,duration=num($('reservation-create-duration').value,45),kwh=num($('reservation-create-kwh').value,30),target=num($('reservation-create-target').value,80);const r={id,driver,vehicle,site,date:'2026-08-17',created:nowTime(),arrival,durationMin:duration,status:mode==='waiting'?'waiting':'confirmed',assignmentMode:mode,charger:null,connector:null,bay:null,targetSoc:target,requestedKwh:kwh,graceMin:num(reservationSettings().defaultGraceMin,10),cancellationCutoffMin:num(reservationSettings().cancellationCutoffMin,30),fee:mode==='waiting'?0:500,estimatedCost:kwh*145+(mode==='waiting'?0:500),paymentStatus:mode==='waiting'?'not_required':'pending',arrivalState:mode==='waiting'?'waiting':'not_arrived',accessCode:mode==='waiting'?null:String(Math.floor(100000+Math.random()*900000)),source:'Operator',waitingPosition:mode==='waiting'?state.reservations.filter(x=>x.status==='waiting').length+1:null,notes:$('reservation-create-note').value.trim(),operatorOverride:false,timeline:[{time:nowTime(),type:'created',title:'Operator reservation created',detail:`Created by ${state.network.operator}.`} ]};state.reservations.unshift(r);logCommand('Create operator reservation',id);persist();$('reservation-create-dialog').close();render();openDrawer(id);if(mode==='specific')setTimeout(openAssignment,100);showToast('Operator reservation created.');}

$('reservation-filter-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-res-filter]');if(!b)return;listFilter=b.dataset.resFilter;document.querySelectorAll('[data-res-filter]').forEach(x=>x.classList.toggle('is-active',x===b));renderTable();});
['reservation-search','reservation-site','reservation-assignment','reservation-sort'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(id==='reservation-search'?'input':'change',renderTable);});
$('reservation-drawer-close').addEventListener('click',closeDrawer);$('reservation-drawer-backdrop').addEventListener('click',closeDrawer);$('reservation-drawer-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-res-tab]');if(!b)return;drawerTab=b.dataset.resTab;renderDrawer();});
$('reservation-charger').addEventListener('change',()=>updateConnectorOptions());$('reservation-connector').addEventListener('change',updateConflictWarning);$('reservation-bay').addEventListener('change',updateConflictWarning);$('reservation-override').addEventListener('change',updateConflictWarning);$('reservation-assignment-close').addEventListener('click',()=>$('reservation-assignment-dialog').close());$('reservation-assignment-cancel').addEventListener('click',()=>$('reservation-assignment-dialog').close());$('reservation-assignment-confirm').addEventListener('click',saveAssignment);
$('reservation-status-close').addEventListener('click',()=>$('reservation-status-dialog').close());$('reservation-status-cancel').addEventListener('click',()=>$('reservation-status-dialog').close());$('reservation-status-confirm').addEventListener('click',confirmStatusAction);
$('new-reservation').addEventListener('click',()=>{$('reservation-create-driver').value='';$('reservation-create-vehicle').value='';$('reservation-create-mode').value='auto';$('reservation-create-note').value='';$('reservation-create-dialog').showModal();});$('reservation-create-close').addEventListener('click',()=>$('reservation-create-dialog').close());$('reservation-create-cancel').addEventListener('click',()=>$('reservation-create-dialog').close());$('reservation-create-confirm').addEventListener('click',createReservation);

populateFilters();render();
const params=new URLSearchParams(location.search);if(params.get('reservation'))openDrawer(params.get('reservation'));if(params.get('site')){$('reservation-site').value=params.get('site');renderTable();}
