import {initCommon,showToast} from '../layout/common.js';
import {saveState,siteById,chargerById,sessionById} from '../core/operator-state.js';

let state=initCommon('revenue');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
const fmt=n=>new Intl.NumberFormat('en-US').format(Math.round(num(n)));
const money=n=>`${fmt(n)} AMD`;
const nowTime=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
const statusClass=v=>`status-${String(v||'').toLowerCase().replace(/[_\s]+/g,'-')}`;
const attentionStatuses=new Set(['pending','failed']);
let filterMode='all',currentTransactionId=null,currentTab='overview',currentSettlementId=null;

function ensureCollections(){
 state.financialTransactions=Array.isArray(state.financialTransactions)?state.financialTransactions:[];
 state.refunds=Array.isArray(state.refunds)?state.refunds:[];
 state.roamingSettlements=Array.isArray(state.roamingSettlements)?state.roamingSettlements:[];
 state.tariffs=Array.isArray(state.tariffs)?state.tariffs:[];
 state.revenueDaily=Array.isArray(state.revenueDaily)?state.revenueDaily:[];
 state.revenueBySite=Array.isArray(state.revenueBySite)?state.revenueBySite:[];
 state.financialTransactions.forEach(tx=>{tx.timeline=Array.isArray(tx.timeline)?tx.timeline:[];tx.gross=num(tx.gross);tx.providerFee=num(tx.providerFee);tx.tax=num(tx.tax);tx.net=num(tx.net,tx.gross-tx.providerFee-tx.tax);tx.refundedAmount=num(tx.refundedAmount)});
}
ensureCollections();
function txById(id){return state.financialTransactions.find(x=>x.id===id)}
function refundById(id){return state.refunds.find(x=>x.id===id)}
function settlementById(id){return state.roamingSettlements.find(x=>x.id===id)}
function reservationById(id){return state.reservations.find(x=>x.id===id)}
function addCommand(action,target,result='Success',note=''){state.commandHistory.unshift({id:`CMD-${Date.now()}-${Math.floor(Math.random()*90+10)}`,time:nowTime(),action,target,result,operator:state.network.operator,note})}
function addTimeline(tx,title,detail){tx.timeline.push({time:nowTime(),title,detail})}
function syncRevenueMeta(){const agg=aggregateToday();state.revenue={...(state.revenue||{}),today:agg.total,failedPayments:state.financialTransactions.filter(tx=>tx.status==='failed').length,refunds:state.refunds.filter(r=>r.status==='completed').length};}
function persist(message,keepDrawer=true){syncRevenueMeta();saveState(state);render();if(keepDrawer&&currentTransactionId)renderDrawer();if(message)showToast(message)}
function transactionAttention(tx){return attentionStatuses.has(tx.status)||tx.status==='preauthorized'&&sessionById(state,tx.session)?.status!=='active'}
function paymentLabel(tx){if(tx.roaming&&tx.status==='pending')return 'Partner settlement';return tx.paymentMethod||tx.provider||'Payment'}
function statusTone(status){return ({captured:'status-online',paid:'status-online',pending:'status-warning',failed:'status-critical',refunded:'status-maintenance','partially_refunded':'status-warning',preauthorized:'status-reserved'}[status]||statusClass(status))}
function typeTone(type){return ({charging:'status-active',reservation:'status-reserved',idle:'status-warning',parking:'status-monitoring',adjustment:'status-maintenance'}[type]||'status-maintenance')}

function populateFilters(){
 const sel=$('#revenue-site');
 if(sel.options.length===1)sel.insertAdjacentHTML('beforeend',state.sites.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join(''));
}
function aggregateToday(){
 const r=state.revenue||{};
 const energy=num(r.energy),reservations=num(r.reservations),idle=num(r.idle),parking=num(r.parking),other=num(r.other);
 return {energy,reservations,idle,parking,other,total:energy+reservations+idle+parking+other};
}
function renderKpis(){
 const agg=aggregateToday(),fees=agg.reservations+agg.idle+agg.parking+agg.other;
 const attention=state.financialTransactions.filter(transactionAttention),completedRefunds=state.refunds.filter(r=>r.status==='completed'),refundTotal=completedRefunds.reduce((a,r)=>a+num(r.amount),0);
 const roamingOpen=state.roamingSettlements.filter(s=>s.status!=='reconciled'),roamingReceivable=roamingOpen.reduce((a,s)=>a+num(s.operatorReceivable),0);
 $('#kpi-revenue-today').textContent=money(agg.total);$('#kpi-revenue-today-note').textContent=`${fmt(state.revenue?.transactions||68)} network transactions`;
 $('#kpi-revenue-energy').textContent=money(agg.energy);$('#kpi-revenue-energy-note').textContent=`${agg.total?Math.round(agg.energy/agg.total*100):0}% of today's revenue`;
 $('#kpi-revenue-fees').textContent=money(fees);$('#kpi-revenue-fees-note').textContent='Reservation + idle + parking + other';
 $('#kpi-revenue-attention').textContent=attention.length;$('#kpi-revenue-attention-note').textContent=`${attention.filter(x=>x.status==='failed').length} failed · ${attention.filter(x=>x.status==='pending').length} pending`;
 $('#kpi-revenue-refunds').textContent=money(refundTotal);$('#kpi-revenue-refunds-note').textContent=`${completedRefunds.length} completed · ${state.refunds.filter(r=>r.status==='review').length} in review`;
 $('#kpi-revenue-roaming').textContent=money(roamingReceivable);$('#kpi-revenue-roaming-note').textContent=`${roamingOpen.length} settlement batches open`;
 $('#revenue-nav-badge').textContent=attention.length;$('#revenue-nav-badge').style.display=attention.length?'':'none';
}
function attentionScore(tx){let score=100;if(tx.status==='failed')score-=80;if(tx.status==='pending')score-=60;if(tx.status==='preauthorized')score-=20;if(tx.roaming&&tx.status!=='captured')score-=10;if(tx.status==='refunded')score+=20;return score}
function filteredTransactions(){
 const q=$('#revenue-search').value.trim().toLowerCase(),site=$('#revenue-site').value,type=$('#revenue-type').value,sort=$('#revenue-sort').value;
 let list=state.financialTransactions.filter(tx=>{
  const st=siteById(state,tx.site),ch=chargerById(state,tx.charger);const hay=[tx.id,tx.customer,tx.reference,tx.session,tx.reservation,st?.name,ch?.name,tx.provider,tx.paymentMethod,tx.roamingPartner].join(' ').toLowerCase();
  if(q&&!hay.includes(q))return false;if(site!=='all'&&tx.site!==site)return false;if(type!=='all'&&tx.type!==type)return false;
  if(filterMode==='captured'&&tx.status!=='captured')return false;if(filterMode==='attention'&&!transactionAttention(tx))return false;if(filterMode==='roaming'&&!tx.roaming)return false;if(filterMode==='refunds'&&!['refunded','partially_refunded'].includes(tx.status))return false;return true;
 });
 const sorters={attention:(a,b)=>attentionScore(a)-attentionScore(b),recent:(a,b)=>(`${b.date} ${b.time}`).localeCompare(`${a.date} ${a.time}`),amount:(a,b)=>num(b.gross)-num(a.gross),site:(a,b)=>String(siteById(state,a.site)?.name||'').localeCompare(String(siteById(state,b.site)?.name||''))};
 return list.sort(sorters[sort]||sorters.attention);
}
function renderTable(){
 const list=filteredTransactions();$('#revenue-result-count').textContent=`${list.length} transactions`;
 $('#revenue-table-body').innerHTML=list.map(tx=>{const st=siteById(state,tx.site),ch=chargerById(state,tx.charger),fee=num(tx.providerFee)+num(tx.tax);return `<tr data-revenue-row="${tx.id}" class="${transactionAttention(tx)?'revenue-row--attention':''}"><td><div class="entity-main"><strong>${esc(tx.id)}</strong><span>${esc(tx.date)} · ${esc(tx.time)}${tx.reference?` · ${esc(tx.reference)}`:''}</span></div></td><td><div class="entity-main"><strong>${esc(tx.customer||'Customer')}</strong><span>${esc(tx.accountType||'Personal')}${tx.roaming?` · ${esc(tx.roamingPartner||'Roaming')}`:''}</span></div></td><td><div class="entity-main"><strong>${esc(st?.name||tx.site||'—')}</strong><span>${esc(ch?.name||tx.charger||tx.reservation||'Network')}</span></div></td><td><span class="ui-pill ${typeTone(tx.type)}">${esc(tx.type)}</span></td><td>${money(tx.gross)}</td><td><div class="revenue-money-cell"><strong>${money(fee)}</strong><span>${money(tx.tax)} tax</span></div></td><td>${money(tx.net)}</td><td><div class="entity-main"><strong>${esc(paymentLabel(tx))}</strong><span>${esc(tx.provider||'—')}</span></div></td><td><span class="ui-pill ${statusTone(tx.status)}">${esc(tx.status.replace('_',' '))}</span></td></tr>`}).join('')||`<tr><td colspan="9"><div class="revenue-empty">No transactions match the current filters.</div></td></tr>`;
 $$('[data-revenue-row]').forEach(row=>row.addEventListener('click',()=>openTransaction(row.dataset.revenueRow)));
}
function renderSitePerformance(){
 const max=Math.max(1,...state.revenueBySite.map(r=>num(r.energy)+num(r.reservations)+num(r.idle)+num(r.parking)+num(r.other)));
 $('#revenue-site-performance').innerHTML=`<div class="revenue-site-grid">${state.revenueBySite.map(r=>{const st=siteById(state,r.site),total=num(r.energy)+num(r.reservations)+num(r.idle)+num(r.parking)+num(r.other);return `<button class="revenue-site-card" type="button" data-revenue-site="${r.site}"><div class="revenue-site-card__head"><div><strong>${esc(st?.name||r.site)}</strong><span>${fmt(r.transactions)} transactions · ${fmt(r.failed)} failed</span></div><strong>${money(total)}</strong></div><div class="revenue-site-track"><span style="width:${Math.max(5,total/max*100)}%"></span></div><div class="revenue-site-split"><span>Energy ${money(r.energy)}</span><span>Fees ${money(total-r.energy)}</span></div></button>`}).join('')}</div>`;
 $$('[data-revenue-site]').forEach(btn=>btn.addEventListener('click',()=>{$('#revenue-site').value=btn.dataset.revenueSite;renderTable();document.querySelector('.revenue-table')?.scrollIntoView({behavior:'smooth',block:'start'})}));
}
function renderTrend(){
 const list=state.revenueDaily,max=Math.max(1,...list.map(x=>num(x.total))),total=list.reduce((a,x)=>a+num(x.total),0);$('#revenue-trend-total').textContent=money(total);
 $('#revenue-trend').innerHTML=`<div class="revenue-trend-chart">${list.map(d=>`<div class="revenue-trend-row"><span>${esc(d.date.slice(5))}</span><div class="revenue-trend-bar"><i style="width:${Math.max(4,num(d.total)/max*100)}%"></i></div><strong>${money(d.total)}</strong><small>Energy ${money(d.energy)}</small></div>`).join('')}</div>`;
}
function renderAttention(){
 const list=state.financialTransactions.filter(transactionAttention).sort((a,b)=>attentionScore(a)-attentionScore(b));$('#payment-attention-count').textContent=list.length;
 $('#payment-attention-list').innerHTML=list.length?list.map(tx=>`<button class="revenue-side-row" type="button" data-attention-tx="${tx.id}"><span class="revenue-side-icon ${tx.status==='failed'?'revenue-side-icon--critical':'revenue-side-icon--warning'}">!</span><div><strong>${esc(tx.id)} · ${esc(tx.customer)}</strong><span>${esc(tx.failureReason||`${tx.status} payment`)} · ${money(tx.gross)}</span></div><span class="ui-pill ${statusTone(tx.status)}">${esc(tx.status)}</span></button>`).join(''):`<div class="revenue-empty">No payment exceptions.</div>`;
 $$('[data-attention-tx]').forEach(b=>b.addEventListener('click',()=>openTransaction(b.dataset.attentionTx)));
}
function renderRefunds(){
 const list=[...state.refunds].sort((a,b)=>(`${b.date} ${b.time}`).localeCompare(`${a.date} ${a.time}`));$('#refund-count').textContent=list.length;
 $('#refund-list').innerHTML=list.length?list.map(r=>`<button class="revenue-side-row" type="button" data-refund-id="${r.id}"><span class="revenue-side-icon">↶</span><div><strong>${esc(r.id)} · ${esc(r.customer)}</strong><span>${money(r.amount)} · ${esc(r.reason)} · ${esc(r.note||'')}</span></div><span class="ui-pill ${statusTone(r.status==='completed'?'captured':'pending')}">${esc(r.status)}</span></button>`).join(''):`<div class="revenue-empty">No refunds.</div>`;
 $$('[data-refund-id]').forEach(b=>b.addEventListener('click',()=>{const r=refundById(b.dataset.refundId);if(r?.transaction)openTransaction(r.transaction)}));
}
function renderRoaming(){
 const list=state.roamingSettlements;$('#roaming-count').textContent=list.length;
 $('#roaming-list').innerHTML=list.map(s=>`<button class="revenue-side-row" type="button" data-roaming-id="${s.id}"><span class="revenue-side-icon revenue-side-icon--roaming">⇄</span><div><strong>${esc(s.partner)}</strong><span>${fmt(s.sessions)} sessions · ${money(s.operatorReceivable)} receivable${num(s.variance)?` · variance ${money(s.variance)}`:''}</span></div><span class="ui-pill ${s.status==='reconciled'?'status-online':s.status==='attention'?'status-critical':'status-warning'}">${esc(s.status)}</span></button>`).join('');
 $$('[data-roaming-id]').forEach(b=>b.addEventListener('click',()=>openSettlement(b.dataset.roamingId)));
}
function renderTariffs(){
 $('#tariff-count').textContent=state.tariffs.length;
 $('#tariff-list').innerHTML=state.tariffs.map(t=>`<div class="revenue-tariff-row"><span class="revenue-side-icon">¤</span><div><strong>${esc(t.name)}</strong><span>${fmt(t.energyRate)} AMD/kWh · connection ${money(t.connectionFee)} · idle ${fmt(t.idleRate)} AMD/min</span></div><span class="ui-pill status-online">${esc(t.status)}</span></div>`).join('');
}
function render(){renderKpis();renderTable();renderSitePerformance();renderTrend();renderAttention();renderRefunds();renderRoaming();renderTariffs()}

function closeDrawer(){currentTransactionId=null;$('#revenue-drawer').classList.remove('is-open');$('#revenue-drawer').setAttribute('aria-hidden','true');$('#revenue-drawer-backdrop').classList.remove('is-visible');$('#revenue-drawer-backdrop').hidden=true}
function openTransaction(id){const tx=txById(id);if(!tx)return;currentTransactionId=id;currentTab='overview';$('#revenue-drawer-title').textContent=tx.id;$('#revenue-drawer-subtitle').textContent=`${tx.customer||'Customer'} · ${money(tx.gross)} · ${tx.status}`;$$('[data-revenue-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.revenueTab==='overview'));renderDrawer();$('#revenue-drawer-backdrop').hidden=false;requestAnimationFrame(()=>$('#revenue-drawer-backdrop').classList.add('is-visible'));$('#revenue-drawer').classList.add('is-open');$('#revenue-drawer').setAttribute('aria-hidden','false')}
function renderDrawer(){const tx=txById(currentTransactionId);if(!tx)return;const st=siteById(state,tx.site),ch=chargerById(state,tx.charger),s=tx.session?sessionById(state,tx.session):null,r=tx.reservation?reservationById(tx.reservation):null;$('#revenue-drawer-body').innerHTML=currentTab==='overview'?drawerOverview(tx,st,ch):currentTab==='fees'?drawerFees(tx):currentTab==='payment'?drawerPayment(tx):currentTab==='related'?drawerRelated(tx,st,ch,s,r):drawerTimeline(tx);renderDrawerFooter(tx)}
function drawerOverview(tx,st,ch){return `<section class="revenue-summary-banner"><div><span class="eyebrow">${esc(tx.type)} transaction</span><h3>${esc(tx.customer||'Customer')}</h3><p>${esc(st?.name||tx.site||'Network')} · ${esc(ch?.name||tx.charger||'No charger')} · ${esc(tx.date)} ${esc(tx.time)}</p></div><div class="revenue-summary-value"><strong>${money(tx.gross)}</strong><span class="ui-pill ${statusTone(tx.status)}">${esc(tx.status.replace('_',' '))}</span></div></section><section class="ui-detail-section"><h3>Transaction details</h3><div class="ui-detail-grid"><div><span>Transaction</span><strong>${esc(tx.id)}</strong></div><div><span>Reference</span><strong>${esc(tx.reference||'—')}</strong></div><div><span>Type</span><strong>${esc(tx.type)}</strong></div><div><span>Account</span><strong>${esc(tx.accountType||'Personal')}</strong></div><div><span>Gross</span><strong>${money(tx.gross)}</strong></div><div><span>Net revenue</span><strong>${money(tx.net)}</strong></div></div></section>${tx.failureReason?`<section class="ui-detail-section"><div class="ui-callout ui-callout--warning"><strong>Payment context</strong><span>${esc(tx.failureReason)}</span></div></section>`:''}${tx.roaming?`<section class="ui-detail-section"><div class="ui-callout"><strong>Roaming transaction</strong><span>${esc(tx.roamingPartner||tx.provider)} · settlement may be finalized separately from the customer CDR.</span></div></section>`:''}`}
function drawerFees(tx){const retained=Math.max(0,num(tx.gross)-num(tx.refundedAmount));return `<section class="ui-detail-section"><h3>Financial breakdown</h3><div class="ui-detail-grid"><div><span>Gross customer charge</span><strong>${money(tx.gross)}</strong></div><div><span>Payment/provider fee</span><strong>${money(tx.providerFee)}</strong></div><div><span>Tax component</span><strong>${money(tx.tax)}</strong></div><div><span>Net operator revenue</span><strong>${money(tx.net)}</strong></div><div><span>Refunded</span><strong>${money(tx.refundedAmount)}</strong></div><div><span>Customer amount retained</span><strong>${money(retained)}</strong></div></div></section><section class="ui-detail-section"><div class="revenue-fee-formula"><span>Gross</span><strong>${money(tx.gross)}</strong><i>−</i><span>Provider fee</span><strong>${money(tx.providerFee)}</strong><i>−</i><span>Tax</span><strong>${money(tx.tax)}</strong><i>=</i><span>Net</span><strong>${money(tx.net)}</strong></div></section>`}
function drawerPayment(tx){return `<section class="ui-detail-section"><h3>Payment processing</h3><div class="ui-detail-grid"><div><span>Status</span><strong><span class="ui-pill ${statusTone(tx.status)}">${esc(tx.status.replace('_',' '))}</span></strong></div><div><span>Payment method</span><strong>${esc(tx.paymentMethod||'—')}</strong></div><div><span>Provider</span><strong>${esc(tx.provider||'—')}</strong></div><div><span>Reference</span><strong>${esc(tx.reference||'—')}</strong></div><div><span>Retry permitted</span><strong>${tx.retryable?'Yes':'No'}</strong></div><div><span>Roaming</span><strong>${tx.roaming?esc(tx.roamingPartner||'Yes'):'No'}</strong></div></div></section>${transactionAttention(tx)?`<section class="ui-detail-section"><div class="ui-callout ui-callout--warning"><strong>Operator attention required</strong><span>${esc(tx.failureReason||'Payment settlement has not reached a final state.')}</span></div></section>`:''}`}
function drawerRelated(tx,st,ch,s,r){return `<section class="ui-detail-section"><h3>Related operational records</h3><div class="revenue-related-list">${st?`<a class="ui-action-card" href="sites.html?site=${encodeURIComponent(st.id)}"><span class="revenue-related-icon">◇</span><div><strong>${esc(st.name)}</strong><span>Open Site operational profile</span></div></a>`:''}${ch?`<a class="ui-action-card" href="chargers.html?charger=${encodeURIComponent(ch.id)}"><span class="revenue-related-icon">ϟ</span><div><strong>${esc(ch.name)} · ${esc(ch.id)}</strong><span>Open Charger details</span></div></a>`:''}${s?`<a class="ui-action-card" href="sessions.html?session=${encodeURIComponent(s.id)}"><span class="revenue-related-icon">◉</span><div><strong>${esc(s.id)}</strong><span>${esc(s.driver)} · ${num(s.energyKwh).toFixed(1)} kWh · ${esc(s.status)}</span></div></a>`:''}${r?`<a class="ui-action-card" href="reservations.html?reservation=${encodeURIComponent(r.id)}"><span class="revenue-related-icon">▣</span><div><strong>${esc(r.id)}</strong><span>${esc(r.driver)} · ${esc(r.status)}</span></div></a>`:''}${!st&&!ch&&!s&&!r?'<div class="revenue-empty">No linked operational record.</div>':''}</div></section>`}
function drawerTimeline(tx){const list=[...(tx.timeline||[])].reverse();return `<section class="ui-detail-section"><h3>Financial timeline</h3><div class="revenue-timeline">${list.length?list.map(e=>`<div class="revenue-timeline-row"><span class="revenue-timeline-dot"></span><div><div><strong>${esc(e.title)}</strong><span>${esc(e.time)}</span></div><p>${esc(e.detail)}</p></div></div>`).join(''):'<div class="revenue-empty">No financial events recorded.</div>'}</div></section>`}
function renderDrawerFooter(tx){const actions=[];if(tx.status==='failed'&&tx.retryable)actions.push(`<button class="button button--primary" type="button" data-tx-retry>Retry Payment</button>`);if(tx.status==='pending'&&!tx.roaming)actions.push(`<button class="button button--primary" type="button" data-tx-capture>Capture Settlement</button>`);if(['captured','partially_refunded'].includes(tx.status)&&num(tx.gross)-num(tx.refundedAmount)>0)actions.push(`<button class="button button--secondary" type="button" data-tx-refund>Issue Refund</button>`);if(tx.roaming)actions.push(`<button class="button button--secondary" type="button" data-tx-roaming>Roaming Settlement</button>`);$('#revenue-drawer-footer').innerHTML=actions.join('')||`<span class="drawer-footer-note">No operator action required.</span>`;
 $('[data-tx-retry]')?.addEventListener('click',()=>retryPayment(tx));$('[data-tx-capture]')?.addEventListener('click',()=>capturePayment(tx));$('[data-tx-refund]')?.addEventListener('click',()=>openRefundDialog(tx.id));$('[data-tx-roaming]')?.addEventListener('click',()=>{const set=state.roamingSettlements.find(x=>x.partner===(tx.roamingPartner||tx.provider));if(set)openSettlement(set.id);else showToast('No settlement batch found for this partner')});
}
function retryPayment(tx){if(tx.status!=='failed'||!tx.retryable)return;tx.status='captured';tx.failureReason=null;addTimeline(tx,'Payment retry captured','Operator retry succeeded and payment reached final captured state.');addCommand('Retry payment',tx.id,'Success',money(tx.gross));persist(`Payment ${tx.id} captured after retry`)}
function capturePayment(tx){if(tx.status!=='pending'||tx.roaming)return;tx.status='captured';tx.failureReason=null;addTimeline(tx,'Settlement captured','Operator reconciliation finalized the pending payment.');const s=tx.session?sessionById(state,tx.session):null;if(s&&s.payment==='pending')s.payment='paid';addCommand('Capture settlement',tx.id,'Success',money(tx.gross));persist(`Settlement ${tx.id} captured`)}

function openRefundDialog(id,amount=null){const tx=txById(id);if(!tx)return;currentTransactionId=id;const available=Math.max(0,num(tx.gross)-num(tx.refundedAmount));$('#revenue-refund-subtitle').textContent=`${tx.id} · ${tx.customer} · up to ${money(available)}`;$('#revenue-refund-amount').max=String(available);$('#revenue-refund-amount').value=String(Math.min(available,amount??available));$('#revenue-refund-note').value='';$('#revenue-refund-dialog').showModal()}
function closeRefund(){$('#revenue-refund-dialog').close()}
$('#revenue-refund-close').addEventListener('click',closeRefund);$('#revenue-refund-cancel').addEventListener('click',closeRefund);
$('#revenue-refund-confirm').addEventListener('click',()=>{const tx=txById(currentTransactionId);if(!tx)return;const available=Math.max(0,num(tx.gross)-num(tx.refundedAmount)),amount=num($('#revenue-refund-amount').value),reason=$('#revenue-refund-reason').value,note=$('#revenue-refund-note').value.trim();if(!amount||amount<=0||amount>available){showToast(`Refund must be between 1 and ${fmt(available)} AMD`);return}let refund=state.refunds.find(r=>r.transaction===tx.id&&r.status==='review');const id=refund?.id||`RF-${String(Date.now()).slice(-7)}`;tx.refundedAmount=num(tx.refundedAmount)+amount;tx.status=tx.refundedAmount>=tx.gross?'refunded':'partially_refunded';if(refund){Object.assign(refund,{date:'2026-08-17',time:nowTime(),amount,reason,status:'completed',customer:tx.customer,operator:state.network.operator,note:note||reason})}else state.refunds.unshift({id,transaction:tx.id,date:'2026-08-17',time:nowTime(),amount,reason,status:'completed',customer:tx.customer,operator:state.network.operator,note:note||reason});addTimeline(tx,'Refund completed',`${money(amount)} · ${reason}${note?` · ${note}`:''}`);addCommand('Issue refund',tx.id,'Success',`${money(amount)} · ${reason}`);syncRevenueMeta();saveState(state);closeRefund();persist(`Refund ${id} completed`)});

function openReconcile(){$('#revenue-reconcile-note').value='';$('#revenue-reconcile-dialog').showModal()}
function closeReconcile(){$('#revenue-reconcile-dialog').close()}
$('#revenue-reconcile').addEventListener('click',openReconcile);$('#revenue-reconcile-close').addEventListener('click',closeReconcile);$('#revenue-reconcile-cancel').addEventListener('click',closeReconcile);
$('#revenue-reconcile-confirm').addEventListener('click',()=>{const scope=$('#revenue-reconcile-scope').value,note=$('#revenue-reconcile-note').value.trim();let processed=0,skipped=0;state.financialTransactions.forEach(tx=>{if(tx.status==='pending'&&!tx.roaming){tx.status='captured';tx.failureReason=null;addTimeline(tx,'Batch reconciliation captured','Pending payment finalized by operator batch reconciliation.');const s=tx.session?sessionById(state,tx.session):null;if(s&&s.payment==='pending')s.payment='paid';processed++}else if(scope==='attention'&&tx.status==='failed'&&tx.retryable){tx.status='captured';tx.failureReason=null;addTimeline(tx,'Batch retry captured','Retryable payment captured during reconciliation.');processed++}else if((tx.status==='pending'&&tx.roaming)||(tx.status==='failed'&&!tx.retryable))skipped++});addCommand('Reconcile payments','Financial ledger','Success',`${processed} finalized · ${skipped} skipped${note?` · ${note}`:''}`);syncRevenueMeta();saveState(state);closeReconcile();persist(`${processed} payments reconciled · ${skipped} require separate handling`)});

function openSettlement(id){const s=settlementById(id);if(!s)return;currentSettlementId=id;$('#roaming-settlement-subtitle').textContent=`${s.partner} · ${s.period}`;$('#roaming-settlement-body').innerHTML=`<div class="ui-detail-grid"><div><span>Settlement</span><strong>${esc(s.id)}</strong></div><div><span>Status</span><strong><span class="ui-pill ${s.status==='reconciled'?'status-online':s.status==='attention'?'status-critical':'status-warning'}">${esc(s.status)}</span></strong></div><div><span>Sessions</span><strong>${fmt(s.sessions)}</strong></div><div><span>Gross CDR value</span><strong>${money(s.gross)}</strong></div><div><span>Operator receivable</span><strong>${money(s.operatorReceivable)}</strong></div><div><span>Partner fee</span><strong>${money(s.partnerFee)}</strong></div><div><span>Variance</span><strong>${money(s.variance)}</strong></div><div><span>Due date</span><strong>${esc(s.due)}</strong></div><div><span>Last sync</span><strong>${esc(s.lastSync)}</strong></div></div>${num(s.variance)?`<div class="ui-callout ui-callout--warning section-gap"><strong>Settlement variance</strong><span>${money(s.variance)} difference requires operator acceptance before reconciliation.</span></div>`:''}`;$('#roaming-settlement-confirm').disabled=s.status==='reconciled';$('#roaming-settlement-confirm').textContent=s.status==='reconciled'?'Already Reconciled':'Mark Reconciled';$('#roaming-settlement-dialog').showModal()}
function closeSettlement(){$('#roaming-settlement-dialog').close();currentSettlementId=null}
$('#roaming-settlement-close').addEventListener('click',closeSettlement);$('#roaming-settlement-cancel').addEventListener('click',closeSettlement);
$('#roaming-settlement-confirm').addEventListener('click',()=>{const s=settlementById(currentSettlementId);if(!s||s.status==='reconciled')return;s.status='reconciled';s.variance=0;s.lastSync=nowTime();addCommand('Reconcile roaming settlement',s.id,'Success',`${s.partner} · ${money(s.operatorReceivable)}`);saveState(state);closeSettlement();persist(`${s.partner} settlement reconciled`)});

function exportCsv(){const rows=[['Transaction','Date','Time','Type','Customer','Site','Charger','Session','Reservation','Gross AMD','Provider Fee AMD','Tax AMD','Net AMD','Provider','Payment Method','Status','Roaming Partner'],...filteredTransactions().map(tx=>[tx.id,tx.date,tx.time,tx.type,tx.customer,siteById(state,tx.site)?.name||tx.site,chargerById(state,tx.charger)?.name||tx.charger||'',tx.session||'',tx.reservation||'',tx.gross,tx.providerFee,tx.tax,tx.net,tx.provider||'',tx.paymentMethod||'',tx.status,tx.roamingPartner||''])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='voltdrive-revenue-transactions.csv';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);showToast('Revenue CSV exported')}
$('#revenue-export').addEventListener('click',exportCsv);

$('#revenue-drawer-close').addEventListener('click',closeDrawer);$('#revenue-drawer-backdrop').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#revenue-drawer').classList.contains('is-open'))closeDrawer()});
$$('[data-revenue-tab]').forEach(b=>b.addEventListener('click',()=>{currentTab=b.dataset.revenueTab;$$('[data-revenue-tab]').forEach(x=>x.classList.toggle('is-active',x===b));renderDrawer()}));
$$('[data-revenue-filter]').forEach(b=>b.addEventListener('click',()=>{filterMode=b.dataset.revenueFilter;$$('[data-revenue-filter]').forEach(x=>x.classList.toggle('is-active',x===b));renderTable()}));
['revenue-search','revenue-site','revenue-type','revenue-sort'].forEach(id=>$('#'+id).addEventListener(id==='revenue-search'?'input':'change',renderTable));

populateFilters();render();
const params=new URLSearchParams(location.search),sessionParam=params.get('session'),reservationParam=params.get('reservation'),siteParam=params.get('site'),chargerParam=params.get('charger');
if(siteParam&&siteById(state,siteParam)){$('#revenue-site').value=siteParam;renderTable()}
if(chargerParam)$('#revenue-search').value=chargerParam;
let deepTx=sessionParam?state.financialTransactions.find(tx=>tx.session===sessionParam):reservationParam?state.financialTransactions.find(tx=>tx.reservation===reservationParam):null;
if(chargerParam){renderTable();if(!deepTx)deepTx=state.financialTransactions.find(tx=>tx.charger===chargerParam)}
if(deepTx)requestAnimationFrame(()=>openTransaction(deepTx.id));
