import {loadState,saveState,siteById,chargerById,connectorById,sessionById} from '../core/operator-state.js';
import {initCommon,showToast} from '../layout/common.js';

const state=initCommon('support');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const num=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
const nowTime=()=>new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const reservationById=id=>state.reservations.find(x=>x.id===id);
const txById=id=>state.financialTransactions?.find(x=>x.id===id);
const bayById=id=>state.parkingBays?.find(x=>x.id===id || x.label===id);
const caseById=id=>state.supportCases.find(x=>x.id===id);
const activeStatuses=new Set(['open','in_progress','pending','escalated']);
let currentCaseId=null,currentTab='overview',filterMode='active';

function pretty(v){return String(v||'—').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function priorityRank(v){return ({critical:4,high:3,normal:2,low:1})[v]||0}
function slaPercent(c){return c.slaTargetMin?Math.round(num(c.elapsedMin,c.ageMin)/num(c.slaTargetMin,60)*100):0}
function slaState(c){const p=slaPercent(c);return p>=100?'breached':p>=80?'risk':p>=60?'watch':'healthy'}
function siteName(id){return siteById(state,id)?.name||id||'—'}
function chargerName(id){const c=chargerById(state,id);return c?`${c.name} · ${c.model}`:(id||'—')}
function statusClass(s){return `status-${String(s||'open').replaceAll(' ','-')}`}
function addTimeline(c,type,title,detail){c.timeline=Array.isArray(c.timeline)?c.timeline:[];c.timeline.push({time:nowTime(),type,title,detail})}
function addCommand(action,target,result='Success',detail=''){state.commandHistory.unshift({id:`CMD-${String(Date.now()).slice(-7)}`,time:nowTime(),action,target,result,operator:state.network.operator,detail})}
function persist(message,open=true){saveState(state);render();if(open&&currentCaseId)renderDrawer();showToast(message)}

function populateFilters(){
 const siteSel=$('#support-site'),newSite=$('#support-new-site');
 state.sites.forEach(s=>{siteSel.insertAdjacentHTML('beforeend',`<option value="${esc(s.id)}">${esc(s.name)}</option>`);newSite.insertAdjacentHTML('beforeend',`<option value="${esc(s.id)}">${esc(s.name)}</option>`)});
 updateNewChargers();
}
function updateNewChargers(){const site=$('#support-new-site').value,sel=$('#support-new-charger');sel.innerHTML='<option value="">No charger</option>';state.chargers.filter(c=>!site||c.site===site).forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${esc(c.id)}">${esc(c.name)} · ${esc(c.model)}</option>`))}

function filteredCases(){
 const q=$('#support-search').value.trim().toLowerCase(),site=$('#support-site').value,cat=$('#support-category').value,channel=$('#support-channel').value,sort=$('#support-sort').value;
 let rows=state.supportCases.filter(c=>{
  if(filterMode==='active'&&!activeStatuses.has(c.status))return false;
  if(filterMode!=='all'&&filterMode!=='active'&&c.status!==filterMode)return false;
  if(site!=='all'&&c.site!==site)return false;if(cat!=='all'&&c.category!==cat)return false;if(channel!=='all'&&c.channel!==channel)return false;
  if(q){const hay=[c.id,c.customer,c.subject,c.site,c.charger,c.session,c.reservation,c.transaction,c.vehicle,c.owner,c.team].join(' ').toLowerCase();if(!hay.includes(q))return false}
  return true;
 });
 rows.sort((a,b)=>{
  if(sort==='oldest')return num(b.elapsedMin,b.ageMin)-num(a.elapsedMin,a.ageMin);
  if(sort==='newest')return num(a.elapsedMin,a.ageMin)-num(b.elapsedMin,b.ageMin);
  if(sort==='priority')return priorityRank(b.priority)-priorityRank(a.priority);
  const score=c=>(slaState(c)==='breached'?500:slaState(c)==='risk'?350:slaState(c)==='watch'?150:0)+priorityRank(c.priority)*50+num(c.elapsedMin,c.ageMin)/10;
  return score(b)-score(a);
 });return rows;
}

function renderKpis(){const active=state.supportCases.filter(c=>activeStatuses.has(c.status));$('#support-kpi-open').textContent=active.length;$('#support-kpi-urgent').textContent=active.filter(c=>['critical','high'].includes(c.priority)).length;$('#support-kpi-sla').textContent=active.filter(c=>['risk','breached'].includes(slaState(c))).length;$('#support-kpi-pending').textContent=state.supportCases.filter(c=>c.status==='pending').length;$('#support-kpi-resolved').textContent=state.supportCases.filter(c=>c.status==='resolved').length}
function renderTable(){const rows=filteredCases();$('#support-result-count').textContent=`${rows.length} case${rows.length===1?'':'s'}`;$('#support-table-body').innerHTML=rows.map(c=>{const site=siteById(state,c.site),sla=slaState(c),pct=Math.min(140,Math.max(0,slaPercent(c)));return `<tr data-case-id="${esc(c.id)}" class="${sla==='breached'?'support-row--breached':sla==='risk'?'support-row--risk':''}"><td><div class="entity-main"><strong>${esc(c.id)}</strong><span>${esc(c.subject)}</span></div></td><td><div class="entity-main"><strong>${esc(c.customer)}</strong><span>${esc(c.vehicle||c.customerPlan||'Customer')}</span></div></td><td><div class="entity-main"><strong>${esc(site?.name||c.site||'No site')}</strong><span>${esc(c.charger||c.session||c.reservation||c.transaction||'General support')}</span></div></td><td><span class="ui-pill priority-${esc(c.priority)}">${esc(c.priority)}</span></td><td><span class="ui-pill ${statusClass(c.status)}">${esc(pretty(c.status))}</span></td><td><div class="support-sla-cell"><div><strong>${pct}%</strong><span>${esc(pretty(sla))}</span></div><i><b style="width:${Math.min(100,pct)}%"></b></i></div></td><td><div class="entity-main"><strong>${esc(c.owner||'Unassigned')}</strong><span>${esc(c.team||'Support')}</span></div></td><td><span class="support-channel-icon support-channel-icon--${esc(c.channel)}">${c.channel==='phone'?'☎':c.channel==='email'?'✉':'◌'}</span></td></tr>`}).join('')||`<tr><td colspan="8" class="support-empty">No support cases match these filters.</td></tr>`;$$('[data-case-id]').forEach(r=>r.addEventListener('click',()=>openCase(r.dataset.caseId)))}
function renderSla(){const rows=state.supportCases.filter(c=>activeStatuses.has(c.status)).sort((a,b)=>slaPercent(b)-slaPercent(a)).slice(0,5);$('#support-sla-list').innerHTML=rows.map(c=>`<button class="support-side-row" data-sla-case="${esc(c.id)}"><span class="support-side-icon support-side-icon--${esc(slaState(c))}">${slaState(c)==='breached'?'!':slaState(c)==='risk'?'↑':'◷'}</span><div><strong>${esc(c.id)} · ${esc(c.customer)}</strong><span>${esc(c.subject)}</span></div><span class="ui-pill ${slaState(c)==='breached'?'status-critical':slaState(c)==='risk'?'status-warning':'status-monitoring'}">${slaPercent(c)}%</span></button>`).join('')||'<div class="support-empty">No active SLA cases.</div>';$$('[data-sla-case]').forEach(b=>b.addEventListener('click',()=>openCase(b.dataset.slaCase)))}
function renderWorkload(){const cats=['charging','reservation','billing','access','general'];const active=state.supportCases.filter(c=>activeStatuses.has(c.status)),max=Math.max(1,...cats.map(x=>active.filter(c=>c.category===x).length));$('#support-workload').innerHTML=cats.map(cat=>{const n=active.filter(c=>c.category===cat).length;return `<div class="support-workload-row"><div><strong>${esc(pretty(cat))}</strong><span>${n} active</span></div><i><b style="width:${n/max*100}%"></b></i></div>`}).join('')}
function render(){renderKpis();renderTable();renderSla();renderWorkload()}

function openCase(id){const c=caseById(id);if(!c)return;currentCaseId=id;currentTab='overview';$$('[data-support-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.supportTab==='overview'));$('#support-drawer').classList.add('is-open');$('#support-drawer-backdrop').classList.add('is-visible');renderDrawer()}
function closeDrawer(){$('#support-drawer').classList.remove('is-open');$('#support-drawer-backdrop').classList.remove('is-visible');currentCaseId=null}
function caseSummary(c){return `<div class="support-summary-banner"><div><span class="ui-pill priority-${esc(c.priority)}">${esc(c.priority)}</span><h3>${esc(c.subject)}</h3><p>${esc(c.summary||'No detailed customer summary recorded.')}</p></div><div class="support-summary-status"><strong>${slaPercent(c)}%</strong><span>SLA · ${esc(pretty(slaState(c)))}</span></div></div>`}
function overviewTab(c){return `${caseSummary(c)}<section class="ui-detail-section"><h3>Case Status</h3><div class="ui-detail-grid"><div><span>Status</span><strong><span class="ui-pill ${statusClass(c.status)}">${esc(pretty(c.status))}</span></strong></div><div><span>Priority</span><strong><span class="ui-pill priority-${esc(c.priority)}">${esc(c.priority)}</span></strong></div><div><span>Owner</span><strong>${esc(c.owner||'Unassigned')}</strong></div><div><span>Team</span><strong>${esc(c.team||'Network Support')}</strong></div><div><span>Channel</span><strong>${esc(pretty(c.channel))}</strong></div><div><span>SLA Target</span><strong>${num(c.slaTargetMin,60)} min</strong></div><div><span>Elapsed</span><strong>${num(c.elapsedMin,c.ageMin)} min</strong></div><div><span>Customer Plan</span><strong>${esc(c.customerPlan||'Standard')}</strong></div></div></section><section class="ui-detail-section"><h3>Customer Need</h3><div class="ui-callout"><strong>Requested outcome</strong><span>${esc(c.desiredResolution||'Resolve the reported issue and confirm outcome to the customer.')}</span></div>${c.resolution?`<div class="ui-callout section-gap"><strong>Resolution</strong><span>${esc(c.resolution)}</span></div>`:''}</section><section class="ui-detail-section"><h3>Tags</h3><div class="support-tags">${(c.tags||[]).map(t=>`<span class="panel-chip">${esc(t)}</span>`).join('')||'<span class="panel-chip">No tags</span>'}</div></section>`}
function contextAction(href,icon,title,meta){return `<a class="ui-action-card support-related-card" href="${esc(href)}"><span class="support-related-icon">${icon}</span><div><strong>${esc(title)}</strong><span>${esc(meta)}</span></div></a>`}
function contextTab(c){const s=c.session?sessionById(state,c.session):null,r=c.reservation?reservationById(c.reservation):null,tx=c.transaction?txById(c.transaction):null,ch=c.charger?chargerById(state,c.charger):null,con=c.connector?connectorById(state,c.connector):null,bay=c.bay?bayById(c.bay):null;return `<section class="ui-detail-section"><h3>Customer</h3><div class="ui-detail-grid"><div><span>Customer</span><strong>${esc(c.customer)}</strong></div><div><span>Vehicle</span><strong>${esc(c.vehicle||'—')}</strong></div><div><span>Phone</span><strong>${esc(c.customerPhone||'—')}</strong></div><div><span>Email</span><strong>${esc(c.customerEmail||'—')}</strong></div></div></section><section class="ui-detail-section"><h3>Operational Context</h3><div class="ui-detail-grid"><div><span>Site</span><strong>${esc(siteName(c.site))}</strong></div><div><span>Charger</span><strong>${esc(ch?.name||c.charger||'—')}</strong></div><div><span>Connector</span><strong>${esc(con?`${con.type} · ${con.id}`:(c.connector||'—'))}</strong></div><div><span>Parking Bay</span><strong>${esc(bay?.label||c.bay||'—')}</strong></div></div><div class="support-related-list">${c.site?contextAction(`sites.html?site=${encodeURIComponent(c.site)}`,'◇',siteName(c.site),'Open site operations'):''}${c.charger?contextAction(`chargers.html?charger=${encodeURIComponent(c.charger)}`,'ϟ',chargerName(c.charger),'Open charger details'):''}${s?contextAction(`sessions.html?session=${encodeURIComponent(s.id)}`,'◉',s.id,`${pretty(s.status)} · ${num(s.soc)}% SOC · ${num(s.powerKw)} kW`):''}${r?contextAction(`reservations.html?reservation=${encodeURIComponent(r.id)}`,'▣',r.id,`${pretty(r.status)} · ${r.arrival||'No arrival time'}`):''}${tx?contextAction(`revenue.html?session=${encodeURIComponent(tx.session||'')}&reservation=${encodeURIComponent(tx.reservation||'')}`,'¤',tx.id,`${pretty(tx.status)} · ${num(tx.gross).toLocaleString()} AMD`):''}</div></section>`}
function conversationTab(c){const tl=[...(c.timeline||[])].reverse();const notes=[...(c.internalNotes||[])].reverse();return `<section class="ui-detail-section"><h3>Case Timeline</h3><div class="support-timeline">${tl.map(e=>`<div class="support-timeline-row"><span class="support-timeline-dot support-timeline-dot--${esc(e.type||'system')}"></span><div><div><strong>${esc(e.title)}</strong><span>${esc(e.time)}</span></div><p>${esc(e.detail)}</p></div></div>`).join('')||'<div class="support-empty">No timeline events.</div>'}</div></section><section class="ui-detail-section"><h3>Internal Notes</h3><div class="support-notes">${notes.map(n=>`<article><div><strong>${esc(n.author||'Operator')}</strong><span>${esc(n.time)}</span></div><p>${esc(n.text)}</p></article>`).join('')||'<div class="support-empty">No internal notes yet.</div>'}</div></section>`}
function actionButton(icon,title,meta,attr,disabled=false){return `<button class="support-control-card" type="button" ${attr} ${disabled?'disabled':''}><span class="support-control-icon">${icon}</span><div><strong>${esc(title)}</strong><small>${esc(meta)}</small></div></button>`}
function actionsTab(c){const s=c.session?sessionById(state,c.session):null,con=c.connector?connectorById(state,c.connector):null,r=c.reservation?reservationById(c.reservation):null,tx=c.transaction?txById(c.transaction):null,bay=c.bay?bayById(c.bay):null;const activeSession=s?.status==='active';const cableReleaseBlocked=Boolean(activeSession);let contextual='';if(s)contextual+=actionButton('■','Stop Session Safely',activeSession?'End backend session and release charging allocation.':'Session is not active.',`data-support-stop-session`,!activeSession);if(con)contextual+=actionButton('↧','Release Cable',activeSession?'Stop the active session first.':con.locked?'Send connector unlock command.':'Connector is already unlocked.',`data-support-release-cable`,activeSession||!con.locked);if(r)contextual+=actionButton('+5','Extend Grace +5 min',`Current grace period: ${num(r.graceMin,10)} min.`,`data-support-extend-grace`,['completed','cancelled','no_show'].includes(r.status));if(bay)contextual+=actionButton('S','Dispatch Site Security',`Parking bay ${bay.label||c.bay} · ${pretty(bay.status)}.`,`data-support-security`);if(tx)contextual+=actionButton('¤','Create Refund Review',`Transaction ${tx.id} · ${pretty(tx.status)}.`,`data-support-refund-review`,state.refunds?.some(x=>x.transaction===tx.id&&x.status==='review'));if(c.category==='charging'||c.charger)contextual+=actionButton('!','Escalate to Maintenance','Create a technical maintenance alert linked to this case.',`data-support-maintenance`);return `${caseSummary(c)}<section class="ui-detail-section"><h3>Operator Controls</h3><div class="support-control-grid">${contextual||'<div class="support-empty">No context-specific operator actions for this case.</div>'}</div></section><section class="ui-detail-section"><h3>Case Management</h3><div class="support-control-grid">${actionButton('@','Assign Case','Change team or case owner.','data-support-assign')}${actionButton('✎','Add Update','Internal note or customer communication.','data-support-message')}${c.status==='resolved'?actionButton('↺','Reopen Case','Return this case to the active queue.','data-support-reopen'):actionButton('✓','Resolve Case','Close the case with a resolution note.','data-support-resolve')}</div></section>`}
function renderDrawer(){const c=caseById(currentCaseId);if(!c)return;$('#support-drawer-title').textContent=`${c.id} · ${c.customer}`;$('#support-drawer-subtitle').textContent=`${siteName(c.site)} · ${pretty(c.category)} · ${pretty(c.channel)}`;$('#support-drawer-body').innerHTML=currentTab==='overview'?overviewTab(c):currentTab==='context'?contextTab(c):currentTab==='conversation'?conversationTab(c):actionsTab(c);const footer=[];if(c.status!=='resolved')footer.push(`<button class="button button--secondary" type="button" data-footer-message>Add Update</button>`,`<button class="button button--primary" type="button" data-footer-resolve>Resolve</button>`);else footer.push(`<button class="button button--secondary" type="button" data-footer-reopen>Reopen Case</button>`);$('#support-drawer-footer').innerHTML=footer.join('');bindDrawerActions(c)}
function bindDrawerActions(c){$('[data-footer-message]')?.addEventListener('click',()=>openMessage(c));$('[data-footer-resolve]')?.addEventListener('click',()=>openResolve(c));$('[data-footer-reopen]')?.addEventListener('click',()=>reopenCase(c));$('[data-support-assign]')?.addEventListener('click',()=>openAssign(c));$('[data-support-message]')?.addEventListener('click',()=>openMessage(c));$('[data-support-resolve]')?.addEventListener('click',()=>openResolve(c));$('[data-support-reopen]')?.addEventListener('click',()=>reopenCase(c));$('[data-support-stop-session]')?.addEventListener('click',()=>stopSession(c));$('[data-support-release-cable]')?.addEventListener('click',()=>releaseCable(c));$('[data-support-extend-grace]')?.addEventListener('click',()=>extendGrace(c));$('[data-support-security]')?.addEventListener('click',()=>dispatchSecurity(c));$('[data-support-refund-review]')?.addEventListener('click',()=>createRefundReview(c));$('[data-support-maintenance]')?.addEventListener('click',()=>escalateMaintenance(c))}

function stopSession(c){const s=sessionById(state,c.session);if(!s||s.status!=='active'){showToast('No active session to stop');return}s.status='completed';s.ended=nowTime();s.stopReason='Customer support intervention';s.operatorStopReason='Customer support intervention';s.powerKw=0;s.events=Array.isArray(s.events)?s.events:[];s.events.push({time:nowTime(),type:'operator',title:'Session stopped by support operator',detail:`Triggered from support case ${c.id}.`});const con=connectorById(state,s.connector);if(con){con.status='available';con.locked=false}const ch=chargerById(state,s.charger);if(ch&&ch.status==='busy')ch.status='online';if(s.payment==='preauthorized')s.payment='pending';addTimeline(c,'action','Charging session stopped',`${s.id} ended safely by operator support intervention.`);c.status='in_progress';addCommand('Stop session',s.id,'Success',`Support case ${c.id}`);persist(`Session ${s.id} stopped safely`)}
function releaseCable(c){const con=connectorById(state,c.connector);if(!con){showToast('No connector attached to case');return}const active=state.sessions.find(s=>s.connector===con.id&&s.status==='active');if(active){showToast(`Stop active session ${active.id} before releasing cable`);return}if(!con.locked){showToast('Cable is already unlocked');return}con.locked=false;if(con.status==='busy')con.status='available';addTimeline(c,'action','Cable released',`${con.id} unlock command completed successfully.`);c.status='in_progress';addCommand('Release cable',con.id,'Success',`Support case ${c.id}`);persist(`Cable released on ${con.id}`)}
function extendGrace(c){const r=reservationById(c.reservation);if(!r){showToast('No reservation attached');return}if(['completed','cancelled','no_show'].includes(r.status)){showToast('Reservation can no longer be extended');return}r.graceMin=num(r.graceMin,10)+5;r.timeline=Array.isArray(r.timeline)?r.timeline:[];r.timeline.push({time:nowTime(),type:'operator',title:'Grace period extended',detail:`Extended by 5 minutes from support case ${c.id}.`});addTimeline(c,'action','Reservation grace extended',`${r.id} grace period is now ${r.graceMin} minutes.`);addCommand('Extend reservation grace',r.id,'Success',`+5 min · ${c.id}`);persist(`Reservation ${r.id} grace extended to ${r.graceMin} min`)}
function dispatchSecurity(c){const bay=bayById(c.bay);addTimeline(c,'action','Site security dispatched',`${siteName(c.site)} security requested to inspect ${bay?.label||c.bay||'customer bay'}.`);c.status='in_progress';addCommand('Dispatch site security',c.site||c.id,'Success',`${bay?.label||c.bay||'Bay issue'} · ${c.id}`);persist(`Site security notified for ${c.id}`)}
function createRefundReview(c){const tx=txById(c.transaction);if(!tx){showToast('No financial transaction attached');return}state.refunds=Array.isArray(state.refunds)?state.refunds:[];const existing=state.refunds.find(x=>x.transaction===tx.id&&x.status==='review');if(existing){showToast(`Refund review ${existing.id} already exists`);return}const amount=Math.max(0,num(tx.gross)-num(tx.refundedAmount));const rf={id:`RF-${String(Date.now()).slice(-7)}`,transaction:tx.id,date:'2026-08-17',time:nowTime(),amount,status:'review',reason:'Customer support review',customer:c.customer,operator:state.network.operator,note:`Created from support case ${c.id}.`};state.refunds.unshift(rf);addTimeline(c,'action','Refund review created',`${rf.id} opened for transaction ${tx.id}.`);c.status='pending';addCommand('Create refund review',tx.id,'Success',`${rf.id} · ${c.id}`);persist(`Refund review ${rf.id} created`)}
function escalateMaintenance(c){state.maintenanceAlerts=Array.isArray(state.maintenanceAlerts)?state.maintenanceAlerts:[];const existing=state.maintenanceAlerts.find(a=>a.supportCase===c.id&&a.status!=='resolved');if(existing){showToast(`Maintenance alert ${existing.id} already linked`);return}const id=`AL-${String(Date.now()).slice(-5)}`;const alert={id,site:c.site||null,charger:c.charger||null,connector:c.connector||null,severity:['critical','high'].includes(c.priority)?c.priority:'normal',status:'open',code:'SUP-ESC',title:`Customer support escalation · ${c.subject}`,body:c.summary||c.subject,created:nowTime(),ticket:null,supportCase:c.id,source:'operator',category:c.category==='billing'?'support':'charger',customerImpact:['critical','high'].includes(c.priority)?'High':'Medium',occurrences:1,affectedSessions:c.session?1:0,slaTargetMin:45,elapsedMin:0,probableCauses:['Customer-reported operational issue requires technical verification'],suggestedRecovery:['Review charger and connector telemetry','Validate issue on site if remote checks are inconclusive'],recoveryAttempts:[],diagnostics:{},timeline:[{time:nowTime(),type:'ticket',title:'Alert created from Customer Support',detail:`Escalated from ${c.id} by ${state.network.operator}.`}]} ;state.maintenanceAlerts.unshift(alert);c.status='escalated';addTimeline(c,'escalation','Escalated to Maintenance',`${id} created and linked to this customer case.`);addCommand('Escalate support to maintenance',c.id,'Success',id);persist(`Maintenance alert ${id} created`)}
function reopenCase(c){c.status='open';c.resolution=null;c.resolvedAt=null;addTimeline(c,'action','Case reopened','Operator returned the case to the active support queue.');addCommand('Reopen support case',c.id,'Success');persist(`${c.id} reopened`)}

function openNewCase(){$('#support-new-customer').value='';$('#support-new-subject').value='';$('#support-new-message').value='';$('#support-new-priority').value='normal';$('#support-new-category').value='charging';$('#support-new-site').value='';updateNewChargers();$('#support-new-dialog').showModal()}
function closeNew(){$('#support-new-dialog').close()}
function createCase(){const customer=$('#support-new-customer').value.trim(),subject=$('#support-new-subject').value.trim(),message=$('#support-new-message').value.trim();if(!customer||!subject||!message){showToast('Customer, subject and message are required');return}const id=`SUP-${String(Date.now()).slice(-4)}`,priority=$('#support-new-priority').value,site=$('#support-new-site').value||null,charger=$('#support-new-charger').value||null,channel=$('#support-new-channel').value,category=$('#support-new-category').value;state.supportCases.unshift({id,customer,subject,site,charger,connector:null,priority,status:'open',ageMin:0,elapsedMin:0,channel,category,slaTargetMin:priority==='critical'?10:priority==='high'?20:priority==='low'?120:45,owner:'Unassigned',team:'Network Support',summary:message,desiredResolution:'Investigate customer request and provide a confirmed resolution.',tags:[pretty(category)],internalNotes:[],timeline:[{time:nowTime(),type:'customer',title:`${pretty(channel)} case opened`,detail:message}]});addCommand('Create support case',id,'Success',subject);saveState(state);closeNew();render();openCase(id);showToast(`${id} created`)}
function openMessage(c){$('#support-message-title').textContent='Add Case Update';$('#support-message-subtitle').textContent=`${c.id} · ${c.customer}`;$('#support-message-text').value='';$('#support-message-type').value='note';$('#support-message-status').value='keep';$('#support-message-dialog').showModal()}
function closeMessage(){$('#support-message-dialog').close()}
function saveMessage(){const c=caseById(currentCaseId),text=$('#support-message-text').value.trim();if(!c||!text){showToast('Enter an update message');return}const type=$('#support-message-type').value,newStatus=$('#support-message-status').value;if(type==='note'){c.internalNotes=Array.isArray(c.internalNotes)?c.internalNotes:[];c.internalNotes.push({time:nowTime(),author:state.network.operator,text});addTimeline(c,'note','Internal note added',text)}else addTimeline(c,'customer','Customer update sent',text);if(newStatus!=='keep')c.status=newStatus;else if(c.status==='open')c.status='in_progress';addCommand(type==='note'?'Add support note':'Send customer update',c.id,'Success');saveState(state);closeMessage();persist(type==='note'?'Internal note saved':'Customer update recorded')}
function openAssign(c){$('#support-assign-subtitle').textContent=`${c.id} · ${c.customer}`;$('#support-assign-team').value=[...$('#support-assign-team').options].some(o=>o.value===c.team)?c.team:'Network Operations';$('#support-assign-owner').value=[...$('#support-assign-owner').options].some(o=>o.value===c.owner)?c.owner:'Arman Hakobyan';$('#support-assign-dialog').showModal()}
function closeAssign(){$('#support-assign-dialog').close()}
function assignCase(){const c=caseById(currentCaseId);if(!c)return;c.team=$('#support-assign-team').value;c.owner=$('#support-assign-owner').value;if(c.status==='open')c.status='in_progress';addTimeline(c,'assignment','Case assigned',`${c.owner} · ${c.team}`);addCommand('Assign support case',c.id,'Success',`${c.owner} · ${c.team}`);saveState(state);closeAssign();persist(`${c.id} assigned to ${c.owner}`)}
function openResolve(c){$('#support-resolve-subtitle').textContent=`${c.id} · ${c.customer}`;$('#support-resolve-note').value='';$('#support-resolve-dialog').showModal()}
function closeResolve(){$('#support-resolve-dialog').close()}
function resolveCase(){const c=caseById(currentCaseId),note=$('#support-resolve-note').value.trim();if(!c||!note){showToast('Resolution note is required');return}const type=$('#support-resolve-type').value;c.status='resolved';c.resolution=`${type}: ${note}`;c.resolvedAt=nowTime();addTimeline(c,'resolved','Case resolved',c.resolution);addCommand('Resolve support case',c.id,'Success',type);saveState(state);closeResolve();persist(`${c.id} resolved`)}
function assignNext(){const c=state.supportCases.filter(x=>activeStatuses.has(x.status)&&x.owner!=='Arman Hakobyan').sort((a,b)=>slaPercent(b)-slaPercent(a)||priorityRank(b.priority)-priorityRank(a.priority))[0];if(!c){showToast('No unassigned SLA case available');return}c.owner='Arman Hakobyan';c.team='Network Operations';if(c.status==='open')c.status='in_progress';addTimeline(c,'assignment','Assigned from SLA queue',`${state.network.operator} accepted next attention case.`);addCommand('Assign next SLA case',c.id,'Success');saveState(state);render();openCase(c.id);showToast(`${c.id} assigned to you`)}

$('#support-new-case').addEventListener('click',openNewCase);$('#support-assign-next').addEventListener('click',assignNext);$('#support-new-close').addEventListener('click',closeNew);$('#support-new-cancel').addEventListener('click',closeNew);$('#support-new-confirm').addEventListener('click',createCase);$('#support-new-site').addEventListener('change',updateNewChargers);
$('#support-message-close').addEventListener('click',closeMessage);$('#support-message-cancel').addEventListener('click',closeMessage);$('#support-message-confirm').addEventListener('click',saveMessage);
$('#support-assign-close').addEventListener('click',closeAssign);$('#support-assign-cancel').addEventListener('click',closeAssign);$('#support-assign-confirm').addEventListener('click',assignCase);
$('#support-resolve-close').addEventListener('click',closeResolve);$('#support-resolve-cancel').addEventListener('click',closeResolve);$('#support-resolve-confirm').addEventListener('click',resolveCase);
$('#support-drawer-close').addEventListener('click',closeDrawer);$('#support-drawer-backdrop').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#support-drawer').classList.contains('is-open'))closeDrawer()});
$$('[data-support-tab]').forEach(b=>b.addEventListener('click',()=>{currentTab=b.dataset.supportTab;$$('[data-support-tab]').forEach(x=>x.classList.toggle('is-active',x===b));renderDrawer()}));
$$('[data-support-filter]').forEach(b=>b.addEventListener('click',()=>{filterMode=b.dataset.supportFilter;$$('[data-support-filter]').forEach(x=>x.classList.toggle('is-active',x===b));renderTable()}));
['support-site','support-category','support-channel','support-sort'].forEach(id=>$('#'+id).addEventListener('change',renderTable));$('#support-search').addEventListener('input',renderTable);

populateFilters();render();
const params=new URLSearchParams(location.search),caseParam=params.get('case'),sessionParam=params.get('session'),reservationParam=params.get('reservation'),transactionParam=params.get('transaction'),siteParam=params.get('site'),chargerParam=params.get('charger');if(siteParam&&siteById(state,siteParam)){$('#support-site').value=siteParam;renderTable()}if(chargerParam){$('#support-search').value=chargerParam;renderTable()}let deep=caseParam?caseById(caseParam):sessionParam?state.supportCases.find(c=>c.session===sessionParam):reservationParam?state.supportCases.find(c=>c.reservation===reservationParam):transactionParam?state.supportCases.find(c=>c.transaction===transactionParam):chargerParam?state.supportCases.find(c=>c.charger===chargerParam):null;if(deep)requestAnimationFrame(()=>openCase(deep.id));
